### ISSUE TITLE
Nightly v0.4.0-1928-gd3c17d50d is segfaulting on `:!tmux split`

### ISSUE THREAD

**Issue by unclechu** [neovim/neovim#10927]
```bash
nvim -u NORC
```
And then in Neovim:
```bash
:!tmux split
```
And after a split in tmux I got:
```
nvim: %confidential-path%/neovim-nightly-v0.4.0-1928-gd3c17d50d/src/nvim/message.c:2241: msg_scroll_flush: Assertion `row >= 0' failed.
Aborted (core dumped)
```

**Comment by justinmk** [comment]
Thanks for the repro, merging this with https://github.com/neovim/neovim/issues/10924

**Comment by unclechu** [comment]
@justinmk @bfredl In `v0.4.0-2014-g554566cce` segfault is fixed, but when I do vertical `tmux split -h` some extra lines are appeared or the screen is redrawn not at the right time, I don't know, you can compare:

`v0.4.0-2014-g554566cce`:
![Screenshot from 2019-09-09 00-05-35](https://user-images.githubusercontent.com/799353/64494480-16be2c00-d296-11e9-96e1-705aadffd8e1.png)

`v0.4.0-1860-g0ec80d5f6`:
![Screenshot from 2019-09-09 00-05-58](https://user-images.githubusercontent.com/799353/64494487-263d7500-d296-11e9-971a-870d5570804f.png)

**Comment by bfredl** [comment]
Yes, the screen is not resized/redrawn until after you press RETURN. But I would think the TUI code would just cut the screen in half on this occasion, so you would still see the left half of the message...

**Comment by unclechu** [comment]
@bfredl Is it possible to somehow force it to trigger that _RETURN_ automatically after a command is executed?

**Comment by justinmk** [comment]
You can send `<CR>` via `nvim_input()` or feedkeys(), etc. Please use https://vi.stackexchange.com for usage questions.

**Comment by unclechu** [comment]
@justinmk This works for me:
```viml
:cal nvim_input('<cr>')|!tmux sp -h
```
Thanks

**Comment by bfredl** [comment]
@unclechu I suppose `:silent !tmux split` works well enough.

**Comment by unclechu** [comment]
@bfredl Yep, `:sil !tmux sp -h` works too, thanks again!
