### ISSUE TITLE
Cannot type dot '.' 

### ISSUE THREAD

**Issue by LoafingBunny** [neovim/neovim#11255]
Hi, I'm using neovim but every time I try to type the dot, it get interpreted as canc.
This happens both in normal mode and in edit mode
Keyboard layout is italian, but the windows terminal correctly show the dot - eg in the command line. The same happens when using the old windows cmd.exe or powershell core.

- `nvim --version`: 0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: windows 10 32bit
- Terminal name/version: windows terminal preview
- `$TERM`:

**Comment by blueyed** [comment]
Also with `nvim -u NONE` / `nvim -u NORC`?

**Comment by blueyed** [comment]
If so, does changing the keyboard layout to english make a difference?

**Comment by LoafingBunny** [comment]
I've tried with -u NORC and it's the same. Later I'll try with the english keyboard layout

**Comment by erw7** [comment]
@LoafingBunny Can you show me the `key.log` created in the next step using following nvim with debug output created in #11061?

- [64bit](https://ci.appveyor.com/project/neovim/neovim/builds/27541438/job/692nw7o2i4j1ganu/artifacts)
- [32bit](https://ci.appveyor.com/project/neovim/neovim/builds/27541438/job/2kg2cjdfcfmie59g/artifacts)

```
nvim -u NORC 2> key.log
.
:q
```

**Comment by LoafingBunny** [comment]
The same happens when the keyboard layout is UK, and nvim is executed with '-u NONE'.
Here is the output with the debug:

[key.log](https://github.com/neovim/neovim/files/3747658/key.log)

**Comment by erw7** [comment]
@LoafingBunny thanks. Looking at `key.log`, the next artifact built with #11061 also should fix this problem.

- [64bit](https://ci.appveyor.com/project/neovim/neovim/builds/27575561/job/r85oqk88yiccp328/artifacts)
- [32bit](https://ci.appveyor.com/project/neovim/neovim/builds/27575561/job/lf8yc5i2842spf1x/artifacts)

**Comment by LoafingBunny** [comment]
thank you! I'll try the new built asap

**Comment by LoafingBunny** [comment]
nope sorry it still doesn't work. I've also tried the latest nightly build.
Again when I run ".\Neovim\bin\nvim.exe -u NONE" the dot is mapped as canc.

**Comment by erw7** [comment]
>nope sorry it still doesn't work.

@LoafingBunny I'm checking just to be sure, but did you use `Neovim.zip`? The problem exists in `uv.dll`, so downloading just a new build of `nvim.exe` will not fix the problem. As long as I look at your `key.log`, using the new `uv.dll` should solve the problem.

**Comment by LoafingBunny** [comment]
For sure I downloaded just the nvim.exe, but I downloaded the .zip too, and I'm pretty sure I tried both of them because the path is Neovim\bin\nvim.exe 
Anyway I'll double check

**Comment by erw7** [comment]
@LoafingBunny Hasn't it been fixed in the latest nightly?

**Comment by vimalaguti** [comment]
Hi, I cannot check, sorry. I decided to use nvim on SSH on a linux server in the meantime.

**Comment by kuripa** [comment]
Hi, it seems to be fixed.

- `nvim --version` : v0.6.1
- `nvim -u NORC`
- Windows Terminal v1.12.10334.0
- Powershell: v5.1.19041.1320
