### ISSUE TITLE
LSP hover window is not cleared for successive call

### ISSUE THREAD

**Issue by e-kwsm** [neovim/neovim#11508]
- `nvim --version`: v0.5.0-226-gb1e4ec1c2
- `vim -u DEFAULTS` (version: ) behaves differently? n/a
- Operating system/version: Debian 10.2
- Terminal name/version: GNOME Terminal 3.30.2 using VTE 0.54.2 +GNUTLS
- `$TERM`: xterm-256color
- `g:python3_host_prog`: Python 3.7.3
- neovim/nvim-lsp@bf657b837ee0aad20afd812ea14d73108bb30093
- pynvim: 0.4.0
- python-language-server: 0.31.2

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:so vimrc
```

vimrc:
```vim
set runtimepath+=/path/to/nvim-lsp
call nvim_lsp#setup('pyls', {})
```

Open the following python file:
```python
def f():
    """
    =========
    docstring
    =========
    """
    pass


f()
```

Go to the bottom and on `f` execute `lua vim.lsp.buf.hover()` and 
successively `lua vim.lsp.buf.signature_help()`, or vice versa.

### Actual behaviour
Contents of `lua vim.lsp.buf.hover()` is not cleared.

![asciinema](https://user-images.githubusercontent.com/11627708/71406624-1fd3dd00-267c-11ea-9a9f-39bf43f679eb.gif)

### Expected behaviour
Contents of `lua vim.lsp.buf.hover()` is cleared.

**Comment by norcalli** [comment]
So the idea is that only one floating window should be available at all times from the LSP?

**Comment by e-kwsm** [comment]
> So the idea is that only one floating window should be available at all times from the LSP?

It would be favourable.

Also, vertical movement in insert mode (e.g., `O<CR>` and `a<CR>`) does not clear the window:
![vertical](https://user-images.githubusercontent.com/11627708/71407706-2b74d300-267f-11ea-8acd-6b8ddaf78718.gif)

**Comment by norcalli** [comment]
Yeah I have noticed the insert mode one myself. I didn't put enough thought into all of the various hover cancellation scenarios. It almost feels like binding to every single autocmd wouldn't be incorrect.

**Comment by norcalli** [comment]
I'll fix this for every scenario I come up with right now, but feel free to help me brainstorm/report more cases so that I don't miss anything @e-kwsm

**Comment by mjlbach** [comment]
@e-kwsm Can you test if this is the case now that #14649 is merged?

**Comment by e-kwsm** [comment]
#14135 and https://github.com/neovim/neovim/issues/11508#issuecomment-568712926 are fixed.

`:lua vim.lsp.buf.signature_help()` does not put "No signature help available" in hover now (nvim 3cd688ff775a50808eb7d260e540038cc32b4a40; clangd and pyls), so I try modifying

https://github.com/neovim/neovim/blob/3cd688ff775a50808eb7d260e540038cc32b4a40/runtime/lua/vim/lsp/handlers.lua#L336-L337

to
```lua
    return util.open_floating_preview({'No signature help available'}, "markdown", config)
```

But I get

![hover-signature_help](https://user-images.githubusercontent.com/11627708/120114619-f8f7cf80-c1ba-11eb-92f0-01a478f559ba.png)

**Comment by e-kwsm** [comment]
```cpp
// docstring
void f() {}

int main() {
  f(42);
}
```

1. Open the above C++ file,
2.  enable clangd (`:lua require'lspconfig'.clangd.setup{on_attach = custom_lsp_attach}`), and
3. execute `:lua vim.lsp.buf.hover()` and `:lua vim.lsp.diagnostic.show_line_diagnostics()`,

Then I get

![hover-show_line_diagnostics](https://user-images.githubusercontent.com/11627708/120116356-bfc35d80-c1c2-11eb-933a-5a28f1ae4ed3.png)

**Comment by mjlbach** [comment]
Ah yes, I see the issue is still persistent. @folke I think we can enforce a per buffer check that there is only a single lsp related hover window.

**Comment by folke** [comment]
> Ah yes, I see the issue is still persistent. @folke I think we can enforce a per buffer check that there is only a single lsp related hover window.

Yep, makes sense. I think there's an existing PR for that already. I can have a look at it
