### ISSUE TITLE
Display errors when `arabic` is set

### ISSUE THREAD

**Issue by MahmoudEmad1491999** [neovim/neovim#13597]
when I use neovim in arabic mode `:set arabic` and numbered lines is produced not in order. 
when I use arabic dialects with a characters like سً the behavior is just ً  and removes the underneath character.
![Capture](https://user-images.githubusercontent.com/76225580/103060136-d3cdb800-45af-11eb-9304-88333d719c9f.PNG)

**Comment by teto** [comment]
could you fill theissue template aka what neovim version, how does it compare to vim etc. Do you have C skills/are you willing to help solving it ?

**Comment by bfredl** [comment]
Try toggle 'arabicshape' option. If your terminal does shaping then it is typically best to turn it off in neovim.

**Comment by MahmoudEmad1491999** [comment]
@teto sorry I am not on that level this is a problem that I faced in windows and Linux  I am extremely sorry.

**Comment by MaMrEzO** [comment]
How I can disable internal arabic in compile time?

**Comment by bfredl** [comment]
@MaMrEzO you can't and don't need to. just use `set noarabic`

**Comment by MaMrEzO** [comment]
> @MaMrEzO you can't and don't need to. just use `set noarabic`

`set noarabic` has no effect !
![Screenshot_20201231_144110](https://user-images.githubusercontent.com/1070230/103408041-22fa8680-4b76-11eb-906c-5235ac1941c0.png)
*Both NeoVim and Nano are running in Konsole*

**Comment by teto** [comment]
help welcome. You can look at arabic.h and screen.c for the output, for instance  https://github.com/neovim/neovim/blob/74b343a6f23de43590ab79750848f66e2fa9a7f7/src/nvim/screen.c#L1858

**Comment by MaMrEzO** [comment]
I'd just comment out some codes and displaying is look great:
![Screenshot_20201231_165452](https://user-images.githubusercontent.com/1070230/103412089-c81e5a80-4b88-11eb-87ee-95a0c38d8257.png)

**But** display and not editing, when cursor get in line, characters get moving around. which this is the same for both NeoVim/Vim as current behavior:
![Screenshot_20201231_170749](https://user-images.githubusercontent.com/1070230/103412438-56471080-4b8a-11eb-83d3-0d7b8acd5a53.png)

May I look deeper in code for checking `noarabic` affects as expected and  handling cursor in Arabic/Persian text at same time 

In detail, for displaying Arabic/Persian text, characters must be in reverse order, just imagine each of following characters are in arabic `MUHAMAD REZA` must be changes to `AZER DAMAHUM` to display correctly, which I implemented text editing for fpGUI in FreePascal.

**Comment by bfredl** [comment]
well you have to use `set rightleft` for that (unfortunately currently only on a per-window basis, but we could hack it to be per-line at least).

**Comment by MaMrEzO** [comment]
> well you have to use `set rightleft` for that (unfortunately currently only on a per-window basis, but we could hack it to be per-line at least).

But that `set rightleft` not works as expected!

EXPECTED RESULT, look at `!` and where it is placed:
![expected result](https://user-images.githubusercontent.com/1070230/103423384-82c75080-4bbb-11eb-9998-9b85d440667d.png)

For clarification check picture of results and descriptions:
| `noarabic` | Result | Description |
|--------|--------------------|--------------------|
| Current behavior | ![Corrent - Correct](https://user-images.githubusercontent.com/1070230/103423018-9d98c580-4bb9-11eb-8dc6-fff475f3d7c3.png) | Characters order is correct, shapes are not |
| Modified version | ![Modified - Correct](https://user-images.githubusercontent.com/1070230/103423038-b99c6700-4bb9-11eb-8596-fb111104401e.png) | Characters order and shapes are OK |

Now check how characters are misplaced:
| `arabic` or `rightleft` | Result | Description |
|--------|--------------------|--------------------|
| Current behavior | ![Current - Order not Correct](https://user-images.githubusercontent.com/1070230/103423229-c7062100-4bba-11eb-8f00-35ae649a570a.png) | Characters order and shapes are wrong |
| Modified version | ![Modified - Order not Correct](https://user-images.githubusercontent.com/1070230/103423232-d2f1e300-4bba-11eb-9dc7-40e492d2f662.png)  | Characters order is wrong, so no matter how shapes look |

In my modified version of NeoVim(I just commented some parts of code), result with `noarabic` is somewhat acceptable.
In both of current version of NeoVim and mine, with `arabic` or `rightleft` result is nor correct not acceptabl!

So, these are expected for `noarabic`:
* Let terminal render text and leave shapes of characters unchanged!
 
And for `arabic` or `rightleft` mode:
* Find a way to move cursor around, which now moving cursor in line causes misplacing characters and orders...

Then we can :
>  we could hack it to be per-line at least
but with care, for example:
```golang
fmt.Println("سلام دنیا")
```
in `arabic` will be:
```golang
)                       )"ایند ملاس"(nltnirP.tmf
```
So if we hack it, it must be under control not automatic, which make it hard to edit codes....

**Comment by MahmoudEmad1491999** [comment]
Edit: new updates the problem does not exist in Debian 10.8 10.4 even in the nvim-qt

**Comment by mhinz** [comment]
Can someone confirm whether this is still an issue with a current master or nightly version?

**Comment by sekaiking** [comment]
The issue is still present in `NVIM v0.10.0-dev`. This a side by side comparation of nvim vs windows terminal (WSL)

![image](https://github.com/neovim/neovim/assets/54310457/2ef4f3f2-88a1-477a-b0ca-25f9b2c598b5)

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/pull/25934 is not really about arabic .

Is it confirmed the issue is present both _with_ `'arabicshape'` (nvim does the shaping) and with `'noarabicshape'` (nvim doesn't "interpret" the arabic text but leaves it to the terminal emulator) ?

**Comment by sekaiking** [comment]
Tried it in both https://github.com/neovim/neovim/commit/d92dd2a0c05148154c353f0e7cd2099b2427308a and https://github.com/neovim/neovim/pull/25934, nothing changes.

However, doing `:set noarabicshape` fixes the issue.

**Comment by justinmk** [comment]
> doing `:set noarabicshape` fixes the issue.

Then this issue is resolved. Open a new issue if a new problem is found.

**Comment by Humam-Hamdan** [comment]
well, i am on 0.11-dev -ubuntu ppa- and the problem is still there no matter the option, tried :set arabic/noarabic/arabicshape/noarabicshape/rightleft. nothing worked. in the terminal -guake- it shows up fine.
