### ISSUE TITLE
Problems with guisp and gui=undercurl

### ISSUE THREAD

**Issue by RRethy** [neovim/neovim#13734]
- `nvim --version`:NVIM v0.5.0-dev+1016-g0af5a56e4
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: macOS Mojave 10.14.6
- Terminal name/version: Kitty v0.19.3 (most recent)
- `$TERM`: xterm-256color

`:checkhealth`
```

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.2.6 (outdated; from /usr/local/lib/python2.7/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.2

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          /usr/local/bin/python3 does not have the "neovim" module. :help |provider-python|
          python3.10 not found in search path or not executable.
          /usr/local/bin/python3.9 does not have the "neovim" module. :help |provider-python|
          python3.8 not found in search path or not executable.
          python3.7 not found in search path or not executable.
          python3.6 not found in search path or not executable.
          /usr/local/bin/python is Python 2.7 and cannot provide Python 3.
  - INFO: Executable: Not found

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin18]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v12.16.3
  - INFO: Nvim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - WARNING: Package "neovim" is out-of-date. Installed: 4.5.0, latest: 4.9.0
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed
```

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

```vim
set termguicolors
hi Foo guifg=Red guibg=Blue guisp=Green gui=undercurl
call nvim_buf_add_highlight(1, 100, 'Foo', 0, 0, 3)
```

Results in:

![image](https://user-images.githubusercontent.com/21000943/104149414-0a734300-53a4-11eb-86bc-d69007bf3404.png)

### Expected behaviour

I expect the word `set` to have green undercurl.

My terminal supports undercurl as can be seen when I run:

```bash
echo -e '\e[4:3m\e[58:2::240:143:104mfoobarbaz\e[59m\e[4:0m\n' 
```

I get the following:

![image](https://user-images.githubusercontent.com/21000943/104149488-52926580-53a4-11eb-9741-d8c8ae4fe01c.png)

**Comment by akinsho** [comment]
@RRethy I use `guisp` and undercurl extensively in my config and both work.

![image](https://user-images.githubusercontent.com/22454918/104247644-17556c80-5460-11eb-887c-b9b78eca1a7a.png)

![image](https://user-images.githubusercontent.com/22454918/104247846-69968d80-5460-11eb-9ecd-302997c485ac.png)

Not sure if this might have anything to do with the `nvim_buf_add_highlight` call rather than the highlighting

**Comment by RRethy** [comment]
All the following is with `nvim --clean`. I tried with

```vim
set termguicolors
hi Foo guifg=Red guibg=Blue guisp=Green gui=undercurl
call matchaddpos('Foo', [2])
call nvim_buf_add_highlight(1, 100, 'Foo', 0, 0, 3)
syn keyword Bar matchaddpos
hi link Bar Foo
```

and it still doesn't show undercurl. Also tried changing SpellBad in my colorscheme to match what you have and it still doesn't work for me.

Even simply doing 

```lua
hi Foo guifg=Red guibg=Blue guisp=Green gui=undercurl
```

Then viewing it with `:hi Foo` doesn't work.

![image](https://user-images.githubusercontent.com/21000943/104258693-13b8ea00-544e-11eb-81fe-c8b86e9739d8.png)

Gonna try a bisect on Neovim and maybe asking if kitty maintainer has any ideas.

**Comment by RRethy** [comment]
Solved by kovidgoyal in https://github.com/kovidgoyal/kitty/issues/3235, I had `export TERM="xterm-256color"`, changing it to `export TERM="xterm-kitty"` fixed the problem and undercurls now show.

**Comment by luisdavim** [comment]
shouldn't it still work with `TERM="xterm-256color"`? It does with `vim` but not `neovim`

**Comment by bfolkens** [comment]
Something is still broken with this.  I can get it to work by changing to TERM="tmux-256color" but TERM="xterm-256color" doesn't work.  Have also verified it's neovim and not a terminal (iTerm2) issue via the `echo` command above.
