### ISSUE TITLE
Apple Silicon Arm build problems

### ISSUE THREAD

**Issue by reportaman** [neovim/neovim#13847]
**Homebrew installation problem**
On Apple Silicon (ARM) Mac, I first used home-brew to download dependencies mentioned on macOS-specific brew installation, and then installed the latest (HEAD) version. This opens fine, but upon loading I got error from vim packages like *YouCompleteMe* that python is not found. That indeed seems to be the case: both `:echo has("python3")` & `:echo has("python")` return 0. Please update the brew config to enable python3 for nvim, or provide a way to do so.

Note: As a side note, Homebrew's `--build-from-source` builds neovim fine, but again it doesn't python enabled. Is there a way to pass it as an option?

**Build from source problem**
I cloned the latest master branch from github, and ran `make` from neovim directory. Ninja compile fails with a non-helpful error message:
```
[20/89] Performing configure step for 'libvterm'
FAILED: build/src/libvterm-stamp/libvterm-configure 
cd /Users/reportaman/Downloads/neovim/.deps/build/src/libvterm && "" "" && /usr/local/bin/cmake -E touch /Users/reportaman/Downloads/neovim/.deps/build/src/libvterm-stamp/libvterm-configure
/bin/sh: : command not found
[22/89] Performing download step for 'luajit'
```

**Prebuilt binaries problem**
The prebuilt binary provided for macOS is only for x86 architecture. Please add directory for ARM builds. It also fails saying "nvim” cannot be opened because the developer cannot be verified." If I allow that, it then fails on individual libs of neovim in lib folder.

**Comment by fsouza** [comment]
As far as I understand homebrew is using a fork of luajit that's compatible with darwin arm64. Keep in mind that neovim is not like vim though, enabling python is not something you do during compile time. You do it on the runtime, via providers, see `:h provider-python` or https://neovim.io/doc/user/if_pyth.html#Python

**Comment by reportaman** [comment]
@fsouza Thanks 👍, I confirm that this solves **Homebrew installation problem** in the sense that I don't get "python not found" errors anymore. Let's see what the solutions are for the rest of the problems. Also can you point me to the darwin arm64 luajit repo?

**Comment by fsouza** [comment]
Actually, nevermind, homebrew uses the default luajit for neovim (there are some other formulae using the fork, but neovim is not one of them. See some info here: https://github.com/Homebrew/homebrew-core/pull/68787).

Regarding the compilation error you posted, I think some variables are getting expanded to empty strings. Perhaps a maintainer can chime in to help, but posting which command you ran and the entire output will also help.

**Comment by clason** [comment]
> Actually, nevermind, homebrew uses the default luajit for neovim (there are some other formulae using the fork, but neovim is not one of them. See some info here: [Homebrew/homebrew-core#68787](https://github.com/Homebrew/homebrew-core/pull/68787)).

Actually, that might change soon: https://github.com/Homebrew/homebrew-core/pull/70053

Also note that homebrew is a separate project which modify neovim's (cross-platform) build scripts, so any build issues with `brew` should be reported there. (Of course, we want to support them, and if the problem turns out to be in neovim's scripts, we have to fix them. But from all reports so far, a manual `make` in the cloned repo works well on on Apple ARM.)

**Comment by reportaman** [comment]
@clason Thanks for the explanation, below are the relevant details you ask. Let me know if you need more info.
```
* cmake: (It's in my /usr/local/bin/ dir which means I built it from source, has not given me problem with other builds...)
cmake version 3.19.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).

* macOS:
 OS: macOS 11.1 20C69 arm64
Host: Macmini9,1
Kernel: 20.2.0
Shell: zsh 5.8
```
 
Ok thanks for letting me know, I will file separate tickets. Is it recommended to file one parent ticket that links to other child tickets?

**Comment by clason** [comment]
> * cmake: (It's in my /usr/local/bin/ dir which means I built it from source, has not given me problem with other builds...)
> cmake version 3.19.3
> CMake suite maintained and supported by Kitware (kitware.com/cmake).

Hmm, that version should be new enough. Just to make sure, could you test with homebrew's cmake? 

> Ok thanks for letting me know, I will file separate tickets. Is it recommended to file one parent ticket that links to other child tickets?

No need, since these are orthogonal issues. Do search for similar issues first, though, since these might be duplicates. For example, the CMake problem is possibly https://github.com/neovim/neovim/issues/12675 and signing the binary is https://github.com/neovim/neovim/issues/11011.

**Comment by reportaman** [comment]
@clason Here we go, with homebrew's cmake (version 3.19.4)

```
[14/89] Performing configure step for 'libvterm'
FAILED: build/src/libvterm-stamp/libvterm-configure 
cd /Users/reportaman/Downloads/neovim/.deps/build/src/libvterm && "" "" && /opt/homebrew/Cellar/cmake/3.19.4/bin/cmake -E touch /Users/reportaman/Downloads/neovim/.deps/build/src/libvterm-stamp/libvterm-configure
/bin/sh: : command not found
[16/89] Performing download step for 'unibilium'

```

**Comment by clason** [comment]
That's weird. This is _exactly_ #12675, which is fixed in #12676. Can you make sure that that patch is applied for your build? Do you see other empty commands in the CMake file?

**Comment by reportaman** [comment]
That string still existed in the Build* file, I uncommented it * did `make clean && make`. Compile moves past that point, though it now fails on luajit "gcc" error. 

<img width="1265" alt="Screen Shot 2021-01-30 at 4 15 29 AM" src="https://user-images.githubusercontent.com/71736629/106356346-cf35a700-62b3-11eb-8f20-2e198021a70a.png">


```
[35/89] Performing install step for 'luajit'
FAILED: build/src/luajit-stamp/luajit-install 
cd /Users/amanmehra/Downloads/neovim/.deps/build/src/luajit && /opt/homebrew/bin/gmake CFLAGS=-fPIC CFLAGS+=-DLUA_USE_APICHECK CFLAGS+=-DLUA_USE_ASSERT CCDEBUG+=-g Q= install "CC=/Library/Developer/CommandLineTools/usr/bin/cc -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk" PREFIX=/Users/amanmehra/Downloads/neovim/.deps/usr MACOSX_DEPLOYMENT_TARGET= && /usr/local/bin/cmake -E touch /Users/amanmehra/Downloads/neovim/.deps/build/src/luajit-stamp/luajit-install
gmake[1]: Entering directory '/Users/amanmehra/Downloads/neovim/.deps/build/src/luajit'
==== Building LuaJIT 2.0.5 ====
/opt/homebrew/bin/gmake -C src
gmake[2]: Entering directory '/Users/amanmehra/Downloads/neovim/.deps/build/src/luajit/src'
lj_arch.h:55:2: error: "No support for this architecture (yet)"
#error "No support for this architecture (yet)"
 ^
lj_arch.h:294:2: error: "No target architecture defined"
#error "No target architecture defined"
 ^
lj_arch.h:317:2: error: "Need at least GCC 4.3 or newer"
#error "Need at least GCC 4.3 or newer"
 ^
3 errors generated.
lj_arch.h:55:2: error: "No support for this architecture (yet)"
#error "No support for this architecture (yet)"
 ^

```

**Comment by clason** [comment]
I'm sorry, something seems to be seriously wrong with your build setup. Can you make sure that you installed all build dependencies according to https://github.com/neovim/neovim/wiki/Building-Neovim#macos (`ninja` is also highly recommended, please install that as well).

**Comment by reportaman** [comment]
Ok it worked, thanks! My bad, I had checked out "stable" branch after cloning the repo... It worked!!!
