### ISSUE TITLE
Wrong highlighting after autoread with treesitter highlight enabled

### ISSUE THREAD

**Issue by doubleloop** [neovim/neovim#13937]
After https://github.com/neovim/neovim/pull/13935, there is still small issue with highlighting:

testrc.vim
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()
lua require('nvim-treesitter.configs').setup{highlight={enable = true}}
hi illuminatedWord cterm=underline gui=underline
let m = matchadd('illuminatedWord', 'print')
```

```sh
$ echo "print('boo')" > test.py && vim -u testrc.vim test.py
```
inside vim:
```
:set autoread
:!echo "print('boo')" > %
```

### Expected behaviour
after overwriting file, `print` should have the same color as before

### Actual behaviour
It does not
![vim2](https://user-images.githubusercontent.com/2602750/107887144-3edaa180-6f04-11eb-9061-6cd81abd4a22.gif)

tested nvim master (dc3ca16a99ec05c88df1b1fe6a3cfbe97ea34227)

**Comment by vigoux** [comment]
Hi, sorry for the delay.

I can't reproduce this issue anymore, and it should have been fixed now.

Could you confirm it is the case, and if yes, close the issue ?

**Comment by doubleloop** [comment]
Just pulled current master (68d40388f356587726ea7db83f87846dfaecf9d9) and updated treesitter config plugin, the issue still occurs.

**Comment by vigoux** [comment]
Okay, I can reproduce it in the end, working on it right now.

**Comment by Cnly** [comment]
A workaround now seems to be reloading the file again (e.g. with `:e`). Any updates on this?

**Comment by vigoux** [comment]
Do you ever encounter this issue these days?
If yes please provide detailed reproduction information!

**Comment by justinmk** [comment]
cannot reproduce. `v0.9.0-dev-1027+g` 09b6a68c3700

**Comment by doubleloop** [comment]
sry for late response, can not reproduce either on current master
