### ISSUE TITLE
TUI: handle ModifyOtherKeys key sequences 

### ISSUE THREAD

**Issue by jerome-pouiller** [neovim/neovim#14350]
### Environment

- `nvim --version`: v0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: Debian Bullseye
- Terminal name/version: xterm
- `$TERM`: xterm

### Steps to reproduce

 - Modify your  `~/.Xresources` to include `xterm*modifyOtherKeys: 2`. This step is not mandatory, but it may make the further behavior easier to understand. Don't forget to merge your resource with `xrdb -merge ~/.Xresources`.
 - Launch `nvim -u NORC` with xterm.
 - Enter command mode with `:`.
 - Hit `C-k` twice (I have never understood why `C-k` should be typed twice, but I think it is not related to the problem).
 - Hit a key sequence with `Ctrl` and `Shift` like `C-S-g`.
 - It shows `^G` while `<C-S-g>` is expected.

If you do the same with `vim`, it displays `<C-S-g>` as expected.

Neovim correctly support ModifyOtherKeys. If it was not the case, it would be impossible to enter any control sequences or shited letters (compare with the behavior of a program that does not support ModifyOtherKeys like `nano`). However, a part of the escape sequence is dropped somewhere and neovim does not make the difference between `<C-g>` and `<C-S-g>`.

Note I think this issue is not related to #6279. Indeed, in my setup `xterm` send `^]]` and not `\x9b`.

**Comment by glacambre** [comment]
Could you try [nightly](https://github.com/neovim/neovim/releases/tag/nightly)? I think this bug might have been fixed already.

**Comment by jerome-pouiller** [comment]
Indeed, it is fixed with v0.5.0-dev+1233-g82ac44d01

**Comment by jerome-pouiller** [comment]
In fact, it seems there another problem with nightly build. Indeed, it runs fine with `xterm*modifyOtherKeys: 2` (which is a bit unsane). However, it still does not work with the default xterm configuration. I think that neovim does not send the string "\<Esc>[>4;2m" that enable modifyOtherKeys[1]. In vim, this string is sent by `t_TI` and `t_TE`[2]. Indeed, I do not see these equivalents in neovim.

[1]: as explain here https://github.com/alacritty/alacritty/issues/3101
[2]: see `:h modifyOtherKeys` in vim

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/nitty-gritty-questions-on-terminal-nvim-and-keyboard-events/1624/1

**Comment by justinmk** [comment]
fixed by #17771
