### ISSUE TITLE
vim.lsp.buf_get_clients() is unreliable when working with multiple projects

### ISSUE THREAD

**Issue by ahmedkhalf** [neovim/neovim#14618]
- `nvim --version`: NVIM v0.5.0-dev+1345-g6dd04ed5f
- Operating system/version: manjaro
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

### Steps to reproduce

1. Open neovim to any lsp project (in my case python)
2. Then list lsp clients connected to buffer using `vim.lsp.buf_get_clients()`
3. We can see that the listed clients table has length 1 and contains client python
4. Now, open another buffer in another project (in my case golang)
5. Then list lsp clients connected to buffer using `vim.lsp.buf_get_clients()`
6. We can see that the listed clients table has length 0 and does not contain any client.

### Expected behaviour

On step number 6, I expect the listed clients table to have a length of one and contain lsp client golang.

### Workaround

Right now I can use this piece of code instead of `vim.lsp.buf_get_clients()`, however this piece of code has the disadvantage that it won't be able to differentiate between different projects/lsp clients that target the same filetype.

```lua
local get_lsp_client = function()
  -- Get lsp client for current buffer
  local buf_ft = vim.api.nvim_buf_get_option(0, 'filetype')
  local clients = vim.lsp.get_active_clients()
  if next(clients) == nil then
    return nil
  end

  for _, client in ipairs(clients) do
    local filetypes = client.config.filetypes
    if filetypes and vim.fn.index(filetypes,buf_ft) ~= -1 then
      return client
    end
  end

  return nil
end
```

**Comment by mjlbach** [comment]
I'm not able to reproduce this, it works fine for me.


https://user-images.githubusercontent.com/13316262/119245785-a79f6e80-bb30-11eb-90e7-64d8f465f1ff.mp4

**Comment by lcrockett** [comment]
Can confirm this report. See additional information here below:

# Environment
- NVIM v0.5.0-dev+1349-g0cbe748da
- Build type: Release
- LuaJIT 2.1.0-beta3
- Operating system/version: MacOS Big Sur (x86_64)
- Terminal name/version: iTerm2
- $TERM: xterm-256color

# Steps to reproduce
- Open neovim with 3 different lua files, all from different underlying directories
- Buffer #1 -> 1 active client + 1 client attached to buffer (great, let's move on)
- Move to buffer #2 -> 2 active clients + 2 clients attached to buffer (how come both clients are attached to this buffer ?)
- Move to buffer #3 -> 3 active clients + 0 clients attached to buffer (it did start a 3rd client but none are attached to this buffer)

# Expected behaviour
I would expect each buffer to spawn a separate client (all these files are not under a shared git root) and have them attach to their corresponding buffer.

# Video

https://user-images.githubusercontent.com/58056722/119246102-fbd13f80-bb7e-11eb-85fb-6025d35570ed.mp4

# Notes
Let me know if you need additional information that might be required. Cheers !

**Comment by mjlbach** [comment]
Ah, I see the issue. This is an implementation detail about `#` in lua 5.1 semantics.

Try the following in a lua repl (or as neovim commands).
```
:lua y = { [1]="test" }
:lua print(#y) -- Should be 1
:lua x = { [3]="test" }
:lua print(#x) -- Should be 0
```

See here for an explanation:
https://stackoverflow.com/questions/9613322/lua-table-getn-returns-0

If you want to get the number of clients, you can use the follow snippet:
```
local count = 0
for k,v in pairs(vim.lsp.buf_get_clients()) do count = count + 1 end
```

**Comment by lcrockett** [comment]
Cheers for the direct pointer @mjlbach, your snippet works well. The `vim.inspect` does not, the integer value returned by it matches what `:LspInfo` returns and is therefore incorrect.

Looking at `https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/lspinfo.lua#L7-L26` it seems `:LspInfo` uses the incorrect method of counting the number of clients attached to the buffer. You reckon that's indeed true ? If so, I can open an issue at `neovim/nvim-lspconfig`, additionally referring back to this issue.

**Comment by mjlbach** [comment]
Whoops! The `#` was an oversight, I meant to direct you to the raw output which shows the table keys.

> Looking at https://github.com/neovim/nvim-lspconfig/blob/e883e23305fdef61b8f71b680cead17b26c73e4e/lua/lspconfig/lspinfo.lua#L7-L26 it seems :LspInfo uses the incorrect method of counting the number of clients attached to the buffer.

Yes, that is probably my fault given I implemented the original version. I think `#vim.tbl_keys(vim.lsp.buf_get_clients())` should also work (and is probably a nicer one liner for a PR to lspconfig)

**Comment by ahmedkhalf** [comment]
@mjlbach 
Hum weird, I was like 100% sure something's not right. Unfortunately I'm not hone right now, but I think *my* issue still persists, and is completely unrelated to what @lcrockett is talking about...
I mean there most be a reason why @glepnir switched from using `buf_get_clients` to using `get_active_clients`...
https://github.com/glepnir/galaxyline.nvim/commit/168fe13d5d825a084366f866cc611ae9a128e0f5

**Comment by mjlbach** [comment]
I have no idea, I can confirm that the behavior you are seeing in the issue:
```
6. We can see that the listed clients table has length 0 and does not contain any client.
```
 is 100% expected if you use `#` to get the list of a table with missing entries.

The code for  `buf_get_clients` is almost as simple as it can be, you can check the implementation yourself, but I am almost certain there is no bug...

**Comment by ahmedkhalf** [comment]
PROBLEM FIXED, changed code from:
```lua
local get_lsp_client = function()
  -- Get lsp client for current buffer
  local buf_ft = vim.api.nvim_buf_get_option(0, 'filetype')
  local clients = vim.lsp.get_active_clients()
  if next(clients) == nil then
    return nil
  end

  for _, client in ipairs(clients) do
    local filetypes = client.config.filetypes
    if filetypes and vim.fn.index(filetypes,buf_ft) ~= -1 then
      return client
    end
  end

  return nil
end
```
to
```lua
local get_lsp_client = function()
  -- Get lsp client for current buffer
  local buf_ft = vim.api.nvim_buf_get_option(0, 'filetype')
  local clients = vim.lsp.buf_get_clients()
  if next(clients) == nil then
    return nil
  end

  for _, client in pairs(clients) do
    local filetypes = client.config.filetypes
    if filetypes and vim.fn.index(filetypes,buf_ft) ~= -1 then
      return client
    end
  end

  return nil
end
```
Apparently, ipairs doesn't work for looping so I have to use pairs... Anyways I'm really glad this isn't a problem with neovim since I was going insane....
