### ISSUE TITLE
`vim.lsp.buf.formatting` resets position of same buffer on different window

### ISSUE THREAD

**Issue by alexisquintero** [neovim/neovim#14645]
### Actual behaviour

Calling `vim.lsp.buf.formatting` on a buffer opened on different windows, regardless if it's on the same or different tab, causes the non focused window(s) to reset its position to the top of the file. 

### Expected behaviour

Avoid changing the position of the non focused windows.

**Comment by folke** [comment]
I'm not sure we can fix this, this is due to `nvim_buf_set_lines` replacing the lines. When the cursor was in the replacement region, it will be set to the top of the replaced region. In case all lines change in a buffer, it will be set to the top of the buffer

**Comment by folke** [comment]
What we can do, is save the cursor position before `set_lines` and then try restoring it afterwards?

**Comment by craftzdog** [comment]
Hi @folke, could you show me an example config to do that? Mine is:

```lua
if client.resolved_capabilities.document_formatting then
  vim.api.nvim_command [[augroup Format]]
  vim.api.nvim_command [[autocmd! * <buffer>]]
  vim.api.nvim_command [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync(nil, 1000)]]
  vim.api.nvim_command [[augroup END]]
end
```

**Comment by folke** [comment]
@craftzdog to do what? :)

You mean what I was referring to as a possible fix? That would be using the api to save the cursor position, calling format and resetting it. So you would need to write that code to use it.

Either way, I think this problem may be fixed by #13703

**Comment by craftzdog** [comment]
Thanks! I hope it'll be merged soon.

**Comment by YorickPeterse** [comment]
As a temporary workaround, you should be able to use this:

```lua
local api = vim.api
local fn = vim.fn
local lsp = vim.lsp
local format_mark_ns = api.nvim_create_namespace('')

function format_buffer()
  local bufnr = api.nvim_win_get_buf(0)
  local windows = fn.win_findbuf(bufnr)
  local marks = {}

  -- Until https://github.com/neovim/neovim/issues/14645 is solved, I use this
  -- code to ensure the cursor position is properly restored after formatting a
  -- buffer. The approach used supports restoring cursors for different windows
  -- using the same buffer.
  for _, window in ipairs(windows) do
    local line, col = unpack(api.nvim_win_get_cursor(window))

    marks[window] =
      api.nvim_buf_set_extmark(bufnr, format_mark_ns, line - 1, col, {})
  end

  lsp.buf.formatting_sync(nil, 1000)

  for _, window in ipairs(windows) do
    local mark = marks[window]

    local line, col =
      unpack(api.nvim_buf_get_extmark_by_id(bufnr, format_mark_ns, mark, {}))

    if line and col then
      api.nvim_win_set_cursor(window, { line + 1, col })
    end
  end

  api.nvim_buf_clear_namespace(bufnr, format_mark_ns, 0, -1)
end
```

You then have to run this function in the appropriate `autocmd`. For example:

```vim
BufWritePre *.rs lua format_buffer()
```

This should then ensure your cursors are restored properly after formatting. It also supports multiple windows showing the same buffer, and will restore each independently.

Mind you that I only started testing this last night, so there may be bugs.

**Comment by craftzdog** [comment]
Thanks, @YorickPeterse! I've tried it but got the following error:

```
Error detected while processing BufWritePre Autocommands for "<buffer=1>":
E5108: Error executing lua [string ":lua"]:30: Cursor position outside buffer
```

For some reason, `line` is always the last line when retrieved from:

```lua
local line, col =
      unpack(api.nvim_buf_get_extmark_by_id(bufnr, format_mark_ns, mark, {}))
```

**Comment by YorickPeterse** [comment]
@craftzdog I haven't run into that error so far, so I'm not sure what would cause it. If you have an easy way to reproduce the issue (preferably something that doesn't require installing a ton of dependencies) that would help :smiley:

**Comment by YorickPeterse** [comment]
@craftzdog I finally ran into the error. Using the following should fix it:

```lua
local bufnr = api.nvim_win_get_buf(0)
local windows = fn.win_findbuf(bufnr)
local marks = {}
                                                                              
-- Until https://github.com/neovim/neovim/issues/14645 is solved, I use this
-- code to ensure the cursor position is properly restored after formatting a
-- buffer. The approach used supports restoring cursors for different windows
-- using the same buffer.
for _, window in ipairs(windows) do
  local line, col = unpack(api.nvim_win_get_cursor(window))
                                                                              
  marks[window] =
    api.nvim_buf_set_extmark(bufnr, format_mark_ns, line - 1, col, {})
end
                                                                              
lsp.buf.formatting_sync(nil, 1000)
                                                                              
for _, window in ipairs(windows) do
  local mark = marks[window]
                                                                              
  local line, col =
    unpack(api.nvim_buf_get_extmark_by_id(bufnr, format_mark_ns, mark, {}))
                                                                              
  local max_line_index = api.nvim_buf_line_count(bufnr) - 1
                                                                              
  if line and col and line <= max_line_index then
    api.nvim_win_set_cursor(window, { line + 1, col })
  end
end
                                                                              
api.nvim_buf_clear_namespace(bufnr, format_mark_ns, 0, -1)
```

The change here is this:

```diff
@@ -86,7 +86,9 @@ function M.format_buffer()
     local line, col =
       unpack(api.nvim_buf_get_extmark_by_id(bufnr, format_mark_ns, mark, {}))
 
-    if line and col then
+    local max_line_index = api.nvim_buf_line_count(bufnr) - 1
+
+    if line and col and line <= max_line_index then
       api.nvim_win_set_cursor(window, { line + 1, col })
     end
   end
```

**Comment by craftzdog** [comment]
Thanks for the update.
I still don't know why but, `lsp.buf.formatting_sync(nil, 1000)` affects the return value of `api.nvim_buf_get_extmark_by_id`.
Why not simply store the cursor positions in tables like so?

```lua
local pos = {}
...
pos[window] =  { line - 1, col }
```

**Comment by YorickPeterse** [comment]
@craftzdog Your approach isn't going to work if the line you had your cursor on is now an entirely different line. Consider this for example:

```
1: foo
2: bar
3: baz|
4: quix
```

Here `|` is the cursor. Now let's say we format the code and it ends up like this:

```
1: foo bar baz quix
```

Simply restoring according to the line number would not work, as there is no line 3. Even if there was (e.g. they are empty), you'd end up with this:

```
1: foo bar baz quix
2:
3: |
4: 
```

But that's not what you want: you want the cursor to be as close as possible to the _code_ that you had it pointed to. So this:

```
1: foo bar baz| quix
```

Using extmarks this can be achieved (most of the time at least). Either way this is getting a bit offtopic. If the script doesn't work feel free to adjust it according to your needs; it's just a temporary hack that's better than nothing :smiley:

**Comment by craftzdog** [comment]
Thank you for the explanation, that makes sense!
Now, I need to know why `lsp.buf.formatting_sync(nil, 1000)` breaks the extmarks.

**Comment by craftzdog** [comment]
Confirmed that the latest build fixed the issue 🎉

**Comment by YorickPeterse** [comment]
@craftzdog Just to check: do you mean the latest `master` fixes the issue described by OP, or that it fixes my extmarks hack?

**Comment by craftzdog** [comment]
Sorry, I was wrong. I tried the latest `master`. The cursor position still moves up to the beginning on formatting. I was editing a file that is not formatted on save.

By the way, how do you format your code?
I use `lspconfig` with `diagnosticls` and `prettier` like so:

```lua
local on_attach = function(client, bufnr)
  if client.resolved_capabilities.document_formatting then
    vim.api.nvim_command [[augroup Format]]
    vim.api.nvim_command [[autocmd! * <buffer>]]
    vim.api.nvim_command [[autocmd BufWritePre <buffer> lua format_buffer()]]
    vim.api.nvim_command [[augroup END]]
  end
end

nvim_lsp.diagnosticls.setup {
  on_attach = on_attach,
  filetypes = { 'javascript', 'javascriptreact', 'json' },
  init_options = {
    formatters = {
      prettier = {
        command = 'prettier_d_slim',
        rootPatterns = { '.git' },
        -- requiredFiles: { 'prettier.config.js' },
        args = { '--stdin', '--stdin-filepath', '%filename' }
      }
    },
    formatFiletypes = {
      javascript = 'prettier',
      javascriptreact = 'prettier',
      json = 'prettier',
    }
  }
}
```

**Comment by YorickPeterse** [comment]
@craftzdog Ah. I use the following for formatting:

- https://gitlab.com/yorickpeterse/dotfiles/-/blob/9834832f56c333f56b8bee7d81dea3bd445cf5c2/dotfiles/.config/nvim/lua/dotfiles/hooks.lua#L92
- https://gitlab.com/yorickpeterse/dotfiles/-/blob/9834832f56c333f56b8bee7d81dea3bd445cf5c2/dotfiles/.config/nvim/lua/dotfiles/hooks.lua#L28

**Comment by YorickPeterse** [comment]
From Matrix per @mjlbach:

```
If you're interesting in debugging this (which would be great)

    check the fix_cursor function is not the culprit,
    check the ranges touched by the formatter
    check the position pre and post of the extmark
```

I'll see if I can do some further debugging this week.

**Comment by craftzdog** [comment]
Thanks, I'll find time to debug this.

**Comment by hrsh7th** [comment]
Related
https://github.com/neovim/neovim/pull/16038
https://github.com/neovim/neovim/pull/15561

**Comment by mjlbach** [comment]
This doesn't seem to be the case when I open main.c, split the window, and call format on the original window. I need a more clear reproduction case (not null-ls, EFM, or any of these adapter servers)

**Comment by YorickPeterse** [comment]
@mjlbach You should be able to reproduce it using the following Rust file:

```rust
fn main() {
    println!(
        "{}", 
        42
    );
}
```

Open this file in two vertical splits. In the right split, move the cursor to `4`. In the left split, move the cursor to the `p` in `println!`. Then format the file. If you move the cursor back to the right split, it's moved to the start of the file; instead of being located at `4`. With my extmarks hack it sort of works but not always (e.g. in this case the cursor ends up at `)` and not `4`, but most of the time it's where I would expect it).

**Comment by mjlbach** [comment]
I don't think fix_cursor is the issue, I'm not exactly sure where in the vim codebase the cursor is adjusted when switching back to another window. fix_cursor was only triggered on the primary window and correctly adjusts the cursor position.

**Comment by craftzdog** [comment]
Found that formatting with `nvim_lsp.diagnosticls` breaks the extmarks.
Using `prettier.nvim` and `null-ls.nvim` instead of `nvim_lsp.diagnosticls` solved the issue.
My configuration looks like so:

```lua
local null_ls = require('null-ls')

null_ls.setup({
  on_attach = function(client, bufnr)
    if client.server_capabilities.documentFormattingProvider then
      vim.api.nvim_command [[augroup Format]]
      vim.api.nvim_command [[autocmd! * <buffer>]]
      vim.api.nvim_command [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_seq_sync()]]
      vim.api.nvim_command [[augroup END]]
    end
  end
})

local prettier = require('prettier')

prettier.setup {
  bin = 'prettier',
  filetypes = {
    "css",
    "javascript",
    "javascriptreact",
    "json",
    "scss",
    "less"
  }
}
```

Thanks!

**Comment by danielo515** [comment]
So, this is kind of (kind of) old problem. Has it been fixed by any of the latest releases? I'm on NVIM v0.8.2 and this bug is still there

**Comment by Pezhvak** [comment]
This is still an issue, and it seems `vim.lsp.buf.formatting_seq_sync()` is deprecated.

**Comment by alexisquintero** [comment]
Seems to be fixed on v0.10.0 🎉
