### ISSUE TITLE
Cannot unset option 'showmode' in init.lua

### ISSUE THREAD

**Issue by samodostal** [neovim/neovim#15468]
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 11.5

### Terminal name/version

Alacritty

### $TERM environment variable

xterm-256color

### Installation

home-brew

### How to reproduce the issue

When I try to set: `vim.o.showmode = false`, I get following error:

> E5113: Error while calling lua chunk: ...Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/_meta.lua:170: Cannot unset option 'showmode'

The same thing happens to: `splitright` and `splitbelow`.
It is working when I set it the vim script way: `set noshowmode`. When I print current value: `:lua print(vim.o.showmode)`, it prints `true`.

### Expected behavior

vim.o.showmode works

### Actual behavior

vim.o.showmode throws error

**Comment by justinmk** [comment]
works with 0.6.0  db1b0ee3b30f

```
$ nvim -u NONE --cmd 'lua vim.o.showmode=false'
$ nvim -u NONE --c 'lua vim.o.showmode=false'
:set showmode?
noshowmode         
        Last set from Lua
```

assuming this was fixed on master.

**Comment by gpanders** [comment]
I can't reproduce this on 0.5.0.

**Comment by samodostal** [comment]
I upgraded to the latest nightly version: NVIM v0.6.0-dev+181-g5d633546b
and I still get the same error. Do you have any idea what could cause it? Maybe some plugin?

**Comment by bfredl** [comment]
@samodostal The problem is not lua but the context in which the code is called (could be an autocmd, a modeline, or something). `:lua vim.o.showmode = false` works interactively. please post a full minimal repro, i e `init.lua` file or something that reproduces the error.
