### ISSUE TITLE
Neovim 0.5.0 segfaults on chansend to terminal buffer opened with nvim_open_term

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#16040]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

On both macOS 11.5.1 and CentOS 7.9

### Terminal name/version

On both iterm2 3.4.10 and xfce4-terminal 0.8.7.4

### $TERM environment variable

tmux-256color and xterm-256color (repros outside tmux)

### Installation

system package manager

### How to reproduce the issue

Save the following as `/tmp/crash.vim`:

```
let chan = nvim_open_term(0, {})
let lines = repeat([repeat('x',187)."\r"], 12250)
call chansend(chan, lines)
```

Then use `nvim --clean -S /tmp/crash.vim`.

### Expected behavior

terminal buffer opens with lines of x's

### Actual behavior

segfault

**Comment by seandewar** [comment]
Reproducible on master. ASAN backtrace:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==16821==ERROR: AddressSanitizer: stack-overflow on address 0x7fff6a7a7388 (pc 0x000001f1b7f2 bp 0x7fff6b07c3e0 sp 0x7fff6a7a7390 T0)
    #0 0x1f1b7f2 in on_text /home/sean/projects/3rdparty/neovim/.deps/build/src/libvterm/src/state.c:255:3
    #1 0x1f1857c in vterm_input_write /home/sean/projects/3rdparty/neovim/.deps/build/src/libvterm/src/parser.c:314:19
    #2 0x1b35351 in terminal_receive /home/sean/projects/3rdparty/neovim/build/../src/nvim/terminal.c:674:3
    #3 0x8058f9 in channel_send /home/sean/projects/3rdparty/neovim/build/../src/nvim/channel.c:534:5
    #4 0xb3353c in f_chansend /home/sean/projects/3rdparty/neovim/build/../src/nvim/eval/funcs.c:999:26
    #5 0xa8d431 in call_internal_func /home/sean/projects/3rdparty/neovim/build/../src/nvim/eval/funcs.c:196:3
    #6 0xbc4870 in call_func /home/sean/projects/3rdparty/neovim/build/../src/nvim/eval/userfunc.c:1592:15
    #7 0xbc00ae in get_func_tv /home/sean/projects/3rdparty/neovim/build/../src/nvim/eval/userfunc.c:459:11
    #8 0xbf9683 in ex_call /home/sean/projects/3rdparty/neovim/build/../src/nvim/eval/userfunc.c:3006:9
    #9 0xcfa1cc in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1983:5
    #10 0xce2973 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:604:20
    #11 0xccabfe in do_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2237:5
    #12 0xcc55c8 in cmd_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:1800:14
    #13 0xcc5ce5 in ex_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:1781:3
    #14 0xcfa1cc in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1983:5
    #15 0xce2973 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:604:20
    #16 0xce8943 in do_cmdline_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:288:10
    #17 0x107c44b in exe_commands /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:1655:5
    #18 0x106a0ff in main /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:493:5
    #19 0x7f0578d210b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #20 0x45dedd in _start (/home/sean/projects/3rdparty/neovim/build/bin/nvim+0x45dedd)

SUMMARY: AddressSanitizer: stack-overflow /home/sean/projects/3rdparty/neovim/.deps/build/src/libvterm/src/state.c:255:3 in on_text
==16821==ABORTING
```

**Comment by justinmk** [comment]
Might be a libvterm bug @leonerd. We may need to update libvterm too.

**Comment by erw7** [comment]
The reason for this is the use of VLA as shown below.

```C
static int on_text(const char bytes[], size_t len, void *user)
{
  VTermState *state = user;

  VTermPos oldpos = state->pos;

  // We'll have at most len codepoints
  uint32_t codepoints[len];
```

To solve this problem, modify it to allocate `codepoints` on the heap as follows.

```diff
diff --git a/src/state.c b/src/state.c
index ee815f4..69ef4e9 100644
--- a/src/state.c
+++ b/src/state.c
@@ -272,7 +272,7 @@ static int on_text(const char bytes[], size_t len, void *user)
   VTermPos oldpos = state->pos;
 
   // We'll have at most len codepoints
-  uint32_t codepoints[len];
+  uint32_t *codepoints = malloc(len * sizeof(*codepoints));
   int npoints = 0;
   size_t eaten = 0;
 
@@ -289,8 +289,10 @@ static int on_text(const char bytes[], size_t len, void *user)
   /* There's a chance an encoding (e.g. UTF-8) hasn't found enough bytes yet
    * for even a single codepoint
    */
-  if(!npoints)
+  if(!npoints) {
+    free(codepoints);
     return eaten;
+  }
 
   if(state->gsingle_set && npoints)
     state->gsingle_set = 0;
@@ -433,6 +435,7 @@ static int on_text(const char bytes[], size_t len, void *user)
   }
 #endif
 
+  free(codepoints);
   return eaten;
 }

```

**Comment by leonerd** [comment]
Not a good idea. libvterm isn't supposed to heap-allocate anything during runtime. It must remain on the stack.

**Comment by leonerd** [comment]
(or perhaps within a buffer that's allocated once at object-creation time, if it really can't fit there)

**Comment by erw7** [comment]
>Not a good idea. libvterm isn't supposed to heap-allocate anything during runtime. It must remain on the stack.

>(or perhaps within a buffer that's allocated once at object-creation time, if it really can't fit there)

A library that causes stack overflow is useless. I think this is a problem that should be fixed on the `libvterm` side, so please fix it on the `libvterm` side in any way you can.

**Comment by leonerd** [comment]
I'd suggest fixing it by the following:

* Pick a number. Lets say 1024
* When the state object is created, allocate a buffer of that size.
* In `on_text`, use that buffer and process a bounded amount of input. If more input was provided, consume only that amount and return, so it'll be called again.

Since you've submitted a patch already, do you want to have a go at doing theabove instead, or should I do it? I don't know timing-wise when I'll get around to writing that.

**Comment by ddickstein** [comment]
While this is unaddressed, would breaking up the input and calling `chansend` on chunks of the input in a loop still have the guarantee that all of the input is rendered in the terminal buffer at once (i.e., without any intervening logic running)? Or could splitting up the `chansend` calls lead to a state where code on Neovim's event loop calls `nvim_buf_get_lines` on the terminal buffer and sees only some of the lines displayed because others haven't rendered yet?

**Comment by erw7** [comment]
As I mentioned in this [comment](https://github.com/erw7/neovim/commit/5207883127efa2257c7996e0cc688eb65c3b8e37#commitcomment-97586023), this issue has already been resolved by HEAD.
