### ISSUE TITLE
Early vim style 'syntax enable' command breaks treesitter attaching capabilities

### ISSUE THREAD

**Issue by RayZ0rr** [neovim/neovim#17083]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

xterm-256color

### Installation

pacman ( arch official package repo )

### How to reproduce the issue

Use the below [minimal rc file](https://gist.github.com/RayZ0rr/8df7ae674b7c9b641403fe37faf0d031) (gist here)

<details>
<summary> min-vimrc.lua  </summary>

```lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

--vim.cmd [[ source ~/minimal_settings.vim ]]
local temp_dir
if on_windows then
  temp_dir = vim.loop.os_getenv 'TEMP'
else
  temp_dir = '/tmp'
end

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'nvim-treesitter/nvim-treesitter',
			-- 'nvim-treesitter/nvim-treesitter-textobjects',
			-- 'JoosepAlviste/nvim-ts-context-commentstring',
      -- 'neovim/nvim-lspconfig',
			-- 'navarasu/onedark.nvim',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
end

-- #########################################################
-- PROBLEM COMMANDS
-- #########################################################
-- vim.opt.syntax = 'enable'  -- THIS WORKS
vim.cmd [[ syntax enable ]]   -- THIS DOESN'T
-- #########################################################

-- Treesitter configuration
vim.cmd([[
 	set foldmethod=expr
	set foldexpr=nvim_treesitter#foldexpr()
	set foldlevel=99
]])

-- Parsers must be installed manually via :TSInstall
require('nvim-treesitter.configs').setup {
	ensure_installed = {
		"bash",
		"c",
		"cpp",
		"lua",
		"python",
		"rust",
		"html",
		"css",
		"toml",
		"vim",
		-- for `nvim-treesitter/playground`
		"query",
	},
	-- Install languages synchronously (only applied to `ensure_installed`)
	sync_install = false,
	highlight = {
		enable = true, -- false will disable the whole extension
		additional_vim_regex_highlighting = false,
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			-- init_selection = 'gnn',
			init_selection = '<cr>',
			node_incremental = '<tab>',
			scope_incremental = 'grc',
			node_decremental = '<s-tab>',
		},
  },
  indent = {
    enable = true,
  },
}

```
</details>

1). `nvim -nu min-vimrc.lua`
2). Open any file with treesitter parser or lsp client.
`nvim -nu min-vimrc.lua file1 file2 ...`
3). Doesn't attach   
4). Open two files with treesitter parser or lsp client.  
5). Attach for second one but doesn't attach for first  
6). using `vim.opt.syntax = 'enable' ` doesn't show this issue

### Expected behavior

Clients and treesitter attaches to all files

### Actual behavior

Doesn't attach to first file

**Comment by RayZ0rr** [comment]
This is not reproducible when using [this minimal rc](https://gist.github.com/RayZ0rr/a56ec0dc47b81726e3a6b4e7366196c6) based on [vim-plug ](https://github.com/junegunn/vim-plug). I honestly don't know whether this is a packer issue or init.vim vs init.lua issue. Can anyone with know-how tell the differences between these two minimal rc files ?
[minimal rc vim](https://gist.github.com/RayZ0rr/a56ec0dc47b81726e3a6b4e7366196c6) (based on vim-plug, derived from nvim-cmp minimal rc file)
[minimal rc lua](https://gist.github.com/RayZ0rr/8df7ae674b7c9b641403fe37faf0d031) (based on packer, derived from lspconfig minimal rc file)

**Comment by mjlbach** [comment]
This should have already been fixed in https://github.com/neovim/neovim/pull/16723

**Comment by RayZ0rr** [comment]
But treesitter is showing same behaviour. Were you able to reproduce?

**Comment by RayZ0rr** [comment]
Checked with both `NVIM v0.6.1 (2021-12-31)` and `NVIM v0.7.0-dev+886-ga88046fe2` appimages. As I said in my comment above, issue is still there with this [minimalrc.lua](https://gist.github.com/RayZ0rr/8df7ae674b7c9b641403fe37faf0d031) based on packer. However, problem is not there with this [minimalrc.vim](https://gist.github.com/RayZ0rr/a56ec0dc47b81726e3a6b4e7366196c6) based on vim-plug. So, is this a packer issue or something else. What is difference between these two minimal rc files?

**Comment by mjlbach** [comment]
The following works fine for me:

```lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.cmd [[ syntax enable ]]   -- THIS WORKS
  require('lspconfig').clangd.setup{}
  -- vim.cmd [[ syntax enable ]]   -- SO DOES THIS
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

I don't know about treesitter, I just want to remove the LSP from the title as it seems to work fine.

**Comment by RayZ0rr** [comment]
@mjlbach with my limited knowledge, I think it's treesitter problem. The following minimal rc derived from yours breaks on my setup:

```lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
      'nvim-treesitter/nvim-treesitter',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.cmd [[ syntax enable ]] -- PROBLEM IF BELOW COMMAND DIRECTLY BELOW
  vim.cmd([[ " CAUSES PROBLEM PROBLEM WITH ABOVE LINE
    set foldmethod=expr
    set foldexpr=nvim_treesitter#foldexpr()
    set foldlevel=99
  ]])
  require('lspconfig').clangd.setup{}
  -- vim.cmd([[ " PUTTING HERE WORKS
    -- set foldmethod=expr
    -- set foldexpr=nvim_treesitter#foldexpr()
    -- set foldlevel=99
  -- ]])
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

I will make an issue at [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter)
