### ISSUE TITLE
`link` and `nocombine` attributes missing from `get_hl`/`synIDattr` functions

### ISSUE THREAD

**Issue by qubidt** [neovim/neovim#19254]
### Neovim version (nvim -v)

0.8.0-dev+563-gc68f1d7263

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Arch Linux (kernel 5.18.5)

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

Arch User Repository (AUR)

### How to reproduce the issue

running `nvim --clean -u test.vim`

with `test.vim`:
```vim
set termguicolors
:highlight NewHighlight cterm=underline,nocombine guifg=red ctermfg=blue gui=nocombine,italic
:highlight link LinkedHighlight NewHighlight
```

### Expected behavior

the result of `nvim_get_hl_by_name` (I believe) should contain a `nocombine` key when appropriate, and `synIDattr(..., 'nocombine')` should return an appropriate value

```vim
:highlight NewHighlight
:echo nvim_get_hl_by_name("NewHighlight", v:true)
:echo 'italic:' synIDattr(nvim_get_hl_id_by_name("NewHighlight"), "italic")
:echo 'nocombine:' synIDattr(nvim_get_hl_id_by_name("NewHighlight"), "nocombine")
```

```
NewHighlight   xxx cterm=underline,nocombine ctermfg=12 gui=italic,nocombine guifg=Red
{'foreground': 16711680, 'nocombine': v:true, 'italic': v:true}
italic: 1
nocombine: 1
```

as well as a `link` (or `linked`?) key

```vim
:highlight LinkedHighlight
:echo nvim_get_hl_by_name("LinkedHighlight", v:true)
:echo 'link:' synIDattr(nvim_get_hl_id_by_name("LinkedHighlight"), "link")
```

```
LinkedHighlight xxx links to NewHighlight
{'foreground': 16711680, 'nocombine': v:true, 'italic': v:true}
link: 1
```

### Actual behavior

`synIDattr(..., 'nocombine')` always returns the same result as `synIDattr(..., 'name')` and `nvim_get_hl_by_name` never has `nocombine`:

```vim
:highlight NewHighlight
:echo nvim_get_hl_by_name("NewHighlight", v:true)
:echo 'italic:' synIDattr(nvim_get_hl_id_by_name("NewHighlight"), "italic")
:echo 'nocombine:' synIDattr(nvim_get_hl_id_by_name("NewHighlight"), "nocombine")
```

```
NewHighlight   xxx cterm=underline,nocombine ctermfg=12 gui=italic,nocombine guifg=Red
{'foreground': 16711680, 'italic': v:true}
italic: 1
nocombine: NewHighlight
```

`link` (`linked`?) is completely missing from both:

```vim
:highlight LinkedHighlight
:echo nvim_get_hl_by_name("LinkedHighlight", v:true)
:echo 'link:' synIDattr(nvim_get_hl_id_by_name("LinkedHighlight"), "link")
```

```
LinkedHighlight xxx links to NewHighlight
{'foreground': 16711680, ''italic': v:true}
link:
```

**Comment by MunifTanjim** [comment]
Upstream vim fix for `nocombine`:
- https://github.com/vim/vim/pull/10816

**Comment by clason** [comment]
#19582

**Comment by zeertzjq** [comment]
Fixed by #19582

**Comment by MunifTanjim** [comment]
@zeertzjq it was partially solved. The `link` part is not fixed yet.

**Comment by zeertzjq** [comment]
Oh, `nocombine` hasn't been added to `nvim_get_hl_by_nam` either.

**Comment by MunifTanjim** [comment]
Just asking for clarification, should `link` be returns from `nvim_get_hl_*` and `synIDattr` function? Or does that belong to some other place?

**Comment by zeertzjq** [comment]
I'm not sure either.

**Comment by clason** [comment]
@bfredl?
