### ISSUE TITLE
Error with UI  : "decor_provider_invoke:37: error in provider (UNKNOWN PLUGIN)"

### ISSUE THREAD

**Issue by woosaaahh** [neovim/neovim#19883]
### Neovim version (nvim -v)

v0.8.0-dev-905-g6b9852cc4

### Vim (not Nvim) behaves the same?

not related

### Operating system/version

GNU/Linux - Arch Linux 5.19

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

kitty 0.25.2

### Installation

nightly build

### How to reproduce the issue

Put this in a config file, then open Telescope `find_files` picker.
```lua
require("telescope").setup({
    pickers = {
        find_files = {
            preview = {
                hide_on_startup = true,
            },
        },
    },
})
vim.keymap.set("n", "<leader>f", require("telescope.builtin").find_files)
```

### Expected behavior

No error.

### Actual behavior

Since 4 days ago (2022-08-18), when I use Telescope, I get this error in the main window. 
The error appears only the first time I use the `find_files` picker but no more errors after I open the picker again and again...

![2022-08-21_16-10_nvim-telescope-bug](https://user-images.githubusercontent.com/111681540/185805214-d36a84e2-4501-4a91-88fe-ebe6395a046c.png)

Nothing is listed when using `:messages` but I found this type of messages in `~/.local/state/nvim/log`
```log
...
ERR 2022-08-21T19:55:43.972 nvim.240299.0 decor_provider_invoke:37: error in provider (UNKNOWN PLUGIN):end: Error executing lua: attempt to call a nil value
stack traceback:
...
```
Note : There is nothing in the log file after `stack traceback:` line.

The log message seems related to this : 
- [decoration_provider.c#L37](https://github.com/neovim/neovim/blob/master/src/nvim/decoration_provider.c#L37)
- [extmark.c#L8](https://github.com/neovim/neovim/blob/master/src/nvim/api/extmark.c#L86)

As I first thought it was a Telescope issue, I tried the latest Telescope commit before 2022-08-18, used the latest nvim nightly build and the issue was still there.

Then I tried latest Telescope version and tried a manual bissect until this commit : 
d879331 "feat(ui): allow to set the highlight namespace per window" 2022-08-17.

Before this commit, everything work as expected !

**Comment by bfredl** [comment]
please try the latest commit on master https://github.com/neovim/neovim/commit/c086bf60794811ef33480e87000630e2d498b1bd

**Comment by woosaaahh** [comment]
Seems fixed now. Thank you so much for the fast reply and fix !

Thanks to all direct/indirect contributors for Neovim in general !

**Comment by andrewferrier** [comment]
For the record, I am still seeing this exact error message periodically in NVIM v0.9.0-dev-546+g98daaa798. It seems random (I cannot find a reliable set of repro instructions), but if I do, I'll open a separate issue.

**Comment by andrewferrier** [comment]
Correction, line 47 in my case:

```
decor_provider_invoke:47: error in provider (UNKNOWN PLUGIN):end: Error executing lua: attempt to call a nil value
```
