### ISSUE TITLE
Copying and pasting from system clipboard to command line adds trailing `<F37>`

### ISSUE THREAD

**Issue by renstrom** [neovim/neovim#2024]
Basically, I select some text to automatically copy it to the system clipboard and the paste it to the command line using <kbd>cmd</kbd><kbd>v</kbd> I get a trailing `<F37>` string/character.

This with `nvim -u NONE` using https://github.com/neovim/neovim/commit/b1d079c83b3dd459114d1ba7c2ff1b07a9ee3e9e and iTerm2 (Build 2.0.0.20141103).

![screen_shot_2015-02-19_at_12_01_46](https://cloud.githubusercontent.com/assets/177685/6265508/837fed32-b82f-11e4-8187-fdcbdfb1013c.png)

**Comment by renstrom** [comment]
Reproduced with the regular Terminal.app as well.

**Comment by tarruda** [comment]
Should be fixed in #2025

**Comment by renstrom** [comment]
Just verified that #2025 fixes the issues.

**Comment by shmup** [comment]
Using neovim nightly on Ubuntu with Gnome Terminal this still happens.

**Comment by Pyrohh** [comment]
@shmup what's the output of `--version`? I remember @fwalch saying those nightlies were outdated, but I'm not sure that's still true.

**Comment by gacha** [comment]
I got the same issue on NVIM 0.0.0-alpha+201504270459

**Comment by renstrom** [comment]
I actually experience this myself on occasion. And I believe it's related to bracketed paste mode, because when this happens I'm left with paste mode turned on.

**Comment by mhartington** [comment]
Same as @renstrom, it happens rarely, but I still have issues where `<F37>` are being inserted when I use `cmd-v` to paste things in


NVIM 0.0.0-alpha+201507182239 (compiled Jul 18 2015 19:16:33)
Iterm 2 Nightlies
Tmux

**Comment by davydovanton** [comment]
I have this problem too
```
NVIM 0.0.0-alpha+201507232235 (compiled Jul 25 2015 20:37:11)
Commit: 7a6bf3f418c5ad94ac2ac71f21275a87d08e87b9
```
Iterm2 + tmux

**Comment by firedev** [comment]
I have noticed it is happening when pasting urls from Chrome on OS X in Insert more. Using `p` and Normal mode works fine. So it goes like this:

1. Copy URL for this page in Chrome
2. Switch to Neovim (iTerm2, tmux)
3. `p`
```
https://github.com/neovim/neovim/issues/2024
```
4. `i<Ctrl-V>`
```
<F37>https://github.com/neovim/neovim/issues/2024<F37>
```
5. `i<Ctrl-R>+`
```
https://github.com/neovim/neovim/issues/2024
```

**Comment by skylerberg** [comment]
I have this issue on Ubuntu 14.04 using gnome-terminal. From `nvim --version`
```
NVIM 0.0.0-alpha (compiled Aug 26 2015 20:11:47)
```
I get just a trailing `<F37>` and am left in paste-mode. This happens fairly often (maybe every two dozen pastes), but it is not consistent. Leaving paste-mode and pasting the same text again usually works as expected.

**Comment by firedev** [comment]
I think it is working for me in OS X now. Just installed new `neovim --HEAD` yesterday from Homebrew. And switched to it...

**Comment by firedev** [comment]
Okay, just a couple of days later it started to <37> again :<

**Comment by edrex** [comment]
seeing this with homebrew build from yesterday evening.

**Comment by tarruda** [comment]
Should be fixed now

**Comment by davydovanton** [comment]
@tarruda thanks! :star2:

**Comment by firedev** [comment]
No way! Thank you!!
