### ISSUE TITLE
[BUG] Rendering glitch after loading a session.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2097]
After loading a session, like [this one](http://hastebin.com/fihukozahe.vim), the UI glitches out like this (I'm on the tarruda:builtin-terminal-emulation branch, but I believe it's unrelated to that):

https://www.youtube.com/watch?v=y7gwEie_aac&feature=youtu.be

**Comment by trusktr** [comment]
The glitch is resolved when the window gets resized: http://youtu.be/W4nx0Qeh1LQ

**Comment by justinmk** [comment]
Assuming this is fixed.

**Comment by trusktr** [comment]
@justinmk It still happens. It just happened to me a couple days ago loading a Vim sesh.

**Comment by justinmk** [comment]
Folding this into the numerous other redraw issues.
