### ISSUE TITLE
wildmenu causes the statusline to appear temporarily

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#2255]
When a terminal window is open, `wildmenu` is on, and the statusbar isn’t visible (either `laststatus=0` or `laststatus=1` and no other window is open), tapping `wildchar` (usually `<Tab>`) causes the statusbar to appear _instead of_ the wildmenu. Tapping `wildchar` again returns everything to normal, with the second wildmenu entry selected.
## Tested on:

a6e53a3 Merge PR #2076 'Builtin terminal emulation'
## Steps to reproduce:

From a shell, run `nvim -u NONE +'set wildmenu laststatus=0' term://sh`
Then, inside nvim, type `:<Tab>`
## Expected results:

The wildmenu appears, with the first entry (`!`) selected.
## Actual results:

A statusline appears, with the text `term://.//19967:sh`. The wildmenu doesn’t appear. A `!` is correctly inserted in the command-line, but isn’t drawn until another key is presed (e.g. `<C-L>`).

**Comment by Grimy** [comment]
I can no longer reproduce this as of e38cbb9. I believe it was inadvertently fixed at some point. I’m closing this issue.

**Comment by glacambre** [comment]
Hi,
Using NVIM v0.1.1-81-g1946f96 (compiled Dec 15 2015 18:33:05), I still have this problem.
This is how I reproduce the bug: 
```
nvim -u NONE +'set wildmenu' -c "set laststatus=0" -c "vsplit" -c "term"
```
Then open the cmdline (using ':') and use 'TAB' to try to trigger the wildmenu.

**Comment by Grimy** [comment]
This is a problem with term, not wildmenu.
