### ISSUE TITLE
Failing test on OS X...

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#2298]
This has shown up on the QB builds of master.

``` text
test/functional/job/job_spec.lua:257: Expected objects to be the same.
Passed in:
(table): {
  [1] = 'notification'
  [2] = 'wait'
  [3] = {
    [1] = {
      [1] = -1
      [2] = -1 } } }
Expected:
(table): {
  [1] = 'notification'
  [2] = 'wait'
  [3] = {
    [1] = {
      [1] = 4
      [2] = -1 } } }
stack traceback:
    test/functional/job/job_spec.lua:257: in function <test/functional/job/job_spec.lua:250>
```

It seems to be occurring on OS X only at the moment, though there may be something racy going on that could affect other platforms too.

**Comment by tarruda** [comment]
These timeout tests are tricky, not sure how to handle this one...

**Comment by tarruda** [comment]
@jszakmeister I merged some changes that should remove(or at least greaty reduce) indeterminism from the new job tests. Can you confirm any improvements in the QB results?

**Comment by jszakmeister** [comment]
@tarruda The latest build appears to have passed on all 3 platforms: http://neovim-qb.szakmeister.net/overview/10

That's definitely an improvement.  FWIW, it's currently polling the repo every 5 minutes for changes on master and will automatically build again when it sees something has changed.

**Comment by jszakmeister** [comment]
Just an FYI: master (after the latest merge) is still showing signs of hanging: http://neovim-qb.szakmeister.net/build/220

On the FreeBSD instance, the step timed out and terminated the functional test run.  I re-ran against master and it worked the second time around, so the issue is a bit racy (as usual).  I know you all are working on it, but I just wanted to let you know there's still some issues left.

**Comment by tarruda** [comment]
@jszakmeister I'm having a bit of trouble finding a relevant line in the quickbuild log. Can you configure it to use the utfTerminalDetailed output handler and link to me which test/file is causing the hang?

**Comment by jszakmeister** [comment]
It's not very repeatable, and reconfiguring the handler would break the test charts and a few other steps (related to getting reporting in place).  I really wish I could get both junit style output *and* utfTerminalDetailed from busted.  You only get one or the other though. :-(

**Comment by jszakmeister** [comment]
FWIW, I'm hoping to move to the new TAP handler, when it becomes available.  I think that will be more useful to us in the end (and we can tee the output so we can capture it and see it in the logs).

**Comment by tarruda** [comment]
> FWIW, I'm hoping to move to the new TAP handler, when it becomes available. I think that will be more useful to us in the end (and we can tee the output so we can capture it and see it in the logs).

:+1: I will leave this issue open until we can figure out whats causing the hang.

BTW, is it possible that failed downloads are causing it? I ask because it just happened to travis: https://travis-ci.org/neovim/neovim/jobs/57025849

**Comment by jszakmeister** [comment]
> I will leave this issue open until we can figure out whats causing the hang.

Sounds good.

> BTW, is it possible that failed downloads are causing it? I ask because it just happened to travis: https://travis-ci.org/neovim/neovim/jobs/57025849

No, we made it past all the download steps.

**Comment by tarruda** [comment]
@jszakmeister I've fixed some other tests in #2405, are you still seeing random failures?

**Comment by jszakmeister** [comment]
FWIW, I've seen this one still pop up now and again.

**Comment by jszakmeister** [comment]
This test still fails sometimes, and not only on OS X.  It failed on master under FreeBSD just recently:

```text
test/functional/job/job_spec.lua @ 339
Failure message: test/functional/job/job_spec.lua:346: Expected objects to be the same.
Passed in:
(table) {
[1] = 'notification'
[2] = 'wait'
*[3] = {
*[1] = {
*[1] = -1
[2] = -1 } } }
Expected:
(table) {
[1] = 'notification'
[2] = 'wait'
*[3] = {
*[1] = {
*[1] = 4
[2] = -1 } } }
stack traceback:
test/functional/job/job_spec.lua:346: in function <test/functional/job/job_spec.lua:339>
```

**Comment by justinmk** [comment]
Haven't seen these particular failures in a long time. The new test util function `expect_msg_seq` helps in some cases.
