### ISSUE TITLE
Not resizing correctly when switching to fullscreen

### ISSUE THREAD

**Issue by cHoco** [neovim/neovim#2322]
Hi,
if I start neovim in the terminal app and then switch to full screen, neovim doesn't resize correctly. It takes the whole width but not the full height available! 
If syntax highlighting is disabled (syntax off) neovim resizes correctly.

### To reproduce:

- Start nvim in terminal app `nvim .vimrc -u NONE`
- Switch terminal app to fullscreen -> nvim resized correctly (takes full height and width)
- Disable fullscreen
- Switch syntax highlighting on `:syntax on`
- Switch terminal app to fullscreen -> neovim resized incorrectly (takes full width, not full heigh)

This problem doesn't affect vim, but affects neovim both in Terminal app and iTerm2.

**Comment by blueyed** [comment]
I can confirm this issue (using the "awesome" window manager), and maximizing the terminal.

It does not appear to affect fullscreen mode, and can be more easily triggered with e.g. Neovim's src/nvim/terminal.c than with the startify buffer after starting nvim.
It's not 100% reproducible for me though, but will eventually happen sometimes.

A workaround appears to be then to first maximize the terminal window vertically and then horizontally.

**Comment by cHoco** [comment]
Yeah, it also happens when resizing the window manually, but it's not always reproducible. Instead using the osx fullscreen feature I can reproduce it constantly :(

**Comment by blueyed** [comment]
It sounds like `SIGWINCH` is not handled properly.

From a quick look, this seems to help for me:

    diff --git i/src/nvim/tui/tui.c w/src/nvim/tui/tui.c
    index 72f9397..14369e8 100644
    --- i/src/nvim/tui/tui.c
    +++ w/src/nvim/tui/tui.c
    @@ -210,7 +210,7 @@ static void sigwinch_cb(uv_signal_t *handle, int signum)
       event_push((Event) {
         .data = handle->data,
         .handler = try_resize
    -  }, false);
    +  }, true);
     }
     
     static bool attrs_differ(HlAttrs a1, HlAttrs a2)

It changes the `deferred` attribute of the queued event to `true`.

Maybe the issue is that otherwise the event gets handled too early sometimes,
while the window has been resized only horizontally?!

**Comment by cHoco** [comment]
I just tried your simple patch and indeed it solves the problem for me.

**Comment by erf** [comment]
it  was working better for a second, but now (Commit: 94153ab975401572ea6942b4fba8dcfba53ceecc) the bug is back..

**Comment by splinterofchaos** [comment]
I have this problem on ubuntu with gnome-terminal and st. Renamed the issue because it's not OSX-specific.

**Comment by erf** [comment]
Seems to work now - commit 84891f2802a0db1a257580f341d70a5fdb0f6c75

**Comment by splinterofchaos** [comment]
Still doesn't work for me.

**Comment by blueyed** [comment]
It's still an issue for me, too.

@erf 
Still fixed for you? What window manager and terminal are you using?

**Comment by erf** [comment]
No it's buggy for me too.. commit b6af1afee6eab0a430533efcbb8af6c6b1ffe585 OSX 10.10.3 (14D136) Terminal Version 2.5.3 (343.7)

**Comment by cHoco** [comment]
Just wondering, is there are reason why the fix proposed by @blueyed can't be applied? It completely fixes the bug for me

**Comment by blueyed** [comment]
@cHoco 
I don't know.. maybe I should create a PR for it, but then I wasn't sure if it's the correct way to address it.

Feedback would be really appreciated, regarding https://github.com/neovim/neovim/issues/2322#issuecomment-88444533.

**Comment by splinterofchaos** [comment]
@blueyed that would be good. I'm curious why this fails, though. It looks like, in `update_size()`, we have three different ways of obtaining the new size: `uv_tty_get_winsize`, checking `$LINES` and `$COLUMNS` if that fails, and finally `unibi_get_num` if the previous failed. The question is: when this problem occurs, did any of these fail? If not, which gave us the answer? Are we using them correctly?

In my testing, `uv_tty_get_winsize` always works (but gives the wrong size). Reading `$LINES` and `$COLUMNS` always fails, and so we fall back to `unibi_get_num`.

Using @blueyed's solution, it does seem to work, but I notice that if I put an `EMSG` below the call to `uv_tty_get_winsize`, it prints once at startup, then again, twice, once before resizing and once after. I wish I knew why nvim exhibited any of this behaviour.

**Comment by blueyed** [comment]
@splinterofchaos 
Thanks for investigating!

It sounds like making the event deferred (my patch) is only a workaround for another problem?

The difference between deferred_events and immediate_events is documented like
this:

    // deferred_events:  Events that should be processed as the K_EVENT special key
    // immediate_events: Events that should be processed after exiting libuv event
    //                   loop(to avoid recursion), but before returning from
    //                   `event_poll`

The PR is #2738.

**Comment by erf** [comment]
This problem is back now

**Comment by justinmk** [comment]
Right, because it should be changed to `async=false`. I had my eye on that.

**Comment by justinmk** [comment]
@tarruda If I follow 502aee690c980fcb3cfcb3f211dcfad06103db46 correctly, it looks like `tui_start()` is adding `sigwinch_cb` to the "fast events" queue, which is not deferred to the main loop. But the fix for this issue (https://github.com/neovim/neovim/pull/2738) suggests that `sigwinch_cb` should be deferred. How can this be achieved now?

**Comment by tarruda** [comment]
> @tarruda If I follow 502aee6 correctly, it looks like tui_start() is adding sigwinch_cb to the "fast events" queue, which is not deferred to the main loop. But the fix for this issue (#2738) suggests that sigwinch_cb should be deferred. How can this be achieved now?

This should do it:

```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 460fdb8..38593ee 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -140,6 +140,7 @@ UI *tui_start(void)

   // listen for SIGWINCH
   signal_watcher_init(&loop, &data->winch_handle, ui);
+  data->winch_handle.events = queue_new_child(loop.events);
   signal_watcher_start(&data->winch_handle, sigwinch_cb, SIGWINCH);

   ui->stop = tui_stop;
```

@erf, can you test if this patch fixes the issue?

**Comment by erf** [comment]
That solves it! @tarruda

**Comment by blueyed** [comment]
Is anybody else seeing a regression on master for this?  (I've filed https://github.com/neovim/neovim/issues/3385 about it)

**Comment by ludbek** [comment]
I still face this issue in `terminator`. Pressing `f11` after maximizing the terminator solved the issue for me.

**Comment by blueyed** [comment]
Just for reference, https://github.com/neovim/neovim/issues/3385 should be fixed now.

@ludbek 
Can you try it? (current master)

**Comment by JakubKoralewski** [comment]
i seem to have something similar with windows terminal

https://user-images.githubusercontent.com/43069023/108632158-b9a83d00-746d-11eb-92db-f7cfa6a3ea41.mp4

<details>
<summary>Details</summary>

```
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

</details>

**Comment by nikau6** [comment]
I still have this issue.
![Screenshot from 2024-03-31 01-28-34](https://github.com/neovim/neovim/assets/12031111/a655a4dd-40b8-4a0e-b047-25cc0db61956)
![Screenshot from 2024-03-31 01-28-41](https://github.com/neovim/neovim/assets/12031111/cfbb8999-3ed4-44a9-8452-abf4890dc80b)

vim 0.9.5
gnome-terminal

**Comment by justinmk** [comment]
> NVIM v0.4.4

@JakubKoralewski that is a very old version of Nvim. We can't fix bugs if you don't update Nvim.
