### ISSUE TITLE
nvim -d and git difftool

### ISSUE THREAD

**Issue by rustushki** [neovim/neovim#2377]
I'm having an issue with "nvim -d" as a difftool for git.  Here's a summary:

    $ git difftool
    
    Viewing (1/2): 'build.xml'
    Launch 'nvimdiff' [Y/n]: Y
    2 files to edit
    
    Viewing (2/2): 'pom.xml'
    Launch 'nvimdiff' [Y/n]: 2 files to edit     // I did not actually get a chance to say Y, N or Ctrl+C

With just 2 files, it's not a big deal, but when many files are to be displayed, I don't have a chance to cancel part way through.

Troubleshooting 1:
I've tried using 'meld' as my difftool as a troubleshooting step, and it handles this same situation correctly.

Troubleshooting 2:
I tried using bash instead of zsh.  I tried using a different prompt.  I also tried using a different $TERM setting.  Problem continues to reproduce.

Troubleshooting 3:
I tried using xterm instead of gnome-terminal and the problem reproduces.

Here are my difftool settings:

    [difftool]
        prompt = true
    [diff]
        tool = nvimdiff
    [difftool "nvimdiff"]
        cmd = "nvim -d -u ~/.vimrc \"$LOCAL\" \"$REMOTE\""

EDIT: I'm using the most recent build of neovim as of this morning.

**Comment by justinmk** [comment]
Does it work if you change it to vim?

    cmd = "vim -d -u ~/.vimrc \"$LOCAL\" \"$REMOTE\""

**Comment by rustushki** [comment]
I made that change and it appears to work as expected... here's the output:

    $ git difftool
    
    Viewing (1/2): 'build.xml'
    Launch 'nvimdiff' [Y/n]: 
    2 files to edit
    
    Viewing (2/2): 'pom.xml'
    Launch 'nvimdiff' [Y/n]: 
    2 files to edit

**Comment by justinmk** [comment]
Possibly we're sending a spurious newline after exit?

**Comment by mhinz** [comment]
FFIW, with the same settings in the gitconfig I can't reproduce it with iTerm2 and git 2.4.0.rc1.

**Comment by fwalch** [comment]
This problem seems similar to #2372 (dialog "answered" without user interaction).

**Comment by gdrooid** [comment]
This is what it looks like on my system with sakura and git 2.0.5:
```
❯ LANGUAGE=en git difftool HEAD^

Viewing (1/5): 'src/nvim/buffer_defs.h'
Launch 'nvimdiff' [Y/n]: y
2 files to edit

Viewing (2/5): 'src/nvim/memline.c'
Launch 'nvimdiff' [Y/n]: /usr/libexec/git-core/git-difftool--helper: line 52: read: read error: 0: Resource temporarily unavailable
2 files to edit

Viewing (3/5): 'src/nvim/misc2.c'
Launch 'nvimdiff' [Y/n]: /usr/libexec/git-core/git-difftool--helper: line 52: read: read error: 0: Resource temporarily unavailable
2 files to edit

Viewing (4/5): 'src/nvim/undo.c'
Launch 'nvimdiff' [Y/n]: /usr/libexec/git-core/git-difftool--helper: line 52: read: read error: 0: Resource temporarily unavailable
2 files to edit

Viewing (5/5): 'src/nvim/undo_defs.h'
Launch 'nvimdiff' [Y/n]: /usr/libexec/git-core/git-difftool--helper: line 52: read: read error: 0: Resource temporarily unavailable
2 files to edit
```

**Comment by justinmk** [comment]
@rustushki @gdrooid Can you run it with GIT_TRACE like this:

    GIT_TRACE=1 git difftool

**Comment by rustushki** [comment]
@justinmk @gdrooid 
Here's my output with "cmd = "nvim -d -u ~/.vimrc \"$LOCAL\" \"$REMOTE\"""

    $ GIT_TRACE=1 git difftool
    20:23:35.009697 git.c:554               trace: exec: 'git-difftool'
    20:23:35.009794 run-command.c:341       trace: run_command: 'git-difftool'
    20:23:35.119948 git.c:349               trace: built-in: git 'diff'
    20:23:35.125107 run-command.c:341       trace: run_command: 'git-difftool--helper' 'build.xml' '/tmp/F4zDji_build.xml' 'f2b0b0f3f474e9e91c669e7cf463e7ebac02aa9b' '100644' 'build.xml' '0000000000000000000000000000000000000000' '100644'
    20:23:35.125437 run-command.c:192       trace: exec: 'git-difftool--helper' 'build.xml' '/tmp/F4zDji_build.xml' 'f2b0b0f3f474e9e91c669e7cf463e7ebac02aa9b' '100644' 'build.xml' '0000000000000000000000000000000000000000' '100644'
    20:23:35.131227 git.c:349               trace: built-in: git 'config' 'diff.tool'
    20:23:35.133771 git.c:349               trace: built-in: git 'config' 'difftool.nvimdiff.cmd'
    20:23:35.137590 git.c:349               trace: built-in: git 'config' '--bool' 'mergetool.prompt'
    20:23:35.140454 git.c:349               trace: built-in: git 'config' '--bool' 'difftool.prompt'
    
    Viewing (1/2): 'build.xml'
    Launch 'nvimdiff' [Y/n]: 
    20:23:35.904613 git.c:349               trace: built-in: git 'config' 'difftool.nvimdiff.cmd'
    20:23:35.907390 git.c:349               trace: built-in: git 'config' 'difftool.nvimdiff.path'
    20:23:35.909634 git.c:349               trace: built-in: git 'config' 'mergetool.nvimdiff.path'
    20:23:35.912496 git.c:349               trace: built-in: git 'config' 'difftool.nvimdiff.cmd'
    20:23:35.915347 git.c:349               trace: built-in: git 'config' 'difftool.nvimdiff.cmd'
    2 files to edit
    20:23:36.802129 run-command.c:341       trace: run_command: 'git-difftool--helper' 'pom.xml' '/tmp/8qStm6_pom.xml' 'af79230b5812fafaa3f1a09dd611969da0a9448b' '100644' 'pom.xml' '0000000000000000000000000000000000000000' '100644'
    20:23:36.802546 run-command.c:192       trace: exec: 'git-difftool--helper' 'pom.xml' '/tmp/8qStm6_pom.xml' 'af79230b5812fafaa3f1a09dd611969da0a9448b' '100644' 'pom.xml' '0000000000000000000000000000000000000000' '100644'
    20:23:36.808442 git.c:349               trace: built-in: git 'config' 'diff.tool'
    20:23:36.811087 git.c:349               trace: built-in: git 'config' 'difftool.nvimdiff.cmd'
    20:23:36.814201 git.c:349               trace: built-in: git 'config' '--bool' 'mergetool.prompt'
    20:23:36.816845 git.c:349               trace: built-in: git 'config' '--bool' 'difftool.prompt'
    
    Viewing (2/2): 'pom.xml'
    Launch 'nvimdiff' [Y/n]: 20:23:36.820030 git.c:349               trace: built-in: git 'config' 'difftool.nvimdiff.cmd'
    20:23:36.822718 git.c:349               trace: built-in: git 'config' 'difftool.nvimdiff.path'
    20:23:36.824716 git.c:349               trace: built-in: git 'config' 'mergetool.nvimdiff.path'
    20:23:36.827716 git.c:349               trace: built-in: git 'config' 'difftool.nvimdiff.cmd'
    20:23:36.830447 git.c:349               trace: built-in: git 'config' 'difftool.nvimdiff.cmd'
    2 files to edit

**Comment by rustushki** [comment]
Another note about this issue...  I rebuild nvim each morning using linuxbrew.  I first noted this issue some time in the last couple of weeks.  Prior to that nvim -d worked correctly.

**Comment by fwalch** [comment]
If it's really the same problem as #2372, the bug was introduced with 20f52f4 (previous revision 20f52f4 should work).

**Comment by rustushki** [comment]
@fwalch @justinmk I can confirm that the problem is not present in 20f52f4, but is present in bbcddc5.

**Comment by fwalch** [comment]
@tarruda Have you seen this? Any idea how to fix it? :-)

**Comment by nagisa** [comment]
More general and minimal way to reproduce:

`bash -c 'nvim -u NONE -i NONE -N --cmd q && read'`

`-u NONE -i NONE -N` args are not compulsory.

**Comment by blueyed** [comment]
This issue also affects the interactive use of `git add -p`, when using `e` to edit with nvim, after exiting:

> Stage this hunk [y,n,q,a,d,/,j,J,g,e,?]? Use of uninitialized value $key in string eq at /usr/local/libexec/git-core/git-add--interactive line 1105.

The git (perl) function is this:

The relevant part is this, where `ReadKey 0` does not set `$key` for some reason:

        ReadMode 'cbreak';
        my $key = ReadKey 0;
        ReadMode 'restore';
        if ($use_termcap and $key eq "\e") {

According to /usr/lib/perl5/Term/ReadKey.pm this should perform a normal read via `getc`:

    =item ReadKey MODE [, Filehandle]

    Takes an integer argument, which can currently be one of the following 
    values:

        0    Perform a normal read using getc
        -1   Perform a non-blocked read
        >0	 Perform a timed read

This happens with both libterm-readkey-perl 2.31-1 and 2.32-1+b1.

**Comment by justinmk** [comment]
@blueyed Thanks. This is definitely a problem on our end, @nagisa 's repro steps make that clear. 

Looks like we aren't releasing stdin...?

**Comment by justinmk** [comment]
Ok, I have a fix for this. PR tonight.

**Comment by justinmk** [comment]
Should be fixed now, please say if not!

**Comment by rustushki** [comment]
It looks like this is still a problem for me.  @nagisa's steps to reproduce show the correct behavior: the read waits until I type something.  However, when I use nvim as a difftool with git, it still manifests the same behavior.  Original Vim does not have the issue.  I can continue to use it as my difftool as a workaround.

**Comment by justinmk** [comment]
@rustushki How are you configuring git to use nvim as a difftool? Are you sure it isn't pointing to an older version?

**Comment by justinmk** [comment]
I just built latest and tried

    ./build/bin/nvim -d CMakeLists.txt Doxyfile && read

We're going to need more information before calling this a regression.

**Comment by justinmk** [comment]
> when I use nvim as a difftool with git, it still manifests the same behavior

@rustushki  Just to double-check, I tried latest nvim as a git difftool, and it worked correctly in every respect that I'm aware of. Here's the relevant part of my gitconfig:

```
[merge]
  tool = vimdiff
[mergetool]
  prompt = true
[mergetool "vimdiff"]
  cmd = nvim -d $BASE $LOCAL $REMOTE $MERGED -c '$wincmd w' -c 'wincmd J'
```

Notice I'm using `nvim -d` and `prompt=true`. I usually use prompt=false because I don't want to be prompted. With `prompt=true` (which is git's default), it correctly waited for confirmation after each `nvim -d` invocation, when git had mutliple file conflicts in the workspace.
