### ISSUE TITLE
Lines and columns initialized too late?

### ISSUE THREAD

**Issue by choco** [neovim/neovim#2403]
Hi I have a plugin that during its initialization uses the value of both lines and columns variables to performs some calculations.
Unfortunately both these value are initialized only after the first redraw (I think), since when I try to access them during the initialization phase they're still holding the default values 24 and 80.
Vim isn't affected by the same problem.
### Steps to reproduce:
- Create a minimal vimrc:

```
let lines = &lines
echo lines
```
- Prints 24 in neovim
- Prints correct number of lines vim

**Comment by cHoco** [comment]
Took a look to see what the problem was, in vim 
````
ui_get_shellsize();
win_init_size();
````

Instead in neovim we just call 
````
win_init_size();
````
load plugins and then attach the ui layer and update the size.

Maybe i should access columns and lines after VimEnter but just wanted to point out the difference, if it's something you may want to take a look into

**Comment by splinterofchaos** [comment]
Confirmed. 24 is the default value, but vim is able to print the correct value on startup.

This probably happens because one's `.nvimrc` is sourced well before the ui boots up. This is necessary because `.nvimrc` can be used to configure the gui, but if a plugin needs to know the screen size at boot, this will cause problems.

**Comment by justinmk** [comment]
I think the best we can do for this is to give a warning. Added this case to  https://github.com/neovim/neovim/issues/1202

**Comment by jamesbvaughan** [comment]
@choco Were you able to figure out a workaround for this? I would like to use the value of columns in my init.vim and haven't found a way to get it yet.

**Comment by justinmk** [comment]
I wonder if  @bfredl 's recent changes to allow dynamic setting of UI options, helps with this.

**Comment by bfredl** [comment]
Similar to #8754 there is nothing that should stop us from wait for TUI to initialize and report size before continuing with startup files and commands, if we so want.

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim/pull/9829

**Comment by MIvanchev** [comment]
I still have this with Neovim-Qt v0.5.0. `echo &liners` reports 26 at start up and changes after first redraw. Am I doing something wrong?

**Comment by MIvanchev** [comment]
Nevermind... this seems to be related to neovim-qt, it works OK in neovim.
