### ISSUE TITLE
inlay hint/virtual text getting highlighted together with matchparen characters

### ISSUE THREAD

**Issue by Sneeezu** [neovim/neovim#24152]
### Problem

When hovering over a matchparen character next to which is inlay hint, the inlay hint gets also highlighted. I think this issue is more related to the actual inline virtual text, but I'm clueless how to test it.

https://github.com/neovim/neovim/assets/82700981/4826ed3f-d7a1-472c-a545-8dea6bd79411

### Steps to reproduce

- Use this config (nvim -u init.lua) and open a rust file or edit the config

```lua
--- CHANGE THESE
local pattern = "rust"
local cmd = { "rust-analyzer" }
-- Add files/folders here that indicate the root of a project
local root_markers = { ".git", ".editorconfig", "Cargo.toml", "Cargo.lock" }
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd("FileType", {
	pattern = pattern,
	callback = function(args)
		local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
		local root_dir = match and vim.fn.fnamemodify(match, ":p:h") or nil
		vim.lsp.start({
			name = "rust_analyzer",
			cmd = cmd,
			root_dir = root_dir,
			settings = settings,
			on_attach = function(client, bufnr)
				vim.lsp.buf.inlay_hint(bufnr, true)
			end,
		})
	end,
})

```

<sub>yoinked from https://github.com/neovim/neovim/issues/24075<sub>

- Hover over a matchparent character next to which is inlay hint

### Expected behavior

Highlight only the matchparen characters, not the inlay hint/virtual text.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-576+g5ceb2238d3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux, kernel: 6.3.9-arch1-1

### Terminal name/version

alacritty 0.12.1 (5fdfd47f)

### $TERM environment variable

tmux-256color

### Installation

AUR/neovim-git

**Comment by zeertzjq** [comment]
https://github.com/neovim/neovim/pull/24099#issuecomment-1602198495

**Comment by MariaSolOs** [comment]
> https://github.com/neovim/neovim/pull/24099#issuecomment-1602198495

@zeertzjq Do you mean that this is now fixed?

**Comment by zeertzjq** [comment]
No

**Comment by MariaSolOs** [comment]
> No

Alright, thanks!

**Comment by p00f** [comment]
It happens even when you change the hl_mode to replace though

**Comment by zeertzjq** [comment]
Hmm, that's strange. And what's even stranger is that I can only reproduce this using inlay hint.

**Comment by zeertzjq** [comment]
@p00f Are you using vim-matchup? If so that's a different issue.

**Comment by aklk1ng** [comment]
@zeertzjq , i just compiled neovim `v0.10.0-dev-641+g811140e27`, but the problem still exists
![2023-07-07_10-35](https://github.com/neovim/neovim/assets/94452368/a62b94f9-2bca-4ab2-a5ea-a8730a978eff)

**Comment by zeertzjq** [comment]
Yes, it hasn't been fixed yet, but now this can fixed (with #24094 reintroduced) by simply removing this line:
```diff
diff --git a/runtime/lua/vim/lsp/inlay_hint.lua b/runtime/lua/vim/lsp/inlay_hint.lua
index f577a3169..6426b0c03 100644
--- a/runtime/lua/vim/lsp/inlay_hint.lua
+++ b/runtime/lua/vim/lsp/inlay_hint.lua
@@ -289,7 +289,6 @@ api.nvim_set_decoration_provider(namespace, {
               virt_text_pos = 'inline',
               ephemeral = false,
               virt_text = vt,
-              hl_mode = 'combine',
             })
           end
         end
```

**Comment by p00f** [comment]
@zeertzjq I only set it to `combine` to make cursorline look good, I didn't know cursorline always does the right thing. Should I make a PR to remove `hl_mode` then?

(I was using matchup, yes - fixed now)

**Comment by aklk1ng** [comment]
@zeertzjq , yes, thanks

**Comment by MariaSolOs** [comment]
@zeertzjq I'm still having this issue on v0.10.0-dev-653+gfbeef0d4e...
<img width="531" alt="image" src="https://github.com/neovim/neovim/assets/62502207/5881b014-5825-4ea0-a7a1-93b507bf80e4">

**Comment by p00f** [comment]
I'm also on that commit:
![image](https://github.com/neovim/neovim/assets/36493671/5fa7ce5d-24b8-432d-9541-e7df0f72508e)

**Comment by MariaSolOs** [comment]
@p00f hmmm I don't use vim-matchup, I use nvim-autopairs.

**Comment by clason** [comment]
... which means that this is an issue specific to that plugin, and should be reported there (first).

**Comment by zeertzjq** [comment]
@MariaSolOs Please use `vim.inspect_pos()` on the highlighted parenthesis to see what type of highlight it is.

**Comment by MariaSolOs** [comment]
Lol and now I can't reproduce it anymore lol. To be fair I was tweaking my `init.lua` when I took the picture, and so maybe the reloading of the plugins etc was causing the glitch. I'll make sure to report back if I see it happen again.
