### ISSUE TITLE
NeoVim chokes on too fast input

### ISSUE THREAD

**Issue by SirVer** [neovim/neovim#2454]
Repro steps:
- Start a tmux session:  
  `tmux new -s tmuxsession`.
- In a separate terminal, feed the session with input:  
  `tmux send-keys -t tmuxsession "vim -u NONE" Enter "iHi" Escape ':q!' Enter`

This will open a Vim session, enter insert mode, write "Hi" and exit vim. No problemo. Now replace vim with nvim:

`tmux send-keys -t tmuxsession "nvim -u NONE" Enter "iHi" Escape ':q!' Enter`

Result:

![result image](http://s9.postimg.org/b9d2qim4f/nvim_feederror.png)

Neovim misinterprets the Escape somehow and get's stuck in insert mode. The problem goes away if every character is send individually - but that is very slow.

This is a critical error for https://github.com/SirVer/ultisnips, it makes it impossible to run the test suite on NeoVim.

**Comment by bfredl** [comment]
nvim terminal ui interprets ESC + an immediate character as `alt-` combination. I think this is unavoidable if we want to fully support alt bindings in the terminal.

**Comment by bfredl** [comment]
An option to reliably emulate input in both vim and nvim might be to use `feedkeys("itext\<esc>") and so on. (though I haven't looked in ultisnips test suite, so don't know if its practical here)

**Comment by zachariahreed** [comment]
I see this behavior with human input too. I thought it was potentially my config (either nvim or tmux) and it's been on my list for a while to investigate what the cause is. I find myself contantly having to correct things because of this behavior and it's the main usability issue for me at this point. If support of alt bindings is mutually exclusive with correct handling of fast typing, I don't see their inclusion as good a tradeoff.

**Comment by tarruda** [comment]
Terminals encode the alt modifier using the esc byte, which relies on timing information to distinguish between the alt modifier or the esc key. It's sad that things are this way but there's little we can do about the problem except bundling a GUI that wont suffer from these issues(which is definitely in my plans). Maybe I will revisit this later, and add a TUI option to always treat the esc byte as the escape key(and consequently disable alt modifier), but for now I'm focused on other matters.

@SirVer the new TUI lets you work around the ambiguity when scripting interactions with nvim stdin: follow escape bytes (\x1b) with nul bytes(\x00). In your example it can easily be achieved like this:

```
tmux send-keys -t tmuxsession "vim -u NONE" Enter "iHi" Escape C-@ ':q!' Enter
```

Another option is to bypass the TUI and send keys via a msgpack-rpc socket by calling the `vim_input` function, which accepts the classic vim representation of keys such as `<esc>` or `<a-k>`.

**Comment by zachariahreed** [comment]
I can see how opening up a new set of keys to bind is attractive. However, the introduction of functionality that could ptotentially make the TUI a second-class citizen in the future worries me. It also seems counter to the spirit of vi. In order to head of this possiblility, I would propose that users are allowed to bind keys with the Alt modifier in their nvimrc, but packages are explicitly forbidden from doing so.

**Comment by Joushou** [comment]
TUI will always be first-class, but keybinding support is, due to annoying old semi-standards, impossible to get right. A lot of ctrl-combos cannot be used, as they send terminal controls that cannot be distinguished from the "normal" generators of these controls, ESC needs to wait for a moment to see what comes after to verify... It's all a bloody mess. I always considered making a new command-set (A mode the application could enable), but I didn't have any "large" project to put it into that would cause for the command-set to be adopted.

**Comment by kopischke** [comment]
> A quick workaround to the Esc problem would be to use Ctrl-C, which is instant, to escape Insert mode.

These are not functionally identical: leaving insert mode with `Ctrl-C` bypasses abbreviation checking and does not trigger `InsertLeave` (see `:h i_CTRL-C`).

**Comment by zachariahreed** [comment]
Fair enough. Thanks for the explanation. I'm (obviously) not super
familair with some of the details of terminal keyboard handling.


On Fri, Apr 24, 2015, at 06:01 PM, Kenny Levinsen wrote:
> TUI will always be first-class, but keybinding support is, due to
> annoying old semi-standards, impossible to get right. A lot of
> ctrl-combos cannot be used, as they send terminal controls that cannot
> be distinguished from the "normal" generators of these controls, ESC
> needs to wait for a moment to see what comes after to verify... It's
> all a bloody mess. I always considered making a new command-set (A
> mode the application could enable), but I didn't have any "large"
> project to put it into that would cause for the command-set to be
> adopted.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/neovim/neovim/issues/2454#issuecomment-95858512

**Comment by nagisa** [comment]
Does

```
set ttimeout
set ttimeoutlen=0
```

fix your issue? If so, a this is a duplicate of https://github.com/neovim/neovim/issues/2093

**Comment by zachariahreed** [comment]
@nagisa I was already running with these settings

**Comment by justinmk** [comment]
Perhaps we should have a "non-interacitive" mode that can be specified as a command-line flag. In this mode, meta-key chords would not be supported (unless the resulting sequence is mapped--same as Vim). @SirVer would this solve your problem?

**Comment by SirVer** [comment]
No, that Is a terrible Solution for me. I am using this to test ultisnips. If I test in another mode then the one the user will be in, it is no longer a realistic and good test. That is also the reason why feeding keys though the Python client is not a good test - the data takes another input path. 

The new tui also behaves differently on Unicode key inputs - basically nvim and vim are no longer compatible and plugins must decide which programs idiosyncrasies they want to cater to. That is really unfortunate.

**Comment by justinmk** [comment]
> If I test in another mode then the one the user will be in, it is no longer a realistic and good test.

But you can't send meta-key chords to Vim anyways, except given the circumstances I described above, which would be met by non-interactive mode.

> basically nvim and vim are no longer compatible and plugins must decide which programs idiosyncrasies they want to cater to. That is really unfortunate.

You did not want anything about Vim's input handling to change?

**Comment by SirVer** [comment]
> Are your tests sending meta-key chords?

No, they are not supported by Vim and my terminal emulator. 

> You did not want anything about Vim's input handling to change?

Yes, precisely. Changing the TUI seems like a dangerous approach to me. Add all the nice features you want into a GUI or a separate TUI that is stand alone from nvim core and represents a UI. But keep the default nvim TUI compatible. Now we have different behavior for non-ascii characters and chords to vanilla Vim which will and already is a PITA for plugin authors to support.

**Comment by Joushou** [comment]
Not being able to fix the TUI would leave us stuck with a broken TUI, and I find that to be much more horrible than having to do a bit of handling. I'd much rather sacrifice a bit of (potentially temporary - it could easily be fixed by a bit of redesign of the test suite) complexity on plugin test suites than I'd sacrifice the future of the NeoVIM TUI.

Honestly, I think your approach is wrong and implementation reliant. How to you test it on GUI vim? What about other clients?

I also think that what should have been a comprehensive unit test suite for ultisnips ended up being a comprehensive integration test suite. Integration tests aren't meant to test every line of code, but rather just see if whatever performs the integration glue is working as intended, while unit tests are meant to be where you go nuts. A unit test wouldn't need any UI reliant glue, and would generally be much less complicated than the test suite in question (4 retries for the tests?).

I'm not trying to hammer you down, but really - You're essentially saying that the TUI is not allowed to evolve. NeoVIM is about finally letting an editor that, despite being good, has been stuck for god knows how long finally get a chance to improve. If you ever tried doing multi-platform (Multiple OS's, compilers, or even browsers), you'd know that you're going to have a little bit of platform-specific code, which you usually abstract out of the way for convenience.

**Comment by SirVer** [comment]
>  I'd much rather sacrifice a bit of (potentially temporary - it could easily be fixed by a bit of redesign of the test suite) complexity on plugin test suites than I'd sacrifice the future of the NeoVIM TUI.

I can understand that, since that makes it somebody else's problem.

[testing]
We disagree here. Unit tests are useful during development (and UltiSnips has some for difficult parts or easy to test units). They help define and test corner cases and give an understanding of what a unit should do. They also make refactorings easier/safer. But giving confidence that a program actually works as advertised is given through integration testing. In my > 20 years as a professional developer I cannot remember once that a unit test discovered a bug after the unit was done. Integration tests do all the time though. Therefore, UltiSnips testsuite is meant to be a comprehensive integration test suite. Integration tests are messier and less elegant since they deal with the real world - alas that is were software is run though, so that is were you want to test. 

The best tests for UltiSnips would be to have a human type out all 500 test cases on all Vim variants I want to support all the time. Alas, I do not have the kind of budget, so using Tmux is second best to that: It emulates exactly that kind of test. 

> I'm not trying to hammer you down, but really - You're essentially saying that the TUI is not allowed to evolve. 

No, I am saying two things:
1) Neovim communicated to wanted to stay compatible with Vim to make plugins useful for both - but the TUI change isn't. If the decision to not be compatible with Vim has been made, why not go more aggressive and get rid of old cruft and really make a better editor and officially ditch the compatibility goal instead of violating it in the small.

2)  Given Neovim does not want to be compatible anyways, the TUI should have been split from the core. The TUI is an UI and should not be special to any other GUI. Given that route, a standalone GUI that emulates stock vim could have been kept around.

> If you ever tried doing multi-platform (Multiple OS's, compilers, or even browsers), you'd know that you're going to have a little bit of platform-specific code, which you usually abstract out of the way for convenience.

I do [tons of cross-platform](http://widelands.org) development and I am generally fine with dealing with the idiosyncrasies. This is different though: Neovim claims compatibility to Vim on the same platform (console, Linux), but that is not true anymore - it reacts different on the same input (unicode for example). 

> (I know that you hinted towards two TUI's, but that would just be an even greater PITA for NeoVIM devs than it would be to support the two TUI's for plugin devs)

The question is on who you put the workload I guess. Maybe the new TUI can be reworked to deal with the same input in the fashion too. In the meantime I try to work around the differences.

I appreciate your help so far in getting UltiSnips test suite to run again.

**Comment by Joushou** [comment]
### Rant

My experience may be shorter (Fun fact of the day: Your noted experience extends further than my experience in breathing!), and I understand your concern around unit tests. At work, we have *very* comprehensive integration tests, but from my personal experience, when an integration test breaks, it's usually because you're hitting code that we have not unit-tested (because it was old and dusty, or because someone was lazy during development and it managed to slip through a lazy reviewer). Our unit-tests trip all the time (For example, trying to fix a parser bug is likely to cause another, tripping a test), but due to them giving instant output locally, a failing unit-test never ends up making a trip to the CI system that performs the integration tests. In fact, I cannot remember any of my own cases of integration tests failing that were actually due to the integration tests themselves, rather than just the server component showing issues under high load conditions.

Sometimes, an integration test might also be testing something new and "absurd", which the unit-tests did not consider (100% line coverage does *not* mean 100% test coverage), but that's because the majority of the tests are developed by the test team, not the developers. Unit tests should definitely follow.

I do agree that integration tests are very important, and that they will find things that unit tests did not, but I also believe that if your integration tests are more comprehensive than your unit tests, then I think the test setup is inefficient. If you have proven the functionality of your individual components through unit testing, as well as proven that their interfaces live up to spec, then the integration test only becomes a test of whether the individual interfaces behave as a whole, and whether or not they have been used correctly. This means a test of every feature, but not a test of every feature in every possible combination, as that becomes completely unfeasible at the integration test level, due to the extreme amount of modifiable parameters.

I agree that outsourcing testing as manual labour would be more of a test, but that's not quite feasible, or even deterministic, for that matter. As someone who have worked with both good and bad testers, a lot of time ends up being wasted explaining to them why they can't just randomly change configuration files, especially when they have not understood what they're changing. Or how it actually *is* working, they're just having weird expectations. My personal favourite was an email with a screenshot that clearly showed the application having started up and being functional, with a note saying "application have not started".

NeoVim became incompatible with Vim in other ways long ago (configuration, for example), and while it has a "compatibility layer" for plugins, so that old plugins can be interacted with, I do not think it ever intended to provide any guarantees for UI's.

Again, if you only test the TUI, how do you guarantee the functionality of the GUI? Or for that sake all the other UI's that NeoVim opens up the possibility of using? I understand the convenience of being able to rely on a single interface for easy interaction, but relying on the specifics of keyboard input handling means to rely on something incredibly implementation specific, that is unrelated to the plugin functionality (but might of course affect user experience, not for this plugin, but for the entire application).

Maintaining an entire front-end is no easy task - It is a lot of code. And making an old front-end means making a blob of "dead" code (that needs bug-fixing, and updating to follow changing internals of NeoVim), only meant as a platform for odd automations expecting certain implementation details to hold true. It is *far* more work than a bit of test suite abstraction, which is basically just a slight adjustment in the Vim communication layer for your test suite. You'd be surprised at how many peculiarities that you need to handle when you need to support AIX, Solaris, Linux and Windows, but when abstracted away, no one notices (Except me, when changes need to be made).

However, development practices aside, even if it was written how I would have done it (I am not saying my way is the right way, I'm just airing personal opinions and experience here), there would still be some integration tests to perform. Hence, an actual suggestion (Sorry for the long rant!):

### Suggestion
I think the proper NeoVim way for doing this integration test, would be to talk to NeoVim through msgpack. This may not sound like a UX test, but doing UX testing on an old and unused TUI (which a forked "compatible" UI would end up being) is not useful anyway, as the extra UX guarantees it provides would not hold for the actually used UI's.

**Comment by tarruda** [comment]
@SirVer my goal is to make the new TUI as compatible as possible with Vim, the differences you see now are workarounds to some limitations with libtermkey which is still evolving its capabilities. The advantages of using a third party library for handling terminal input certainly outweights the incompatibilities caused by a few edge cases. While it still has some limitations, the code is now more cleanly separated and easier to maintain.

Even though libtermkey still does not  have the full capabilities of [`check_termcode`](https://github.com/vim/vim/blob/master/src/term.c#L3968-L5341),  I'd prefer to read and patch libtermkey rather than messing with that function, which is doomed to break when suffering minor changes.

**Comment by krisleech** [comment]
@bigeagle has a workaround here: https://github.com/neovim/neovim/issues/2035

> By setting `set -sg escape-time 0` in `.tmux.conf` can work around this problem.

So far it works well for me.

**Comment by SirVer** [comment]
@krisleech `esape-time` does not seem to make any difference for me with automated testing. I think nvim does some buffering itself.

**Comment by SirVer** [comment]
@joushou Kenny, I thought you might be interested: I [went with using `neovim.input`](https://github.com/SirVer/ultisnips/commit/306f0ace5f1a19aeaf4d3e5fa7eac43e6a41e036) for simulating key presses for testing UltiSnips with Neovim now. That is the solution that you suggested in https://github.com/neovim/neovim/issues/2454#issuecomment-102029264. 

That works reasonably well, but [needs some unexpected escaping of special keys](https://github.com/SirVer/ultisnips/commit/306f0ace5f1a19aeaf4d3e5fa7eac43e6a41e036#diff-7a86264bb76bdf27012dd0db1d9f48ceR182). 
It also introduces more fragility in timing since `neovim.input` is unbuffered, i.e. might be processed while Vim is still running UltiSnips logic. The buffered `neovim.feedkeys` unfortunately is sometimes not processed at all - for example when Vim is in `inputlist` waiting for user input, so that was no alternative.

All in all I am reasonable happy with this solution, assuming that `neovim.input` is indeed using the same code path as user key strokes - I did not check that, but that is how I understand the documentation.

**Comment by pjz** [comment]
I decided to try neovim just earlier today, but this is a dealbreaker for me.

I ran into this doing manual input: I have an idiosyncratic 'tic' where after escaping insert mode I *always* quickly hit 'kj' so that if I'm on a slow connection I can see that I've actually exited insert mode. (Old habit, deeply embedded in my fingers).  With neovim this means that I end up inserting ë and, just as importantly, not getting out of insert mode.  

I'm running neovim under screen under xfce4-terminal-emulator under i3wm, if it matters.

```
set ttimeout
set ttimeoutlen=0
```
...does *NOT* fix it for me.

I agree with @zachariahreed : If support of alt bindings is mutually exclusive with correct handling of fast typing, I don't see their inclusion as good a tradeoff.  At the very least there *must* be a way to switch that stuff off, as @tarruda suggested - I'd happily lose the ability to use some `Alt-` key combos if it meant I could gain back the ability to actually type normally.

**Comment by torpak** [comment]
why not just disable ALT- combos until libtermkey supports the needed feature?

**Comment by erikh** [comment]
Sorry to jump in here, but I was disappointed to realize that this bug is also preventing me from using vim. I realize this is a bug vs. feature situation but I would encourage you to consider the importance of the escape key in every day vim usage.

**Comment by justinmk** [comment]
@erikh what do you mean? Neovim handles the escape key more reliably than Vim. What use case is breaking for you?

**Comment by pjz** [comment]
It *doesn't* - it incorrectly interprets ESC,h,j,h typed quickly as some sort of Alt-key combination.  Vim doesn't have this problem.

**Comment by erikh** [comment]
It is most definitely an issue and it relates to how fast you hit the escape key. For example, typing something, waiting a second, then hitting escape will not trigger it. You must hit escape right away.

fwiw, this fixed my problem. seems to be that tmux is surfacing the issue. I cherry picked this from someone else:

```
set -sg escape-time 0
```

in tmux.conf fixes this for me without fail. I've been a happy neovim user for the last few days as a result.

Bugs happen but thanks for making a great tool.

**Comment by erikh** [comment]
Sorry to confuse; The bug is actually:

* enter tmux
* type something
* hit escape immediately
* start typing again (e.g., enter insert mode or really any  key works)

**Comment by justinmk** [comment]
It's a known issue:

https://github.com/neovim/neovim/wiki/Troubleshooting#pressing-esc-when-running-nvim-in-tmux-or-gnu-screen-inserts-characters

Not exactly the same as what this issue #2454 is concerned with.

**Comment by justinmk** [comment]
> With neovim this means that I end up inserting ë and, just as importantly, not getting out of insert mode.

After https://github.com/neovim/neovim/pull/3982 the ë won't be inserted, though you'll still be in insert mode if your tmux/screen timeout is not small enough.

**Comment by dead10ck** [comment]
Just want to chime in here that this issue is unfortunately making NeoVim unusable for me. I can't use it if I have to limit how fast I type.

**Comment by justinmk** [comment]
@dead10ck As mentioned in the comment immediately above your, any issue with _human_ input was fixed in https://github.com/neovim/neovim/pull/3982. However you didn't mention what symptoms you're seeing, or any other information, so I can only guess.

**Comment by dead10ck** [comment]
@justinmk I beg to differ; the change you linked to has been out since at least 0.1.4, which is what I'm running, and if I hit escape and then any other key too quickly, it doesn't register.

**Comment by justinmk** [comment]
@dead10ck Are you using tmux? Did you set `escape-time`? What are `'ttimeout'` and `'ttimeoutlen'` in Neovim? 

In Neovim, try `:set nottimeout`. Please note the **two t's**. 

If you are using tmux, `set-option -sg escape-time 2` should help. (Neovim has no control over tmux.)

**Comment by justinmk** [comment]
Also try `:set ttimeout ttimeoutlen=2`.

**Comment by dead10ck** [comment]
Nope, just from a shell. Ah, but setting `nottimeout` does appear to fix it. Thanks! I did see it mentioned above, but others commented that that did not fix it for them, and I am not using screen or tmux. Forgive me, for I am not that intimately familiar with what escape sequences are in the context of a shell or why they are necessary, but it seems strange to have to set this variable to get nvim working correctly.

**Comment by justinmk** [comment]
> but others commented that that did not fix it for them

Yeah, that was before https://github.com/neovim/neovim/pull/3982.

This has given me some ideas about improvements to these options, I'm going to work on it later today. The documentation also is very incomplete.

**Comment by justinmk** [comment]
> but it seems strange to have to set this variable to get nvim working correctly.

`nottimeout` is the default. Perhaps your migrated vimrc is setting it. We should warn about that in `:CheckHealth`.

**Comment by dead10ck** [comment]
@justinmk Oh, I see. Perhaps one of my plugins is setting it or something. Thanks for your help!

**Comment by rubenfonseca** [comment]
@dead10ck thanks for pointing out to vim-sensible! I was going crazy with this problem and didn't realize vim-sensible was overriding whatever my setting was!

**Comment by justinmk** [comment]
In 0.1.6, `:CheckHealth` gives a warning about sensible.vim: https://github.com/neovim/neovim/commit/fb4d5b05166235ae32db48cb7eb8d3776ea8386a

That's mostly a temporary measure; a full solution is to rework the way Nvim handles `'ttimeout[len]'`.

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim/pull/8226 , confirmed with:

    tmux new -s tmuxsession
    tmux send-keys -t tmuxsession "nvim -u NONE" Enter "iHi" Escape ':q!' Enter

@SirVer Can you try the [nightly build](https://github.com/neovim/neovim/releases/tag/nightly) with the ultisnips test suite? (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by SirVer** [comment]
@justinmk It seems to have improved somewhat, but I still see nvim freezing and getting stuck in insert mode when sending lots of text when running `./test_all.py --vim /root/nvim-linux64/bin/nvim`. 

To repro in UltiSnips: 

1. install docker
2. make image_repro
3. make repro
4. Inside the container shell you are dropped into, install nightly nvim into /root. Also do the vim -> nvim dance: https://neovim.io/doc/user/nvim.html#nvim-from-vim and pip install neovim:
   1. `cd && wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz`
   2. `tar xzvf nvim-linux64.tar.gz`
   3. `pip install neovim`
   4. 
~~~
mkdir -p ~/.config/nvim/ && cat > ~/.config/nvim/init.vim << EOF
set runtimepath^=~/.vim runtimepath+=~/.vim/after  
let &packpath = &runtimepath  
source ~/.vimrc 
EOF
~~~
   5. still in that shell, launch tmux: `tmux new -s vim`.
5. in another shell, run `make shell_in_repro`
6. Run the test suite using `./test_all.py --vim /root/nvim-linux64/bin/nvim` and wait till the Vim inside the tmux hangs. You can manually activate the vim instance, hit escape a few times and `:wq`, at which point the test runs again and passes.

**Comment by justinmk** [comment]
Can the ultisnips test suite be run without docker?

**Comment by SirVer** [comment]
@justinmk Yes, it is possible https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#running-the-test-suite. Of course the testing environment is not hermetic that way.
