### ISSUE TITLE
Attempting to delete a file named '\' in netrw recursively deletes file's parent directory

### ISSUE THREAD

**Issue by polluxcodes** [neovim/neovim#30664]
### Problem

Using netrw to delete a file named '\\' results in the recursive deletion of the file's parent directory.

### Steps to reproduce

```bash
# Setup
mkdir testdir
cd testdir
touch '\'

nvim --clean .
# Navigate to '\'
Dy

# Both '\' and 'testdir' are deleted
```

### Expected behavior

Only the file '\\' is deleted.

### Nvim version (nvim -v)

v0.10.2

### Vim (not Nvim) behaves the same?

no, vim 9.1.740

### Operating system/version

Linux 6.10.10

### Terminal name/version

kitty 0.36.4

### $TERM environment variable

xterm-kitty

### Installation

pacman

**Comment by zeertzjq** [comment]
Already fixed by #29838

**Comment by JonathanSteininger** [comment]
I am able to reproduce the issue on the master branch? 

Am I not understanding something with the build pipeline, or is this issue not actually resolved?

NeoVim Version: 
NVIM v0.11.0-dev-1423+g48c09ed4d9
Build type: RelWithDebInfo
LuaJIT 2.1.1734355927

**Comment by zeertzjq** [comment]
It's more likely that you didn't install Nvim properly.

**Comment by aaryanDhakal22** [comment]
I just accidentally deleted my entire $HOME directory while setting up a new system because for some reason deleting '\' from any directory deletes all the contents of the directory.
-- escape character to create the file named '\'
touch doNotDelete.c Maybedelete.js \\
nvim .
-- navigate to '\'
d
-- tries to delete everything recursively instead of just that file

Learned it the hard way.Had to setup the whole i3 from scratch.
