### ISSUE TITLE
The `jit.p` example in the Neovim documentation outputs nothing

### ISSUE THREAD

**Issue by ColinKennedy** [neovim/neovim#31091]
### Problem

It could be an issue on my side but `jit.p` in the Neovim documentation outputs nothing or `[No samples collected]`, depending on how it's called.

See `:help lua-profile`. It recommends `require('jit.p').start('ri1', '/tmp/profile')` followed by code and then `require('jit.p').stop()`. But the generated `'/tmp/profile'` is effectively empty

### Steps to reproduce

Make a file like

```lua
require('jit.p').start('ri1', '/tmp/profile')

local zone = require("jit.zone")
zone("testout")

local options = {}

for index=1,1 do
    vim.tbl_deep_extend("force", options, { {foo={another=8}} })
end

zone()

require('jit.p').stop()
```

Then run it with `nvim -l repro.lua`. The `'/tmp/profile'` contains `[No samples collected]`.

If you call the file with `nvim -c "luafile repro.lua"` then `'/tmp/profile'` has a chance of containing nothing.

### Expected behavior

Profile statistics included in the /tmp/profile file.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1075+gb34e137e43

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

 Ubuntu 22.04.3 LTS

### Terminal name/version

bash

### $TERM environment variable

screen-256color

### Installation

build from repo

**Comment by guilherme-batalheiro** [comment]
This issue is not a bug in Neovim but rather in LuaJIT, I have opened a [LuaJIT issue #1304](https://github.com/LuaJIT/LuaJIT/issues/1304) and also submitted a [pull request #1305](https://github.com/LuaJIT/LuaJIT/pull/1305) to address the problem in LuaJIT.

**Comment by ColinKennedy** [comment]
How do I test this new LuaJIT? I ran this

```
cd ~/repositories/neovim
git checkout master
git pull
make distclean
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
```

Then ran the above script with 

```
nvim -l reproduction.lua
cat /tmp/profile
```

And it still outputs ` [No samples collected]`. I'm guessing I'm still using the older LuaJIT, maybe?

`:version`
```
NVIM v0.11.0-dev-1157+g434d5936b6
Build type: RelWithDebInfo
LuaJIT 2.1.1731601260
Run ":verbose version" for more info
```

**Comment by clason** [comment]
No, that's the latest version with the fix. Looks like it wasn't enough.

@guilherme-batalheiro

**Comment by clason** [comment]
But keep in mind that this is a sampling profiler, so if the zone is short enough there's a chance that no samples are collected. In this case, the output is expected.

**Comment by clason** [comment]
(Or increase the workload; if you do 1000 iterations, I do get samples.)

**Comment by clason** [comment]
To be clear, what was fixed was this bug:
> If you call the file with nvim -c "luafile repro.lua" then '/tmp/profile' has a chance of containing nothing.

This
> Then run it with nvim -l repro.lua. The '/tmp/profile' contains [No samples collected].

is expected behavior.

> The output is super sparse even if I put a lot of real code (code that takes time to execute) in between the zone. I guess that's expected?

Yes, as I said, you need to tune the flags.  Personally, I've had reasonable experiences with `"10,i1,s,m0"` (add `G` to create a flamegraph for extra points) for reasonably complex workloads, but that was all but universal.

**Comment by ColinKennedy** [comment]
Understood now. WRT `nvim -c ...`, it appears to still not be working as expected. It only sometimes has output, still

```
$ nvim -c "luafile reproduction.lua"
$ cat /tmp/profile
$ nvim -c "luafile /home/selecaoone/temp/jit_loop_test.lua"
$ cat /tmp/profile
jit_loop_test.lua:0;get_attached_clients;get_clients 1
$ nvim -c "luafile /home/selecaoone/temp/jit_loop_test.lua"
$ cat /tmp/profile
$
```

and yes, I'm looking forward to that other PR too
