### ISSUE TITLE
lsp: semantic_tokens: allow pass `debounce` option when attaching client

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#32277]
### Problem

My lsp.log gets lots of messages similar to
```
[ERROR][2025-01-30 17:16:38] ...m/lsp/client.lua:624	"LSP[luals]"	"Cannot find request with id 52 whilst attempting to cancel"
[ERROR][2025-01-30 17:20:28] ...m/lsp/client.lua:624	"LSP[luals]"	"Cannot find request with id 80 whilst attempting to cancel"
[ERROR][2025-01-30 17:20:28] ...m/lsp/client.lua:624	"LSP[luals]"	"Cannot find request with id 82 whilst attempting to cancel"
```

With `print(debug.traceback())` at that line I see 
```
stack traceback:
	...uilds/from-src/share/nvim/runtime/lua/vim/lsp/client.lua:623: in function '_process_request'
	...uilds/from-src/share/nvim/runtime/lua/vim/lsp/client.lua:791: in function 'cancel_request'
	...m-src/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:276: in function 'send_request'
	...m-src/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:560: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
	...uilds/from-src/share/nvim/runtime/lua/vim/lsp/client.lua:623: in function '_process_request'
	...uilds/from-src/share/nvim/runtime/lua/vim/lsp/client.lua:791: in function 'cancel_request'
	...s/from-src/share/nvim/runtime/lua/vim/lsp/completion.lua:434: in function 'cancel'
	...s/from-src/share/nvim/runtime/lua/vim/lsp/completion.lua:43: in function 'cancel_pending'
	...s/from-src/share/nvim/runtime/lua/vim/lsp/completion.lua:442: in function 'trigger'
	...s/from-src/share/nvim/runtime/lua/vim/lsp/completion.lua:747: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
Let's focus on semantic tokens here. I guess that semantic token requests are sent too frequently when I typing in some cases and see that higher debounce option value can reduce such messages. 

### Expected behavior

It would be good to allow the user to adjust that debounce value when `lsp.semantic_tokens.start` is called inside `Client:on_attach()` especially when there is no better way to prevent from covering that condition.

https://github.com/neovim/neovim/blob/9cc060218b66c600f7f50ecbec5ba6f1b3a9da82/runtime/lua/vim/lsp/client.lua#L622-L627

**Comment by justinmk** [comment]
I've noticed this message too, and always with `req_type='cancel'`. It doesn't seem like we need to warn about a missing request if it was canceled? @lewis6991 I skipped the log message in https://github.com/neovim/neovim/pull/32294

**Comment by lewis6991** [comment]
I'd have to double check the spec, but I'm pretty sure all requests should receive a response. Only notifications do not receive a response. This error probably indicates a problem with the server or a bug somewhere else in our client.

**Comment by justinmk** [comment]
Hopefully resolved by: https://github.com/neovim/neovim/pull/33624

**Comment by przepompownia** [comment]
I still get thousands of such logs, although need a new reproduction, other than the example from https://github.com/neovim/neovim/discussions/33074

https://github.com/neovim/neovim/pull/34105 also does not fix that problem.

**Comment by AThePeanut4** [comment]
@przepompownia I didn't see your discussion when I made #34105, but it is identical to the fix you suggested. Are you sure it doesn't resolve #33074? That exact reproduction was what my PR was meant to fix.
