### ISSUE TITLE
Custom textobjects can cause unnecessary horizontal scroll

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#32966]
### Problem

Performing action on custom textobject (Operator-pending mapping which selects a text region, as per `:h omap-info`) can cause horizontal scroll when it is not needed. There is no obvious way to mitigate that (possibly except explicitly restoring window view which is excessive).

### Steps to reproduce

1. Create the following 'init.vim':
    ```vim
    set nocompatible
    set columns=191

    " Define several ways to select the same region
    function g:Select()
      let s:pos = getcurpos()
      call cursor(s:pos[1], s:pos[2] + 49)
      normal! v
      call cursor(s:pos[1], s:pos[2])
    endfunction

    onoremap io <Cmd>call g:Select()<CR>

    onoremap ik :<C-u>normal! 0f"lvt"<CR>
    onoremap iu vi"

    " Set state for reproduction. Maybe add more vertical splits if not enough.
    set nowrap
    call setline(1, 'abcdefghij"'.repeat('abcdefghij', 5).'"abcdefghij' )
    cal cursor(1, 12)

    wincmd v
    wincmd v
    wincmd v
    ```
2. `nvim --clean -u init.vim`
3. Type `cio`. Window is scrolled horizontally although it is not needed. The same happens if `cik` typed, **but** this doesn't happen if typed `ciu` (maps directly to built-in `vi"`) or `ci"` directly.

Notes:
- This doesn't seem to happen in Vim 9.1.1198.
- Adding `set lazyredraw` doesn't seem to help.
- The actual effect size seems to depend on actual window width and selected region: in some cases there is no scroll, in some - only by a single character.

Here is the demo (not quite zommed in because the effect is less prominent in that case):

https://github.com/user-attachments/assets/29666360-eb17-4aec-9ad0-b60ff4f50d98

### Expected behavior

No extra horizontal scroll in such cases.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-2033+g1369d86812

### Vim (not Nvim) behaves the same?

No, Vim 9.1.1198 behaves as expected

### Operating system/version

EndeavourOS Linux x86_64, 6.13.7-arch1-1

### Terminal name/version

Ghostty 1.1.2-arch2

### $TERM environment variable

xterm-ghostty

### Installation

appimage

**Comment by echasnovski** [comment]
After discussions with subject matter experts, the culprit here is the 'sidescroll' value: 1 reproduces this behavior while 0 does not. The difference in Neovim and Vim here is due to different default 'sidescroll' values: 1 in Neovim and 0 in Vim.

So I'll take it to vim/vim.

**Comment by justinmk** [comment]
was this fixed by https://github.com/neovim/neovim/pull/39961 ?

**Comment by echasnovski** [comment]
> was this fixed by [#39961](https://github.com/neovim/neovim/pull/39961) ?

I can still reproduce this issue on latest Nightly (`NVIM v0.13.0-dev-606+g3600d1c13c`). And I don't think #39961 was meant to solve this.

**Comment by zeertzjq** [comment]
Why is the horizontal scroll not needed? It clearly looks needed to me?

Also, what's the magic number 49 for?

**Comment by echasnovski** [comment]
> Why is the horizontal scroll not needed? It clearly looks needed to me?

Because:

1. The text after applying `io` and `ik` is the same as built-in `i"`, while the `iu` is essentially the same. The text fits into the available horizontal space, but for `io` and `ik` there is a scroll while `iu` and `i"` there is none.
2. The textobject that maps directly to the built-in `i"` (i.e. `iu` in this example) shows the intended behavior without horizontal scrolling. And as the output is essentially the same as the other two, I'd expect the other two to also behave the same. I.e. the cursor movement that is done during the Operator-pending mode should not result in horizontal scrolling.

> Also, what's the magic number 49 for?

To concisely mimic the behavior of `vi"` in Opertor-pending mode in this particular case. It moves cursor outside of the view. For it to work precisely, the amount of available horizontal space has to not be very large (I've updated the code to also include `set column=191`) or there has to be more vertical splits.

**Comment by echasnovski** [comment]
@zeertzjq, I'd ask for more elaborate reason than silent closing and "it is clearly not needed".

**Comment by zeertzjq** [comment]
If you move the cursor off the screen then obviously you get a scroll. What you need here is a way to set the other end of the visual selection without actually moving the cursor there.

**Comment by echasnovski** [comment]
> If you move the cursor off the screen then obviously you get a scroll. What you need here is a way to set the other end of the visual selection without actually moving the cursor there.

The difference is that the cursor is moved outside of view temporarily and only technically. The next redraw happens after applying the textobject and the final result doesn't require the scroll.

Setting visual selection without moving cursor might make it less of an issue, but I think won't fix it 100%. Mostly because the cursor must be on either end of the visual selection, so there might be scroll in the other direction if the left end is outside of view. Although it seems that `ci"` also leads to a scroll in this case.

**Comment by zeertzjq** [comment]
> The difference is that the cursor is moved outside of view temporarily and only technically.

It's not really "temporarily" if you are using `:normal` immediately after that, since Normal mode commands depends on the current viewport, so the scroll has to happen.
