### ISSUE TITLE
application gets suspended

### ISSUE THREAD

**Issue by dagi3d** [neovim/neovim#3320]
I was trying to see if the latest build of neovim was kind of ready for my daily work and I found that the app gets suspended when trying to use CtrlP. It also happened with Unite and the message I see is this `[1]  + 1009 suspended (tty input)  nvim`
If I type `fg` it returns to the editor but it becomes quite buggy like control sequences were not being properly sent and finally it crashes.

I also noted that if use a bash shell instead of zsh, the application is stopped instead of suspended: `[1]  + stopped nvim`
How could I see some logs to provide you more context about the error?

**Comment by dnmario** [comment]
Dear dagi3d,

The email sent to danielm@tinyhub.tk with subject
"[neovim] application gets suspended (#3320)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by tarruda** [comment]
Can you provide more info about your environment?(OS, terminal emulator, version...)

**Comment by dagi3d** [comment]
Ubuntu 14.04.1 running as VM with Vagrant/VirtualBox. ITerm 2(build 2.1.1). Using zsh as shell
neovim version:
```
NVIM 0.0.0-alpha+201509080123 (compiled Sep  8 2015 23:45:08)
Commit: dc9652e68de163290abee880a74bf1727c715a1e
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/vagrant/src/neovim/build/config -I/home/vagrant/src/neovim/src -I/home/vagrant/src/neovim/.deps/usr/include -I/home/vagrant/src/neovim/.deps/usr/include -I/home/vagrant/src/neovim/.deps/usr/include/luajit-2.0 -I/home/vagrant/src/neovim/.deps/usr/include -I/home/vagrant/src/neovim/.deps/usr/include -I/home/vagrant/src/neovim/.deps/usr/include -I/home/vagrant/src/neovim/.deps/usr/include -I/usr/include -I/home/vagrant
```

**Comment by dnmario** [comment]
Dear dagi3d,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] application gets suspended (#3320)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by tarruda** [comment]
@dagi3d what's the value of your $TERM variable from within nvim?(`:echo $TERM`)

**Comment by dagi3d** [comment]
screen-256color

**Comment by arzyu** [comment]
I encountered the same problem on Ubuntu 15.10.

This is my environment info.

```
NVIM 0.1.2-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-d10_5x/neovim-0.1.1ubuntu1+git201602040621+2228+16~ubuntu15.10.1/build/config -I/build/neovim-d10_5x/neovim-0.1.1ubuntu1+git201602040621+2228+16~ubuntu15.10.1/src -I/build/neovim-d10_5x/neovim-0.1.1ubuntu1+git201602040621+2228+16~ubuntu15.10.1/.deps/usr/include -I/build/neovim-d10_5x/neovim-0.1.1ubuntu1+git201602040621+2228+16~ubuntu15.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-d10_5x/neovim-0.1.1ubuntu1+git201602040621+2228+16~ubuntu15.10.1/.deps/usr/include -I/build/neovim-d10_5x/neovim-0.1.1ubuntu1+git201602040621+2228+16~ubuntu15.10.1/.deps/usr/include -I/build/neovim-d10_5x/neovim-0.1.1ubuntu1+git201602040621+2228+16~ubuntu15.10.1/.deps/usr/include -I/build/neovim-d10_5x/neovim-0.1.1ubuntu1+git201602040621+2228+16~ubuntu15.10.1/.deps/usr/include -I/usr/include -I/build/neovim-d10_5x/neovim-0.1.1ubuntu1+git201602040621+2228+16~ubuntu15.10.1/build/src/nvim/auto -I/build/neovim-d10_5x/neovim-0.1.1ubuntu1+git201602040621+2228+16~ubuntu15.10.1/build/include
Compiled by buildd@lgw01-05

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

```
$ echo $TERM
xterm-256color
```

**Comment by rockneverdies55** [comment]
I experienced the same problem in windows. I tried few different options from https://ci.appveyor.com/project/equalsraf/neovim (non wip ones especially) with ctrlpvim/ctrlp.vim plugin. However as soon as I press Ctrl+P, nyaovim exits immediately and neovim-qt says neovim crashed.

**Comment by justinmk** [comment]
There's wildly varying reports here (different OSes, different symptoms), with no information (we need a stacktrace if there was a crash). Since 0.1.2 it could have been fixed, or not. Please open a new issue with full details (stacktrace) if needed.

**Comment by dagi3d** [comment]
I tested it the latest precompiled version in Ubuntu(0.1.5-dev) and still happened.The thing is apparently I found the reason it was causing it and was the parameter shell, which was set to `shell=/bin/bash\ -i` 
I replace it with the zsh which is the shell I use but the problem still persisted. By removing it completely the problem went away

**Comment by justinmk** [comment]
Interactive shell (-i) will cause problems even in Vim.
