### ISSUE TITLE
NeoVim 0.11 appimage depends on newer glibc (GLIBC_2.34) than requirements (glibc >= 2.12)

### ISSUE THREAD

**Issue by jdye-bs** [neovim/neovim#33273]
### Problem

Using the 0.11 appimage on Debian Bullseye with glibc 2.31 results in the following error:
```
/tmp/.mount_nvimPHFAGd/usr/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_nvimPHFAGd/usr/bin/nvim)
/tmp/.mount_nvimPHFAGd/usr/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_nvimPHFAGd/usr/bin/nvim)
/tmp/.mount_nvimPHFAGd/usr/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_nvimPHFAGd/usr/bin/nvim)
```

```
>  ./nvim-linux-x86_64.appimage --appimage-extract
>  objdump -T squashfs-root/usr/bin/nvim | grep GLIBC | cut -c 50-61 | sort -n | uniq
GLIBC_2.10
GLIBC_2.12
GLIBC_2.14
GLIBC_2.17
GLIBC_2.2.5
GLIBC_2.28
GLIBC_2.29
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.32
GLIBC_2.33
GLIBC_2.3.4
GLIBC_2.34
GLIBC_2.4
GLIBC_2.6
GLIBC_2.7
GLIBC_2.9
```

I notice that it also depends on a few other things that have a version greater than 2.12 (as documented in the requirements).

### Steps to reproduce

1. Download nvim-linux-x86_64.appimage
2. Run chmod u+x nvim-linux-x86_64.appimage && ./nvim-linux-x86_64.appimage

### Expected behavior

Version 0.10 operates as expected (although it seems to depend on glibc2.29):

```
> objdump -T /tmp/.mount_nvimXI4LXX/usr/bin/nvim | grep GLIBC | cut -c 50-61 | sort -u
GLIBC_2.10
GLIBC_2.12
GLIBC_2.14
GLIBC_2.17
GLIBC_2.2.5
GLIBC_2.28
GLIBC_2.29
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.6
GLIBC_2.7
GLIBC_2.9
```

### Nvim version (nvim -v)

0.11

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Bullseye

### Terminal name/version

ssh

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
The requirements in support.txt refer to the source code, not the binaries.

**Comment by brianhuster** [comment]
This repo is for Nvim binaries for old platforms https://github.com/neovim/neovim-releases

**Comment by scy** [comment]
Thanks for clarifying that the version listed under [Supported Platforms](https://neovim.io/doc/user/support.html#supported-platforms) refers to build time, not runtime.

But, in that case: Where **can** I find the required glibc version? Because the [release page](https://github.com/neovim/neovim/releases/tag/v0.11.0) says, in the "Linux (x86_64)" section:

> If your system does not have the [required glibc version](https://neovim.io/doc/user/support.html#supported-platforms), try the (unsupported) [builds for older glibc](https://github.com/neovim/neovim-releases).

Note that "required glibc version" links to that same "supported platforms" section of the docs that you've just pointed out to be relevant for the source code only.

Three suggestions:

1. Don't link to the "supported platforms" section of the docs from the release page if it's not relevant for it at all.
2. List the actual required version on the release page, or link to somewhere people can find this information.
3. Add a note to "[supported platforms](https://neovim.io/doc/user/support.html#supported-platforms)" that emphasizes that these are the requirements for _building_ Neovim, not for running a binary release.

I'm using Linux for 20 years or something, and even I didn't see any indication that the requirements, linked from the release page, are irrelevant for the binary releases.

**Comment by dundargoc** [comment]
Fixed in https://github.com/neovim/neovim/pull/33093

**Comment by scy** [comment]
@dundargoc I'm sorry, but I've been reading the diff of #33093 and the only thing it fixes, unless I'm missing something, is suggestion # 1 from above:

> 1. Don't link to the "supported platforms" section of the docs from the release page if it's not relevant for it at all.

I still don't know which version of glibc I need to run the binary releas(es), and `support.txt` still has no indication that these are the requirements for _building_ Neovim, not _running_ binary releases.

**Comment by dundargoc** [comment]
> I still don't know which version of glibc I need to run the binary releas(es)

It will tell you when you which version you need when you run the binary if it's too low. We documented them before in the release notes but it leads to a lot of churn to keep updating it constantly. It didn't seem like it was worth it at the time. We could start re-adding the minimum versions to run the binaries if there is demand for it.

> and support.txt still has no indication that these are the requirements for building Neovim, not running binary releases.

It seemed kinda obvious to me, because `support.txt` is unrelated to the binaries.

Anyway, mind sending a PR to include the changes you want?

**Comment by scy** [comment]
> It will tell you when you which version you need when you run the binary if it's too low.

Does it?

```console
$ podman run --rm -it ubuntu:18.04
# { apt update && apt install -y curl; } &>/dev/null
# curl -sLO https://github.com/neovim/neovim/releases/download/v0.11.0/nvim-linux-x86_64.tar.gz
# tar -xf nvim-linux-x86_64.tar.gz
# ./nvim-linux-x86_64/bin/nvim -V
./nvim-linux-x86_64/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./nvim-linux-x86_64/bin/nvim)
./nvim-linux-x86_64/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./nvim-linux-x86_64/bin/nvim)
./nvim-linux-x86_64/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./nvim-linux-x86_64/bin/nvim)
./nvim-linux-x86_64/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./nvim-linux-x86_64/bin/nvim)
./nvim-linux-x86_64/bin/nvim: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./nvim-linux-x86_64/bin/nvim)
```

Similar issue when using the AppImage:

```console
$ podman run --rm -it --device /dev/fuse ubuntu:18.04
# { apt update && apt install -y curl fuse; } &>/dev/null
# curl -sLO https://github.com/neovim/neovim/releases/download/v0.11.0/nvim-linux-x86_64.appimage
# chmod 0755 nvim-linux-x86_64.appimage
# unshare -pfr --user --mount /bin/bash
# ./nvim-linux-x86_64.appimage -V
/tmp/.mount_nvim-lJHHOeJ/usr/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_nvim-lJHHOeJ/usr/bin/nvim)
/tmp/.mount_nvim-lJHHOeJ/usr/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_nvim-lJHHOeJ/usr/bin/nvim)
/tmp/.mount_nvim-lJHHOeJ/usr/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_nvim-lJHHOeJ/usr/bin/nvim)
/tmp/.mount_nvim-lJHHOeJ/usr/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_nvim-lJHHOeJ/usr/bin/nvim)
/tmp/.mount_nvim-lJHHOeJ/usr/bin/nvim: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_nvim-lJHHOeJ/usr/bin/nvim)
```

Does this mean I need 2.34 (because that's the highest one listed) or 2.28 (the lowest one listed, it's just probing for the others)? Or something else entirely?

> We documented them before in the release notes but it leads to a lot of churn to keep updating it constantly. It didn't seem like it was worth it at the time.

I totally understand that, and I'd probably agree with you if the error message was better. But as it is right now, even veterans are confused if they're not familiar with C development; beginners will probably have no idea what to do with this.

> We could start re-adding the minimum versions to run the binaries if there is demand for it.

Either that, or make the error more concise, or have a sentence or two on "what to do when you get `GLIBC_X.YY not found` errors" in the release notes.

> > and support.txt still has no indication that these are the requirements for building Neovim, not running binary releases.
> 
> It seemed kinda obvious to me tbh, because `support.txt` is unrelated to the binaries. I suppose it can't hurt to add a footnote in `support.txt` about this.

Yeah, now that the release notes no longer link to that file it's less of an issue, but I'd still probably suggest to add a footnote.

> Anyway, mind sending a PR to include the changes you want?

I can try, but I'm kinda busy right now and it's probably gonna take me a few days.

I wonder whether there's a way to determine the required glibc version in the GitHub Workflow run and inject it into the release notes Markdown dynamically. Would you be open to something like that? That way, nobody would need to keep it up to date manually.

**Comment by justinmk** [comment]
> determine the required glibc version in the GitHub Workflow run and inject it into the release notes Markdown dynamically. Would you be open to something like that?

yes

**Comment by KyleFontenot** [comment]
Ran into this issue. Wish it didn't waste my time because of incorrect documentation. 
Even if the release page mentions to use unsupported builds for older glib versions, its very fair for anyone to assume from the help docs (even with a provided link) in the Release page that using a supported build for their glibc version of 2.31 would work. That is wrong and misleading. 

> > and support.txt still has no indication that these are the requirements for building Neovim, not running binary releases.
> 
> It seemed kinda obvious to me tbh, because `support.txt` is unrelated to the binaries. I suppose it can't hurt to add a footnote in `support.txt` about this.

I'm not understanding how support.txt is unrelated to the binaries, and I'm not understanding how it is obvious. The requirements seem to be for binaries as well to me.  The directions say:
> #### Tarball
>1. Download nvim-linux-x86_64.tar.gz
> 2. Extract: tar xzvf nvim-linux-x86_64.tar.gz
> 3. Run ./nvim-linux-x86_64/bin/nvim

I'm on glibc 2.31 and cannot run that binary (./nvim-linux-x86_64/bin/nvim).  Trying to use [the unsupported builds ](https://github.com/neovim/neovim-releases/releases) does not even work because of glibc versions. The unsupported build .deb gives me :
```
dpkg: dependency problems prevent configuration of neovim:
 neovim depends on libc6 (>= 2.34); however:
  Version of libc6:amd64 on system is 2.31-0ubuntu9.18.
```

If `glibc >= 2.12 ` in support.txt is supposed to accurately reflect build requirements, to me it seems like an inaccurate use to include it in all of the built binaries. It makes more sense for support.txt to be about running the binaries, and a different doc in the source code to be for building.  support.txt is either misused and misleading or incorrect.



That Tarball instruction section in Installation should just be removed anyway. If it assumes the user knows what to do with the content inside the tarball, its fair to assume the existence of the download link for the tarball itself is clear enough, given its from the Releases page. Or go in a direction of actually guiding less-technical people in a "Installation" section.

**Comment by justinmk** [comment]
still waiting for the proposed CI patch: https://github.com/neovim/neovim/issues/33273#issuecomment-2799997419

**Comment by e-kwsm** [comment]
Sorry to jump in.
IIUC snap and flatpak resolve dependencies, so do they work in bullseye and other distros? Are they recommended over AppImage as it does not even support debian oldstable?

**Comment by justinmk** [comment]
> snap and flatpak ... Are they recommended over AppImage as it does not even support debian oldstable?

They are recommended on a "if it works for you, then great" basis. But, did you try extracting the appimage (mentioned in the [docs](https://github.com/neovim/neovim/blob/master/INSTALL.md#appimage-universal-linux-package) and the release page).

**Comment by scy** [comment]
> still waiting for the proposed CI patch: [#33273 (comment)](https://github.com/neovim/neovim/issues/33273#issuecomment-2799997419)

Sorry, my _"it's probably gonna take me a few days"_ was way too optimistic, life had other plans. I mean, I'll get to it _eventually_, but it's gonna be at least "weeks". If someone else wants to take this, I won't be mad. 😔

**Comment by bfredl** [comment]
> I'm not understanding how support.txt is unrelated to the binaries, and I'm not understanding how it is obvious. The requirements seem to be for binaries as well to me. 

> If glibc >= 2.12 in support.txt is supposed to accurately reflect build requirements, to me it seems like an inaccurate use to include it in all of the built binaries. It makes more sense for support.txt to be about running the binaries, and a different doc in the source code to be for building.

`support.txt` and all other `:help` docs is part of the runtime which is shared in _unmodified_ form across the source distribution, master branch binaries, neovim-release binaries and also online docs. Attempting to modifying these to befit each specific binary install would be both complicated and even more confusing (and an unnecessary papercut for cross-compiling).

Sounds simpler to just add a note that these are the `build time requirements`.

**Comment by e-kwsm** [comment]
> They are recommended on a "if it works for you, then great" basis. But, did you try extracting the appimage (mentioned in the [docs](https://github.com/neovim/neovim/blob/master/INSTALL.md#appimage-universal-linux-package) and the release page).

I am building neovim by myself and do not use appimage etc; I’m just curious portabilities of appimage, flatpak, and snap.

**Comment by justinmk** [comment]
If someone wants to make a concise documentation change, that's welcome. Else closing this because it's generating too much words for too little gain. Send a 1-line documentation change, else this is "wontfix".
