### ISSUE TITLE
completeopt+=fuzzy affects pageup/pagedown behavior in popupmenu

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#36697]
### Problem

When 'fuzzy' is set in &completeopt, pressing <pageup> in the popup menu moves the selection line by line, pagedown behaves similarly.

### Steps to reproduce

* `$ nvim --clean -u NONE +'set completeopt+=fuzzy`
* `<c-x><c-f>`
* `<pageup>`

### Expected behavior

pageup/pagedown moves page up/down.

### Nvim version (nvim -v)

0.11.5

### Vim (not Nvim) behaves the same?

no. VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Nov 12 2025 17:04:01)

### Operating system/version

archlinux

### Terminal name/version

alacritty 0.16.1

### $TERM environment variable

alacritty or tmux-256color

### Installation

pacman

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by haolian9** [comment]
in my test, the proroduce steps needs no more change. i recoreded a clip:

https://github.com/user-attachments/assets/d55664cf-4c42-4b76-9ba9-d94c05ef5306

**Comment by glepnir** [comment]
it select wrong item for me

**Comment by zeertzjq** [comment]
This is already fixed.

**Comment by glepnir** [comment]
~~emm I build with latest commit it works not correct even without fuzzy set~~ oh build is dirty ..

**Comment by haolian9** [comment]
i tried most recent commit of release-0.11 branch, and this issue remains.
so do you mind to tell me will the fix come to release-0.11 branch or nvim 0.11.6?

**Comment by zeertzjq** [comment]
No, it won't.
