### ISSUE TITLE
Can't clear register after recording in it

### ISSUE THREAD

**Issue by dirtybytes** [neovim/neovim#4444]
- Neovim version: 0.1.2
- Operating system: Arch Linux
- Terminal emulator: Gnome-Terminal
### Actual behaviour

Recorded sequence persists in a register after reopening neovim despite clearing it, even though it does get cleared for the current session.
### Expected behaviour

Register should stay empty after being cleared.
### Steps to reproduce
1. Type "qaaaaa<Esc>q"
2. Press "@a", watch "aaa" get inserted.
3. Press "qaq", then "@a" again.
4. Nothing happens, as is expected.
5. Close and open again neovim.
6. Press "@a", "aaa" gets inserted despite the register being cleared in the previous session.

":let @a=''" instead of "qaq" produces exactly the same bug. VIM version 7.4.1529 behaves correctly.

**Comment by ZyX-I** [comment]
Cleared registers are not distinguishable with registers which were empty from the beginning, thus when merging ShaDa file something has priority over nothing. AFAIR that was already discussed, but I failed to find the issue.

**Comment by justinmk** [comment]
@ZyX-I Does that also mean that https://github.com/neovim/neovim/issues/4295 is by design?

**Comment by ZyX-I** [comment]
That has the same reason.

**Comment by ZyX-I** [comment]
@dirtybytes BTW, you need to use backticks to escape code, *not* double quotes. By doing what you did you subscribed https://github.com/a to this issue while he has nothing to do with it.

**Comment by dirtybytes** [comment]
So, is there/will there be any other way to delete the contents of a register othen than editing the shada file by hand?

**Comment by justinmk** [comment]
@dirtybytes You can force the current Nvim instance state to write to the shada file by:

    :!wshada

This will lose data currently stored in the shada file. To workaround that, you can:

1. _read_ the shada file: `:rshada` (which will merge the two states),
2.  _perform the register deletion_, (`qaq`)
3. then _write_ the shada file: `:!wshada`

I haven't tested this, you can check if that solves your issue?

**Comment by dirtybytes** [comment]
It doesn't: the cursor positions in previously opened files are lost. Checked this twice. Using `:wshada` (without exclamation mark) instead just does nothing (nothing is overwritten, but the register also isn't deleted).

**Comment by justinmk** [comment]
> It doesn't: the cursor positions in previously opened files are lost.

You will need to `:rshada|wshada` in all of the other nvim instances, first, I think.

But isn't losing data the objective? :/

**Comment by dirtybytes** [comment]
It's not, I just need to clear one damn register, not nuke the whole shada file.
Also, isn't this a bug - the fact that `:rshada` `:wshada!` dismisses the previously stored cursor positions? In fact, it doesn't seem like `:rshada` is doing anything at all: if you had some recording in a register, and then clear it (with, say, `qaq`), and after that read shada file with `:rshada`, the register stays empty. So either it's a bug with `:rshada` command, or it's somehow possible to differentiate between an empty and unused register for when merging shada files, else the register would have been overwritten with the sequence you had stored in that register before opening nvim.
Sorry if that description is confusing, if you want, I can rephrase it. Also, could you reconsider labeling this as a bug rather than a design choice? It doesn't really make sense making a simple task of deleting a register so complicating.

**Comment by justinmk** [comment]
It's documented extensively in the help.

**Comment by wsdjeg** [comment]
@dirtybytes 
I can not reproduce this issue.and here is my reproduce step;and in the step of your first comment,you miss an `<esc>` before exit record.
1. start vim by `vim test.md`
2. type `qaatest<esc>q` ,then type `@a`,`test` is been inserted.
3. type `qaq` ,tyep `@a`,nothing will be inserted
4. type `:wq<cr>`
5. start vim again by `vim test.md`
6. type `@a`,nothing will be inserted

**Comment by ZyX-I** [comment]
@wsdjeg Steps to reproduce are missing exiting Neovim *before* clearing register.

**Comment by ZyX-I** [comment]
OP also missed this step.

**Comment by wsdjeg** [comment]
> Steps to reproduce are missing exiting Neovim before clearing register.

what step is missing?

**Comment by ZyX-I** [comment]
@wsdjeg “*Exiting Neovim* before clearing register.” It is a step.

**Comment by wsdjeg** [comment]
1. start vim by `vim test.md`
2. type `qaatest<esc>q` , `test` will be inserted
3. then type `@a`,`test` is been inserted again
4. type `:q!<cr>`
5. start vim by `vim test.md`
6. type `@a`, `test` will be inserted
7. type `qaq` ,tyep `@a`,nothing will be inserted
8. type `:q!<cr>`
9. start vim again by `vim test.md`
10. type `@a` still nothing will be inserted
here is all the step, sorry I can not find any bugs
6. type `@a`,nothing will be inserted

**Comment by ZyX-I** [comment]
@wsdjeg Why you are starting Vim? Vim does not bother itself with merging most of data, so, of course, it has this issue only with marks.

@dirtybytes I still do not remember where it was discussed (#4288 has no my replies), but AFAIR the main point was that marks have no “deleted” state and deleting mark is rather pointless and I am now not sure that registers were discussed at all. With current implementation one can simply store MCHAR (characterwise) empty register in a ShaDa file and this should work.

**Comment by wsdjeg** [comment]
@ZyX-I Oh my God,I am really sorry,but I have `alias vim='nvim'` in my bashrc

**Comment by dirtybytes** [comment]
@wsdjeg Followed the steps, reproduced the bug again. Whether or not other neovim instances are open makes no difference. Although the version I'm using is 0.1.2, so if you're using a newer version, perhaps it was already fixed.

**Comment by wsdjeg** [comment]
I build neovim from source,and it is the latest version,BTW my os is ubuntu 15.10,gnome-terminal 3.16.2

**Comment by keiviv** [comment]
This bug is still in the code — despite being more than 5 years old. Guess not many use registers, especially the a-z ones. 

For those who use, it's rather annoying. Clearing or deleting registers on startup introduces own set of problems in some cases. Plus it just doesn't feel right to begin a config of otherwise perfect program with  "-- Old nvim bug workaround".

Most annoying is that Vim does not have this bug. We would be very grateful if it's fixed ❤️.

**Comment by justinmk** [comment]
> Guess not many use registers, especially the a-z ones.

I use registers and shared state often. Never had a need to delete a register.

This will get fixed as soon as human spends time on it. Haven't seen a PR yet.

**Comment by n0099** [comment]
Did this fixed by https://github.com/neovim/neovim/pull/24936?

**Comment by zeertzjq** [comment]
No
