### ISSUE TITLE
mouse double-click and drag should select word by word

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#4754]
- Neovim version: 0.4.x ece19b459c082eae05b5c480f6ee91181f002c02
- Vim behaves differently? Vim version: VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  6 2014 14:32:04)
- Operating system/version: OS X 10.10.2
- Terminal name/version: iTerm 2
- `$TERM`: `xterm-256color`
### Actual behaviour

Double click, then drag to select word by word. In NeoVim, the selection starts with a word (if double clicked inside a word) but as soon as dragging starts then it selects character by character instead of word by word.
### Expected behaviour

While dragging, selection should continue to select word by word like in Vim.
### Steps to reproduce using `nvim -u NORC` and `vim -u NONE`

Run this before testing the mouse actions: 

``` viml
set mouse=a
```

**Comment by fujinuma** [comment]
ttymouse option has been removed from neovim (vim-differences) and mouse option defaults to a. btw, in which version of neovim did this occur? I couldn't reproduce it in master.

**Comment by trusktr** [comment]
@fujinuma 

```
~ ❯ /usr/local/bin/nvim --version
NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-
strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160401-8226-15d1eer/neovim-0.1.2/build/config -I/tmp/neovim20160401-8226-15d1eer/neov
im-0.1.2/src -I/tmp/neovim20160401-8226-15d1eer/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160401-8226-15d1eer/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160401-8226
-15d1eer/neovim-0.1.2/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160401-8226-15d1eer/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160401-8226-15d1eer/neovim-0.1.2/deps-b
uild/usr/include -I/tmp/neovim20160401-8226-15d1eer/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160401-8226-15d1eer/neovim-0.1.2/deps-build/usr/include -I/usr/local/opt/gette
xt/include -I/usr/include -I/usr/include -I/tmp/neovim20160401-8226-15d1eer/neovim-0.1.2/build/src/nvim/auto -I/tmp/neovim20160401-8226-15d1eer/neovim-0.1.2/build/include
Compiled by trusktr@Rosanas-Air.attlocal.net

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.2/share/nvim"
```

on Mac OS X

**Comment by apriendeau** [comment]
This occurring for me as well in this verison.

```
:version
NVIM v0.1.5-386-g999590b
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160606-26056-kkl
m6p/build/config -I/tmp/neovim-20160606-26056-kklm6p/src -I/tmp/neovim-20160606-26056-kklm6p/deps-build/usr/include -I/tmp/neovim-20160606-26056-kklm6p/deps-build/usr/include -I/tmp/neovim-20160606-26056-kklm6p/deps-build/usr/include -I/tmp/neovim-20160606-26056-kklm6p/deps-build/usr/include -I/tmp/neovim-20160606-26
056-kklm6p/deps-build/usr/include -I/tmp/neovim-20160606-26056-kklm6p/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim-20160606-26056-kklm6p/build/src/nvim/auto -I/tmp/
neovim-20160606-26056-kklm6p/build/include
Compiled by austin@Otter.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by apriendeau** [comment]
I think my issue was introduced with this commit and is seperate from the above issue https://github.com/neovim/neovim/commit/8958863e2678fd038ae089f837fa46d19574f977

**Comment by justinmk** [comment]
There were double-click improvements since this report. Should be fixed.

**Comment by trusktr** [comment]
@justinmk This was never fixed. It is still broken in the same way. I'm on version 0.2.0. Can you re-open?

**Comment by justinmk** [comment]
Works for me. The steps here aren't sufficient.

**Comment by lourenko** [comment]
Mine is broken in the same way. I'm on version 0.2.6. They just close non fixed bugs!

**Comment by lourenko** [comment]
Thanks. Now it is working.

**Comment by trusktr** [comment]
Doesn't seem to be fixed yet. I'm in NeoVim 0.3.1. I'm in Bash terminal in WSL.

**Comment by trusktr** [comment]
I'm not sure how to make better steps, but what I'm doing is in NORMAL mode I'm double clicking a word, and on the second click I keep the mouse button pressed, then drag the mouse to try to select word-by-word while dragging.

What happens is that a double click does initially select a whole word, but when I start to drag the mouse, it switches to selecting character-by-character.

**Comment by justinmk** [comment]
> double click does initially select a whole word, but when I start to drag the mouse, it switches to selecting character-by-character.

I can reproduce this in Nvim 0.4.x ece19b459c082eae05b5c480f6ee91181f002c02 with `:set mouse=a` and Terminal.app.

**Comment by Kommynct** [comment]
Yeah, I find this issue extremely annoying, is there any way to fix this at all?

**Comment by trusktr** [comment]
I've no experience with neovim source. Where in the source may this issue be found?
