### ISSUE TITLE
redraw: nvim 'disappears' on tmux split

### ISSUE THREAD

**Issue by mikeys** [neovim/neovim#4884]
- `nvim --version`: NVIM 0.1.4
- Vim (version: 7.3) behaves differently? Yes, the same bug doesn't occur in vim 7.3
- Operating system/version: OSX 10.11.3 (El Capitan)
- Terminal name/version: oh-my-zsh (zsh 5.0.8) + tmux 2.2
- `$TERM`: screen-256color
### Actual behaviour

As can be seen in the animated gif below, when I split the active nvim pane, nvim disappears completely.
It shows up again either by focusing on the nvim pane again or by `exit`ing the new pane session (as can be seen below).

When I disable the `vim-airline` plugin (by commenting it out in my `.vimrc` file) everything works fine.

Also, as mentioned above, the same does not occur on regular Vim 7.3.

![nvim-tmux-bug](https://cloud.githubusercontent.com/assets/1187953/15819047/75ce1ea0-2be9-11e6-89c3-2b95b6e49bdb.gif)

**Comment by justinmk** [comment]
If you focus back and press CTRL-L, it should "re-appear". It's a known redraw bug.

**Comment by mikeys** [comment]
@justinmk thanks for the answer. It actually re-appears even without pressing CTRL-L, when focusing backing. Was just wondering if there's a solution for this bug at the moment.

**Comment by zchee** [comment]
@mikeys I wonder because I do not reproduce in the same environment(only `$TERM=xterm-256color`).
but, Do `FocusGained` or `FocusLost` works effectively against it?

like `autocmd! FocusLost * redraw`

**Comment by lewis6991** [comment]
I'm seeing the same bug and the redraw autocmd doesn't seem to have any effect.

**Comment by szymonkaliski** [comment]
I can confirm, same issue, autocmd doesn't help.

**Comment by justinmk** [comment]
I can reproduce this without airline. When it happens, any eval will draw the screen.

**Comment by pbogut** [comment]
I'm experiencing the same bug without tmux but with i3 instead. Same scenario:
  - Start nvim
  - Start new window in split (any app)
  - Nvim window becomes blank

**Comment by phanimahesh** [comment]
Unable to reproduce with `nvim -u NONE` with terminals gnome-terminal, rxvt and tmux & i3 splits
(tested all four combinations)

Using nvim 0.1.5, Release build from nix (`/nix/store/v2v7kb66hlr9yjl30p1nbn5m6zf6z1ys-neovim-0.1.5`)

**Comment by lewis6991** [comment]
I am also no longer seeing the issue after compiling from HEAD.

**Comment by justinmk** [comment]
#4972 May have changed the behavior. But I'm still able to reproduce this reliably using certain steps with `:Dispatch`. I'll see if I can narrow it down.

**Comment by ruipgpinheiro** [comment]
I can still reproduce it as long as I have vim-airline active. With it disabled (or with nvim -u NONE) it seems to be working fine.

**Comment by tweekmonster** [comment]
I'm able to reproduce this, but not with `-u NONE`.  It looks like it has something to do with timing.

This will work *sometimes*:

```vim
function! s:redraw() abort
  redraw
  echomsg 'redrawing'
endfunction

autocmd! FocusLost * call timer_start(5000, function('s:redraw'))
```

But, the times where it doesn't work, the pane with nvim stays blank.  When I switch back to nvim, the screen comes back, but the `redrawing` message appears 5 seconds after.

Then there's this:

```vim
function! s:redraw() abort
  sleep 5
  redraw
  echomsg 'redrawing'
endfunction

autocmd! FocusLost * call s:redraw()
```

Splitting the pane will either blank the screen or the screen will remain but all statuslines are completely blanked out (void space, not "no text").  When I switch back to nvim, the sleep resumes and I can't interact for 5 seconds.

It seems like something is suspending nvim, but only when I split a pane at a certain time.  If I'm lucky and split at the right time, both of the scripts above work and the screen redraws 5 seconds after splitting a pane.

**Comment by attilastrba** [comment]
I am using neovim with terminology and have the same issue but only if vim-airline is active. If airline is disabled than this does not happen.

**Comment by cHoco** [comment]
Such a coincidence, I opened an issue on the tmux side https://github.com/tmux/tmux/issues/595 and just now I noticed this issue here.
At least in my case, this is only reproducible when I have `focus-events` turned on in tmux.conf, so maybe neovim has issues handling a focuslost plus a resize at the same time causing this weird blank redraw. But I'm not sure it is only that because I can also reproduce something similar when switching windows in tmux and I don't think that triggers a resize.

**Comment by raichoo** [comment]
I also have redraw issues when toggling full-screen mode in Gnome 3, issuing `:redraw` does not fix the problem. Turning of `airline` seems to work around it though.

**Comment by justinmk** [comment]
Ctrl-L should fix it, rather than `:redraw`.

**Comment by raichoo** [comment]
`Ctrl-L` also does not have any effect.

**Comment by pbogut** [comment]
For me,  its not happening so often  without the airlines but it still happens.

**Comment by raichoo** [comment]
For me the problem seems to be fixed with `0f32088ea23fbbe9557c89a9e075f2e9b9e158a4`.

**Comment by pbogut** [comment]
Version: NVIM v0.1.6-300-g0f32088
Problem still exists.

**Comment by raichoo** [comment]
I stand corrected, the problem persists.

**Comment by justinmk** [comment]
@raichoo since you're around, can you confirm https://github.com/neovim/neovim/issues/3875 ?

**Comment by kudomo** [comment]
I'm also affected by this, is there any progress? I've tried taking a look at this during the weekend but couldn't figure out the issue....
It's such a small thing but it really ruins my workflow :(

**Comment by justinmk** [comment]
I started to take a look at this a couple days ago. The problem is caused by an incomplete redraw when nvim handles focus gained/lost event. I'll have at least an ugly fix, soon.

**Comment by beanaroo** [comment]
Today I disabled `focus-events` in tmux and it appears to work. I must admit, I actually got used to this behaviour without realizing.

**Comment by pbogut** [comment]
I'm not using tmux and problem still exists. Additionally, form time to time nvim freezes permamently when I create new splits in i3wm.

**Comment by justinmk** [comment]
@pbogut `:mode` or CTRL-L does not "un-freeze" nvim in those cases?

**Comment by pbogut** [comment]
Nope, can't even ctrl-c. I have to kill terminal when it happens.

**Comment by ismay** [comment]
> Today I disabled focus-events in tmux and it appears to work. I must admit, I actually got used to this behaviour without realizing.

Nice fix, but still, not a long term solution. Focus events is necessary for other stuff to work. Would be nice if this could be fixed.

**Comment by choco** [comment]
Have you guys tried to disable `lazyredraw`? So @justinmk can get some feedback on https://github.com/neovim/neovim/issues/6259

**Comment by ismay** [comment]
@choco Yeah that fixes it as well (for me at least).

**Comment by pbogut** [comment]
I didn't know that this is related to `lazyredraw`, I'm living with this issue for a long time now.
With lazyredraw disabled I can't reproduce this error anymore.

**Comment by beanaroo** [comment]
@ismay, agreed. I have some autocommands that rely on focus events.

@choco Thanks, but I have been using `lazyredraw` with no effect to this problem.

**Comment by choco** [comment]
@beanaroo I was actually suggesting to disable `lazyredraw` and check if that fixes it, since that's probably the culprit blocking the redraw on resize. If the issue is resolved for everyone when disabling it I think it's worth merging the PR above, even though it's kinda an hack.

**Comment by szymonkaliski** [comment]
I can also confirm that with focus-events enabled, and `lazyredraw` disabled, the issue goes away!

**Comment by cento** [comment]
@szymonkaliski with focus-events enabled and `lazyredraw` disabled, I still have the problem. I also tried using `-u NONE`. Same configuration, neovim has the problem, vim not.

**Comment by wayneashleyberry** [comment]
Still happening for me regardless of `lazyredraw` or `focus-events`.

**Comment by kutsan** [comment]
My version is 0.2.0 and I am still having this problem.

**Comment by justinmk** [comment]
The fix is on master, not 0.2.0.

**Comment by kutsan** [comment]
@justinmk Ops, I am so sorry to disturb.
