### ISSUE TITLE
Neovim is extremly slow with folding and python (GetPythonIndent)

### ISSUE THREAD

**Issue by petRUShka** [neovim/neovim#5055]
- `nvim --version`:
  NVIM 0.1.4

```
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic 
-Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.4/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include                                                                                                                                              Compiled by builduser
```
- Vim (version: ) behaves differently
  VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  9 2016 09:35:51)
  Included patches: 1-1910
  Compiled by Arch Linux
- Operating system/version: Arch Linux
- Terminal name/version: xterm
- `$TERM`:

There is a quite big python file. And `set foldmethod=indent`. So all folds are closed. In normal mode I press `O` (new line above current position). It takes 2-3 seconds with NeoVIM and 0.23 seconds in VIM! (same file, same vimrc and etc) 

Something makes neovim really slow in that case.

Profile Neovim (full version: https://gist.github.com/e9bc33edabc6be8d1d8d72b42108ae21)

```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1              2.569670  GetPythonIndent()
```

Profile VIM (full version: https://gist.github.com/2d62c91b954dc8c787acd5e3dd906b57)

```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1              0.252513  GetPythonIndent()
```

**Comment by jamessan** [comment]
The indent script itself hasn't changed between Vim and Neovim, so it appears likely to be some optimizations in the C side that we haven't merged over yet.

The time seems to be spent in `searchpair()`.

Neovim:

    1              1.398612   let parlnum = searchpair('(\|{\|\[', '', ')\|}\|\]', 'nbW', "line('.') < " . (plnum - s:maxoff) . " ? dummy :" . " synIDattr(synID(line('.'), col('.'), 1), 'name')" . " =~ '\\(Comment\\|Todo\\|String\\)$'")

Vim:

    1              0.147579   let parlnum = searchpair('(\|{\|\[', '', ')\|}\|\]', 'nbW', "line('.') < " . (plnum - s:maxoff) . " ? dummy :" . " synIDattr(synID(line('.'), col('.'), 1), 'name')" . " =~ '\\(Comment\\|Todo\\|String\\)$'")

**Comment by justinmk** [comment]
@petRUShka Any chance you could try master?

**Comment by petRUShka** [comment]
I've just compiled neovim from master with [neovim-git](https://aur.archlinux.org/packages/neovim-git/) arch linux aur package. Current version is NVIM v0.1.5-614-g72ad5a1

```
Build type: Dev
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/yaourt-tmp-petrunin/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-petrunin/aur-neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/yaourt-tmp-petrunin/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-petrunin/aur-neovim-git/src/neovim-git/build/include
```

Unfortunately it is still very slow:

`1              2.037616  GetPythonIndent()`

New profile.log: https://gist.github.com/10b72fe68bccb0227cdea52c2d6b228e

P.S. In my tests sometimes (but definitely not always) neovim runs `O` quite fast (according to my feelings). But every time I enable profiling it  became as slow as in `profile.log`.

**Comment by jamessan** [comment]
Do you have a sample Python file you can provide along with __exact__ steps to reproduce the slowness?  The testing I've done on some local Python files I have don't show this sort of performance issue.

Also, can you show the output from the below command?

```vim
:echo filter(g:, 'v:key =~ "pyindent"')
```

**Comment by KillTheMule** [comment]
I'm just looking at the differences of `do_searchpair`. Is your vim compiled with `FEAT_RELTIME`?

**Comment by petRUShka** [comment]
@KillTheMule , I think it isn't. 

My `vim --version`: https://gist.github.com/anonymous/a2dd1a3e7ac6cee24c1c78456a7884fd

**Comment by petRUShka** [comment]
@jamessan , I'll try to crate one!

**Comment by KillTheMule** [comment]
> @KillTheMule , I think it isn't.
> 
> My vim --version: https://gist.github.com/anonymous/a2dd1a3e7ac6cee24c1c78456a7884fd

Can't read gists at work, but that looked like the only real difference of `do_searchpair` between vim an neovim. Steps would definitely help to reproduce, see if that vim compile option does something here.

**Comment by petRUShka** [comment]
@KillTheMule , I extract content of the gist for you:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  9 2016 09:35:51)
Included patches: 1-1910
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl/dyn
+browse          +folding         +mouse_xterm     +termguicolors
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+channel         +gettext         -mzscheme        +textobjects
+cindent         -hangul_input    +netbeans_intg   +timers
+clientserver    +iconv           +packages        +title
+clipboard       +insert_expand   +path_extra      +toolbar
+cmdline_compl   +job             +perl/dyn        +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -lncurses -lelf -lnsl -lacl -lattr -lgpm -ldl -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm 
```

**Comment by petRUShka** [comment]
Yes, there is `+reltime` compile option.

**Comment by ThaHypnotoad** [comment]
I just started noticing a nearly identical issue on 1.5. It seems to happen particularly when the cursor is below a particularly long line of code (long in this case meaning something like this:
`TopEdge = np.row_stack((np.random.uniform(rangeX[0],rangeX[1],number/4),np.random.normal(rangeY[0],stdev,number/4), np.ones(number/4)))
`
it seems that each line similar to this one causes an incremental delay in the amount of time it takes to create a newline. The further the cursor is from the long lines, the smaller the delay.

Was this issue resolved? Is my observation better placed as it's own issue?

**Comment by jamessan** [comment]
Is `'synmaxcol'` set to the same value in vim and nvim?

@ThaHypnotoad In your case, could you post comparisons of the below between vim and nvim?  Open the file and navigate to where the performance is observed to be particularly bad and then run these commands.

```vim
:syntime on
:redraw
:syntime report
```

**Comment by ThaHypnotoad** [comment]
Here it is, vim then nvim. 
[vim diags.txt](https://github.com/neovim/neovim/files/380585/vim.diags.txt)

:
`  TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  0.003177   261    0       0.000030    0.000012  pythonString       [uU]\=\z('''\|"""\)
  0.002693   261    0       0.000029    0.000010  pythonString       [uU]\=\z(['"]\)
  0.002606   261    0       0.000025    0.000010  pythonNumber       \%(^\|\W\)\zs\d*\.\d\+\%([eE][+-]\=\d\+\)\=[jJ]\=\>
  0.002306   261    0       0.000026    0.000009  pythonRawString    [uU]\=[rR]\z('''\|"""\)
  0.002179   261    0       0.000022    0.000008  pythonRawString    [uU]\=[rR]\z(['"]\)
  0.001845   876    757     0.000015    0.000002  pythonNumber       \<\%([1-9]\d*\|0\)[Ll]\=\>
  0.001663   261    0       0.000019    0.000006  pythonNumber       \<\d\+\.\%([eE][+-]\=\d\+\)\=[jJ]\=\%(\W\|$\)\@=
  0.001660   261    0       0.000020    0.000006  pythonNumber       \<\d\+[eE][+-]\=\d\+[jJ]\=\>
  0.001624   261    0       0.000021    0.000006  pythonNumber       \<\d\+[jJ]\>
  0.000210   271    33      0.000007    0.000001  pythonComment      #.*$
  0.000202   1018   908     0.000001    0.000000  level13            (
  0.000176   261    0       0.000002    0.000001  pythonNumber       \<0[oO]\=\o\+[Ll]\=\>
  0.000170   858    858     0.000011    0.000000  level14            )
  0.000164   261    0       0.000002    0.000001  pythonNumber       \<0[bB][01]\+[Ll]\=\>
  0.000158   261    0       0.000002    0.000001  pythonNumber       \<0[xX]\x\+[Ll]\=\>
  0.000146   792    682     0.000001    0.000000  level9             (
  0.000140   792    682     0.000009    0.000000  level2             (
  0.000139   792    682     0.000009    0.000000  level11            (
  0.000138   792    682     0.000001    0.000000  level10            (
  0.000135   792    682     0.000001    0.000000  level3             (
  0.000134   792    682     0.000003    0.000000  level7             (
  0.000133   792    682     0.000001    0.000000  level1             (
  0.000133   792    682     0.000001    0.000000  level6             (
  0.000129   792    682     0.000001    0.000000  level12            (
  0.000128   792    682     0.000001    0.000000  level4             (
  0.000123   700    622     0.000001    0.000000  level14            (
  0.000122   792    682     0.000001    0.000000  level8             (
  0.000121   16     16      0.000027    0.000008  pythonFunction     \%(\%(def\s\|class\s\|@\)\s*\)\@<=\h\%(\w\|\.\)*
  0.000117   488    488     0.000010    0.000000  level16            )
  0.000116   792    682     0.000001    0.000000  level5             (
  0.000101   470    470     0.000009    0.000000  level15            )
  0.000093   261    0       0.000001    0.000000  pythonDecorator    @
  0.000093   261    0       0.000001    0.000000  pythonEscape       \\$
  0.000068   452    384     0.000001    0.000000  level15            (
  0.000064   355    303     0.000001    0.000000  level16            (

  0.023206   18401
'

----------NVIM----------------

`TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  1.401183   1187   101     0.003418    0.001180  pythonFunction     \%(\%(def\s\|class\s\|@\)\s*\)\@<=\h\%(\w\|\.\)*
  0.018171   1501   1       0.000044    0.000012  pythonString       [uU]\=\z('''\|"""\)
  0.015729   1501   0       0.000039    0.000010  pythonNumber       \%(^\|\W\)\zs\d*\.\d\+\%([eE][+-]\=\d\+\)\=[jJ]\=\>
  0.015392   1501   1       0.000050    0.000010  pythonString       [uU]\=\z(['"]\)
  0.012952   1501   0       0.000033    0.000009  pythonRawString    [uU]\=[rR]\z('''\|"""\)
  0.012515   14140  13378   0.000015    0.000001  pythonAttribute    \.\h\w*
  0.012383   1501   0       0.000033    0.000008  pythonRawString    [uU]\=[rR]\z(['"]\)
  0.010720   5099   4417    0.000018    0.000002  pythonNumber       \<\%([1-9]\d*\|0\)[Ll]\=\>
  0.010012   1501   0       0.000025    0.000007  pythonNumber       \<\d\+\.\%([eE][+-]\=\d\+\)\=[jJ]\=\%(\W\|$\)\@=
  0.009060   1501   0       0.000028    0.000006  pythonNumber       \<\d\+[eE][+-]\=\d\+[jJ]\=\>
  0.008916   1501   0       0.000026    0.000006  pythonNumber       \<\d\+[jJ]\>
  0.001914   10536  10267   0.000013    0.000000  level16            (
  0.001296   1577   223     0.000019    0.000001  pythonComment      #.*$
  0.001201   5292   5292    0.000011    0.000000  level15            )
  0.001167   6053   5435    0.000013    0.000000  level13            (
  0.001086   1501   0       0.000010    0.000001  pythonNumber       \<0[bB][01]\+[Ll]\=\>
  0.001046   6608   6187    0.000011    0.000000  level14            (
  0.001000   1501   0       0.000011    0.000001  pythonNumber       \<0[oO]\=\o\+[Ll]\=\>
  0.000943   1501   0       0.000011    0.000001  pythonNumber       \<0[xX]\x\+[Ll]\=\>
  0.000923   5213   5213    0.000012    0.000000  level14            )
  0.000849   4682   4064    0.000013    0.000000  level12            (
  0.000822   4682   4064    0.000011    0.000000  level11            (
  0.000822   4682   4064    0.000010    0.000000  level6             (
  0.000820   4682   4064    0.000012    0.000000  level2             (
  0.000813   4682   4064    0.000010    0.000000  level4             (
  0.000813   4682   4064    0.000009    0.000000  level9             (
  0.000813   4682   4064    0.000009    0.000000  level8             (
  0.000805   4682   4064    0.000009    0.000000  level5             (
  0.000804   4682   4064    0.000003    0.000000  level1             (
  0.000803   4682   4064    0.000009    0.000000  level10            (
  0.000800   4682   4064    0.000002    0.000000  level7             (
  0.000800   4682   4064    0.000009    0.000000  level3             (
  0.000694   4040   3682    0.000013    0.000000  level15            (
  0.000674   2851   2851    0.000010    0.000000  level16            )
  0.000574   1504   0       0.000011    0.000000  pythonEscape       \\$
  0.000537   1501   0       0.000011    0.000000  pythonDecorator    @
  0.000443   1089   0       0.000012    0.000000  pythonEscape       \\N{\a\+\%(\s\a\+\)*}
  0.000420   1089   0       0.000010    0.000000  pythonEscape       \%(\\u\x\{4}\|\\U\x\{8}\)
  0.000414   1089   0       0.000011    0.000000  pythonEscape       \\[abfnrtv'"\\]
  0.000405   1089   0       0.000011    0.000000  pythonEscape       \\\o\{1,3}
  0.000385   1089   0       0.000002    0.000000  pythonEscape       \\x\x\{2}
  0.000068   1089   0       0.000002    0.000000  pythonDoctest      ^\s*>>>\s
  0.000057   1086   0       0.000000    0.000000  pythonDoctestValue ^\s*\%(>>>\s\|\.\.\.\s\|"""\|'''\)\@!\S\+
  0.000012   5      1       0.000003    0.000002  pythonString       \z1
  0.000000   1      0       0.000000    0.000000  pythonString       \\["']

  1.552056   145922
`

**Comment by jamessan** [comment]
Hmm, everything's nearly identical except for pythonFunction -- `\%(\%(def\s|class\s|@)\s)\@<=\h\%(\w|.)`

By any chance, does `:set re?` show different values in vim and nvim?

**Comment by ThaHypnotoad** [comment]
they are both set to zero. Also, never used the syntime utility ever. Really neat.

**Comment by ThaHypnotoad** [comment]
This is my vimrc by the way. I thought that putting too many plugins mighthave been the cause, but after commenting them all out the issue persists.

`set nocompatible

call plug#begin('~/.vim/plugged')

"Plug 'https://github.com/Valloric/YouCompleteMe.git'
Plug 'https://github.com/scrooloose/nerdtree.git'
Plug 'https://github.com/scrooloose/syntastic.git'
Plug 'https://github.com/tpope/vim-dispatch.git'
Plug 'https://github.com/tpope/vim-fugitive.git'
""Plug 'https://github.com/davidhalter/jedi-vim.git'
"Plug 'https://github.com/rdnetto/YCM-Generator.git'
Plug 'https://github.com/kien/rainbow_parentheses.vim.git'
Plug 'https://github.com/jiangmiao/auto-pairs.git'
Plug 'https://github.com/ctrlpvim/ctrlp.vim.git'
Plug 'https://github.com/Shougo/deoplete.nvim.git'
Plug 'https://github.com/zchee/deoplete-jedi.git'
Plug 'https://github.com/zchee/deoplete-clang.git'
Plug 'scrooloose/nerdcommenter'
Plug 'https://github.com/fboender/bexec.git'
call plug#end()
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#clang#libclang_path = "/usr/lib/llvm-3.8/lib/libclang.so.1"
let g:deoplete#sources#clang#clang_header = "/usr/include/clang/3.8.1/include/"
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
filetype plugin indent on

syntax on
set number
set backspace=2
set clipboard=unnamedplus
set mouse=a

set noexpandtab
set copyindent
set preserveindent
set softtabstop=0
set shiftwidth=4
set tabstop=4

au VimEnter * RainbowParenthesesToggle

hi Comment ctermfg=LightBlue
hi Directory ctermfg=LightBlue

"autocmd FileType python nnoremap <buffer> <F9> :exec '!clear; python' shellescape(@%, 1)<cr>
"autocmd FileType cuda set ft=c.cuda
set whichwrap+=<,>,h,l,[,]
`

**Comment by KillTheMule** [comment]
> Hmm, everything's nearly identical except for pythonFunction -- \%(\%(def\s|class\s|@)\s)\@<=\h\%(\w|.)

Did you notice COUNT and MATCH are different for nvim, too? Is that expected?

**Comment by jamessan** [comment]
> Did you notice COUNT and MATCH are different for nvim, too?

Yes, but the average time per call for pythonFunction is 100x worse for nvim.

**Comment by ThaHypnotoad** [comment]
interestingly this is not an issue on my other machine. Same files, same vimrc. Other than being a mac, it's running the homebrew neovim, which is version 1.4 instead of 1.5-dev. As soon as I get home I'm going to try using the older version on my other computer.

**Comment by ThaHypnotoad** [comment]
Speaking of, is there a way to install a different version without building from source? the apt repo only has the current version.

**Comment by ThaHypnotoad** [comment]
Any response regarding my last question? I've been mostly working on my other machine, but issues like this really get under my skin, so I was hoping to resolve it.

**Comment by jamessan** [comment]
There are [instructions] for using the PPA, which gets built daily.

[instructions]: https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu

**Comment by ThaHypnotoad** [comment]
Yes. I've installed from the PPA, however apt-cache shows that there is only one version on the PPA. and that is 1.4 (which strangely enough shows up as 1.5-dev when I run nvim --version)

I was wondering if y'all had set up a different method of allowing older versions to be installed, because the PPA has only the latest one.

**Comment by jamessan** [comment]
You can try installing Debian's [experimental] package.  I'm hoping to get it into unstable soon, but I need to get msgpack-c out of experimental first.

[experimental]: https://packages.debian.org/experimental/neovim

**Comment by ThaHypnotoad** [comment]
Alright, amidst the conversation I compiled the 1.4 release from source and found the issue also disappears on my ubuntu machine. I'm fine with just using this version for now, but if there are any ways I can diagnose this bug I would like to help.

**Comment by jamessan** [comment]
So, it works fine in 0.1.4 but not in the latest builds?  Would you be able to use git bisect to determine when things changed?

**Comment by ThaHypnotoad** [comment]
Yup. I'll do it sometime tomorrow or monday. First i've heard of that feature of git. Neat!

**Comment by justinmk** [comment]
@ThaHypnotoad Do you have any new information here?

**Comment by ThaHypnotoad** [comment]
@justinmk sorry, havent quite got my time management down, so I haven't had time to look into the issue. I was mostly just content to use a working version since it did all the things I wanted and well.

**Comment by jamessan** [comment]
@ThaHypnotoad If you can provide an example file and instructions to reproduce the slowness, then that would also allow us to investigate the issue.

**Comment by Shougo** [comment]
@ThaHypnotoad #5299 may resolve the problem.

**Comment by jamessan** [comment]
> @ThaHypnotoad #5299 may resolve the problem.

Well, there's also a significant difference in the performance of the pythonFunction syntax match.  That should be investigated independent of the general fold optimization.

**Comment by tcrs** [comment]
I just updated my Neovim build (had been using a build from April) and found that starting a new line (via `o` or pressing enter in insert mode) was very slow in a python file. This is without folding and in a small (30 line) file. Without syntax on performance was fine. I profiled vim and found that the time was spent in `GetPythonIndent`. I bisected the performance regression down to
```
commit ea18b4a60f3b89d261c46b030d3d026ddad864bb
Author: James McCoy <jamessan@jamessan.com>
Date:   Mon Jun 20 10:37:19 2016 -0400

    vim-patch:77cdfd1

    Updated runtime files.

    https://github.com/vim/vim/commit/77cdfd10382e01cc51f4ba1a9177032351843151
```

Reverting just the change to `runtime/syntax/python.vim` from that commit restores python syntax performance for me.

**Comment by Shougo** [comment]
Hm.  This is the python syntax history in Vim.
It may be fixed in the latest Vim.

**Comment by Shougo** [comment]
https://github.com/vim/vim/commits/master/runtime/syntax/python.vim

**Comment by chrisbra** [comment]
Am 2016-09-22 12:20, schrieb Shougo:
> Hm. This is the python syntax history in Vim.
> It may be fixed in the latest Vim.
> 

not necessarily, perhaps vim/vim#1098 is related

**Comment by Shougo** [comment]
Oh, the problem still remains in Vim...

**Comment by trx211** [comment]
I also encountered this issue yesterday. I added a timeout to all 3 of `searchpair` in indent/python.vim and the problem disappeared.

**Comment by trx211** [comment]
@justinmk Thank you for referencing my solution here in [the vim issue](https://github.com/vim/vim/issues/1098). Actually, I encountered this indention problem together with the syntax highlighting issue. Besides the simple fix using timeout, I tried to figure out why searchpair() is so slow in the c source code of vim and found that it is related to the implementation of multi-byte aware  text search in vim. I guess it would be difficult to improve the performance perfectly on top of current design. Some ugly hacks may work though.

**Comment by blueyed** [comment]
(btw: there is an alternative indenting plugin: https://github.com/hynek/vim-python-pep8-indent)

**Comment by zachy-ho** [comment]
Hi. Just kindly wondering if the relatively long running time of GetPythonIndent/searchPair is fixed? Was profiling and I found that GetPythonIndent was still causing a noticeable amount of 'lag'.

p.s. haven't commented on issues before so let me know if I'm not doing it right lol. Thanks!

**Comment by rodhash** [comment]
> (btw: there is an alternative indenting plugin: https://github.com/hynek/vim-python-pep8-indent)


Sir, what magic is this? Apparently your plugin worked perfectly for this performance issue, at least for me! Nvim NVIM v0.4.4 on MBP

Thank you very much!  Feels good to be back to vim/nvim, beautiful and FAST



Of course..  I did some profiling before and removed some plugins taking too long to load, one of the worst was polyglot .. things actually got better after removing but still very noticeable performance issues..

Then came to your comment and I can't believe this brutal performance gain .. something must be really broken in my original vim indent script .. my profiling pointed to GetPythonIndent:

here, to be more precise:

>FUNCTION  GetPythonIndent()
    Defined: /usr/local/Cellar/neovim/0.4.4_2/share/nvim/runtime/indent/python.vim line 31

Anyway .. lets go back to code! Thx a lot.

**Comment by rodhash** [comment]
Well now something interesting .. some Python files still getting "stuck" .. didn't expect that ..

So checking the profiling for  some Python codes I got this:

```python
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    6   2.944693   0.001335  GetPythonPEPIndent()
   12   2.935923   0.172706  <SNR>128_find_opening_paren()
 2469   2.767507             <SNR>128__skip_special_chars()
    6   1.497631   0.000142  <SNR>128_indent_like_opening_paren()
    6   1.443841   0.000914  <SNR>128_indent_like_previous_line()
    6   1.438606   0.000172  <SNR>128_find_start_of_multiline_statement()
   29   0.057565   0.005183  airline#check_mode()
    6   0.049945   0.014455  airline#highlighter#highlight()
   29   0.036877   0.001637  airline#extensions#branch#get_head()
   29   0.034015   0.001390  airline#extensions#branch#head()
  151   0.029016   0.015195  airline#highlighter#exec()
   29   0.025508   0.002330  <SNR>144_update_branch()
   29   0.020481   0.001427  <SNR>144_update_git_branch()
   29   0.018384   0.000781  FugitiveHead()
   29   0.017092   0.007779  airline#extensions#whitespace#check()
   29   0.016826   0.003748  fugitive#Head()
   29   0.013077   0.009016  fugitive#Find()
   40   0.011663   0.002315  <SNR>135_exec_separator()
   29   0.008040   0.004616  airline#extensions#hunks#get_hunks()
  231   0.007216             airline#highlighter#get_highlight()
```

That's weird that some files are still having the performance issue and others not.

Depending on the function it takes quite sometime to enter in a new line (usually with keys "o" and "a")
