### ISSUE TITLE
Python `input` gives EOFError if editing in neovim (even if backgrounded)

### ISSUE THREAD

**Issue by n8henrie** [neovim/neovim#5573]
Likely related to #3772 ?

- `nvim --version`: NVIM 0.1.6, Build type: Release
- Vim (version: ) behaves differently? Yes, vim behaves as expected. 
    - VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  8 2016 08:40:07)
    - MacOS X (unix) version

- Operating system/version: macOS 10.12.1
- Terminal name/version: Terminal.app 2.7.1 (387)
- `$TERM`: `xterm-256color`

### Actual behaviour

I generally write some Python code, write to disk, background with `Ctrl z`, and test with `python3 mycode.py` (I know I could also just `:!python3 %`).

If I do this with Neovim, Python's `input` is getting cut off by an `EOF` -- I don't get an opportunity to type my input, while this works fine in vim. Backgrounding with `nvim mycode.py &` illustrates the same behavior:

```bash
$ cat fake.py
stuff = input("some stuff: ")
print(stuff)
$ nvim -u NORC fake.py &
[1] 72342
$ python3 fake.py
some stuff: Traceback (most recent call last):
  File "fake.py", line 1, in <module>
    stuff = input("some stuff: ")
EOFError

[1]+  Stopped                 nvim fake.py
```

### Expected behaviour

Working in vim:

```bash
$ cat fake.py
stuff = input("some stuff: ")
print(stuff)
$ vim fake.py &
[1] 72342
$ python3 fake.py 
some stuff: I can enter my text here as expected
I can enter my text here as expected

[1]+  Stopped                 vim fake2.py
```

### Steps to reproduce using `nvim -u NORC`

See above

**Comment by jamessan** [comment]
This is likely fixed by https://github.com/neovim/neovim/commit/36c0ec6dd49c8c1a57eaa0b9f9d3c44792582f37.  Would you be able to test that?

**Comment by n8henrie** [comment]
I'm on OSX using homebrew, so `brew uninstall --force neovim && brew install neovim --HEAD` gives me `NVIM v0.2.0-36-gbd33f11`, which I presume has the patch above, and is working as expected.

Thanks!

**Comment by loheer** [comment]
I have version NVIM v0.2.0-113-gcbf2a86
and still experience the bug.

**Comment by justinmk** [comment]
@loheer you are using the _exact_ steps from the original post here? And the problem doesn't happen with Vim?

**Comment by loheer** [comment]
I created a new file containing:
i = input(”some input”)
And then opened it in nvim and tried executing it with
:!python %
It works in vim
On Nov 25, 2016 1:07 PM, "Justin M. Keyes" <notifications@github.com> wrote:@loheer you are using the exact steps from the original post here? And the problem doesn't happen with Vim?

**Comment by justinmk** [comment]
@loheer Those are not the steps listed in this issue. Instead you're describing #1496.
