### ISSUE TITLE
Vim(let):E121: Undefined variable: self

### ISSUE THREAD

**Issue by funeralismatic** [neovim/neovim#5763]
- `nvim --version`: `NVIM v0.2.0-134-g988ab580`
- Vim (version: ) behaves differently? `NONE`
- Operating system/version: `Gentoo`
- Terminal name/version: `termite v12-13-g7738c76`
- `$TERM`: `xterm-termite`

### Actual behaviour

```

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
  - ERROR: Failed to run healthcheck for "provider" plugin. Exception:
    function health#check[20]..health#provider#check[2]..<SNR>34_check_python[156]..<SNR>34_version_info[1]..<SNR>3
    4_latest_pypi_version[2]..<SNR>34_download[2]..<SNR>34_system[21]..<SNR>34_system_handler, line 2
    Vim(let):E121: Undefined variable: self
```

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:CheckHealth
```

And I see this error.

**Comment by rgorel** [comment]
Experience the same issue with Ubuntu 16.04 LTS and NVIM 0.2.0-dev

**Comment by mhinz** [comment]
The problem is when functions that weren't declared with `dict` refer to `self`:

```vim
function! s:func()
  return self.data
endfunction

let s:dict = {
      \ 'data': 1,
      \ 'func': function('s:func')
      \ }

echomsg s:dict.func()
```

Changing the first line like this makes it work:

```vim
function! s:func() dict
```

---

The `:CheckHealth` can be worked around in the same way: adding `dict` to [this line](https://github.com/neovim/neovim/blob/988ab5804a16beafff26b487b0612cb7cf97ea09/runtime/autoload/health/provider.vim#L28).

But yea, fixing the root of the problem is more important. ;]

**Comment by jrock2004** [comment]
For someone who installs via apt-get, how can I fix this? My neovim instance is now broken

**Comment by dylanaraps** [comment]
I'm also affected by this.

- `nvim --version`:  `NVIM v0.2.0-134-g988ab58`
- Vim (version: ) behaves differently? NONE
- Operating system/version: `Arch Linux`
- Terminal name/version: `rxvt-unicode (urxvt) v9.22 - released: 2016-01-23`
- `$TERM`: `rxvt-unicode-256color`

**Comment by jamessan** [comment]
Yes, it's an unexpected change in behavior.  There's no need for lots of people to chime in on that.  We're looking into it.

The behavior _is_ consistent with Vim, but it breaks existing Neovim scripts.

**Comment by jamessan** [comment]
0f681c80e1e9c9060394365dae12f8ebd5736176 is what introduced the regression.

**Comment by jamessan** [comment]
This was also [discussed] in the PR, so I think it's best to just move forward and fix the places where `dict` needs to be added.

[discussed]: https://github.com/neovim/neovim/pull/5529#issuecomment-259940275

**Comment by mhinz** [comment]
The partials PR changed at least two things:

- Functions that were not defined via `function dict.func()` and refer to `self`, _have to_ use the `dict` modifier.
- Event handlers (`on_stdout`/`on_stderr`/`on_exit`) _always_ expect 3 arguments now, even if you don't use any of them.

**Comment by vatrat** [comment]
Getting this problem with vim-airline and vim-fugitive whenever I open a file that's managed by git. For example, my .vimrc. It also occurs when I save the file. 

`Error detected while processing function airline#extensions#branch#get_head[1]..airline#extensions#branch#head[6]..<SNR>89_update_untracked[28]..airline#util#system[9]..<SNR>100_system_job_
handler:                                                                                                                                                                                     
line    2:     
                                                                                                                                                                              
E121: Undefined variable: self
`

I read this log and wasn't quite sure where the problems was. I only experience the problem in codeanywhere, which runs Ubuntu (and, so, the PPA version of Neovim). Because of this, I built Neovim from source. However, I s
Getting this problem with vim-airline and vim-fugitive whenever I open a file that's managed by git. For example, my .vimrc. It also occurs when I save the file. 

`Error detected while processing function airline#extensions#branch#get_head[1]..airline#extensions#branch#head[6]..<SNR>89_update_untracked[28]..airline#util#system[9]..<SNR>100_system_job_
handler:                                                                                                                                                                                     
line    2:     
                                                                                                                                                                              
E121: Undefined variable: self
`

I read this log and wasn't quite sure where the problems was. I only experience the problem in codeanywhere, which runs Ubuntu (and, so, the PPA version of Neovim). Because of this, I built Neovim from source. However, I still get the error. So, should I change something with vim-airline? Not really sure. Whenever I disabled vim-airline in my vimrc (I use vim-plug) and restarted Neovim, I got the error `E120: Using <SID> not in a script context: s:completion_delayed` whenever I went into insert mode. This may be unrelated, for example because another plugin was still trying to do something with vim-airline.

Okay, now I get no error when I open or save, but I get the `E120: Using <SID> not in a script context: s:completion_delayed` error whether I have vim-airline enabled or not. I'm not sure what's going on.

**Comment by h-michael** [comment]
@vatrat 
`E120: Using <SID> not in a script context: s:completion_delayed` may be deoplete.nvim error if you use that.
And deoplete.nvim's that issue is fixed.
Try update deoplete.nvim .

**Comment by justinmk** [comment]
@vatrat You need to update vim-airline (and deoplete).

**Comment by jamessan** [comment]
@vatrat The airline issue is fixed in the latest airline code.

**Comment by vatrat** [comment]
When I run vim-plug, nothing new is installed. What should I try?

...

Oh.

 Looks like running :PlugInstall doesn't update plugins.

So, I've never updated my plugins.

After running :PlugUpdate, everything works. I'll change my install mapping to :PlugUpdate. Thanks.

**Comment by ericLemanissier** [comment]
I have got the same error when calling :PlugUpdate

> Error detected while processing function <SNR>2_job_handler
> line    19:
> E121: Undefined variable: self


> NVIM 0.2.0-dev
> Build type: RelWithDebInfo
> Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fdebug-prefix-map=/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1/build/config -I/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1/src -I/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1/.deps/usr/include -I/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1/.deps/usr/include -I/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1/.deps/usr/include -I/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1/.deps/usr/include -I/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1/.deps/usr/include -I/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1/.deps/usr/include -I/usr/include -I/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1/build/src/nvim/auto -I/build/neovim-xgs26C/neovim-0.1.5ubuntu1+git201612221541+2978+22~ubuntu16.10.1/build/include
> Compilé par root@lgw01-07

**Comment by mhinz** [comment]
@ericLemanissier Your vim-plug is [out-of-date](https://github.com/junegunn/vim-plug/commit/5bccd9bc987a2459b3128ccd28d24e9697069e13).

**Comment by docwhat** [comment]
@ericLemanissier: Specifically, you have to run `:PlugUpgrade` to update `vim-plug`... I just fixed this just now and then found this issue. 😆

**Comment by ericLemanissier** [comment]
@docwhat thanks. I did not know about PlugUpgrade, so I redownloaded vim-plug manually and it fixed my problem

**Comment by wolf** [comment]
I hate to pile on when we were asked not to, but this is still a problem for me when building from source cloned from here, at the tip of master.  There's no clear solution above except editing the broken functions... but what functions? and where?  and is editing them really the right answer?  and if it is the right answer, why is it still a problem and this issue is closed?

All the tests pass, but `build/bin/nvim -u NORC` fails `:CheckHealth`.  My brew-installed nvim at 0.1.7 passes `:CheckHealth`; but I'd like to build and work with the tip.  I can paste more info if `:version` or `:CheckHealth` or information about my system would help, but it sounds like you guys know what's going on already.  I'm happy to contribute patches even if it means (learning and) editing Lua files.  Is that where the problem is?  Did more broken functions creep in?  Just point me in the right direction and I'm happy to help.

**Comment by justinmk** [comment]
`:CheckHealth` works fine on master. Please open a new issue with specific details (not "doesn't work").

**Comment by wolf** [comment]
I see now what the problem is.  I had the mistaken impression that `:CheckHealth` was something like `make test` ... that is, I thought I could run it in the built---but not yet installed---`build/bin/nvim`, and that running it that way would use only resources found in the source (and/or build) tree.  That turns out not to be the case.  `CheckHealth` isn't even available before you have installed.  It uses the installed machinery to do its job.  In fact, you can't even start the built `nvim` before you have installed without seeing the error `E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim`.  So `CheckHealth` uses already-installed machinery to do its job.  In my case, my installed copy of `nvim` was from Homebrew at version 0.1.7; and that's the machinery `CheckHealth` was trying to use.  New `nvim` plus old `CheckHealth` equals a failure that looks _exactly_ like the report at the very top of this issue.  This is probably "as designed" for `CheckHealth` and I'll bet would be pretty difficult to make it work as I had originally thought it did.  Probably, the appropriate response to this situation (if any response at all is actually required) is a note in the "Building Neovim" page of the Wiki.

**Comment by JackHasaKeyboard** [comment]
@docwhat I downloaded the latest version via curl... why did this work?

**Comment by docwhat** [comment]
@JackHasaKeyboard; That's all `:PlugUpgrade` does under the hood.
