### ISSUE TITLE
libtermkey: "ABORT: lookup_next within a TYPE_KEY node"

### ISSUE THREAD

**Issue by sittim** [neovim/neovim#5895]
All of a sudden, when I use ST terminal, NeoVIM does not work, but it does work in gnome terminal.  Get this error:

![selection_033](https://cloud.githubusercontent.com/assets/8825037/21719064/a423ad8a-d3e9-11e6-880b-ac6b73d14e67.png)

I am using Ubuntu and I tried to install Termite Terminal, which could have been the cause.  Does anyone have any suggestions?

- `nvim --version`: .15

```
NVIM 0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic
-Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-WIPVdZ/neovim-0.1.5ubuntu1+git201701051417+3021+22~ubuntu16.04.1/build/config -I/build/neovim-WIPVdZ/neovim-0.1.5ubuntu1+git201701051417+3021+22~ubuntu16.04.1/src -I/build/neovim-WIPVdZ/neovim-0.1.5ubuntu1+git201701051417+3021+22~ubuntu16.04.1/.deps/usr/include -I/build/neovim-WIPVdZ/neovim-0.1.5ubuntu1+git201701051417+3021+22~ubuntu16.04.1/.deps/usr/include -I/build/neovim-WIPVdZ/neovim-0.1.5ubuntu1+git201701051417+3021+22~ubuntu16.04.1/.deps/usr/include -I/build/neovim-WIPVdZ/neovim-0.1.5ubuntu1+git201701051417+3021+22~ubuntu16.04.1/.deps/usr/include -I/build/neovim-WIPVdZ/neovim-0.1.5ubuntu1+git201701051417+3021+22~ubuntu16.04.1/.deps/usr/include -I/build/neovim-WIPVdZ/neovim-0.1.5ubuntu1+git201701051417+3021+22~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-WIPVdZ/neovim-0.1.5ubuntu1+git201701051417+3021+22~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-WIPVdZ/neovim-0.1.5ubuntu1+git201701051417+3021+22~ubuntu16.04.1/build/include
Compiled by root@lgw01-28

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

- Vim (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Actual behaviour
![selection_033](https://cloud.githubusercontent.com/assets/8825037/21719031/6f371b34-d3e9-11e6-93c6-ac910923d7c1.png)
### Expected behaviour
nvim starting
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by justinmk** [comment]
@sittim If you are running a local build, any chance you could try reverting https://github.com/neovim/neovim/pull/5758 ?

@leonerd Any hints about this? Is this most likely a bug on our end? I've never seen this before.

**Comment by DarkDeepBlue** [comment]
In my st terminal there are no issues running nvim, so the cause might be a certain configuration detail.

**Comment by leonerd** [comment]
@justinmk Oooh wow. I've never seen that one before.
That sounds possibly a bug in libtermkey. That's some very odd behaviour of its terminfo-based string parsing code. On first glance of the code I can't possibly imagine how it can get into that state (which is why it SIGABRTs; that's supposed to be impossible).

Some more detail might be helpful here - can we get a copy of the full output of `infocmp -L` on the terminal in question? That would give us all the TI key strings.

**Comment by sittim** [comment]
## $TERM

```bash
/home/sporty/Downloads~> echo $TERM
st-256color
```

## inforcmp

```bash
/home/sporty/Downloads~> infocmp -L
#       Reconstructed via infocmp from file: /etc/terminfo/s/st-256color
st-256color| simpleterm with 256 colors,
        auto_right_margin, back_color_erase,
        eat_newline_glitch, has_status_line, move_insert_mode,
        move_standout_mode, no_pad_char,
        columns#80, init_tabs#8, lines#24, max_colors#256,
        max_pairs#32767,
        acs_chars=+C\054D-A.B0E``aaffgghFiGjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        back_tab=\E[Z, bell=^G, carriage_return=^M,
        change_scroll_region=\E[%i%p1%d;%p2%dr,
        clear_all_tabs=\E[3g, clear_screen=\E[H\E[2J,
        clr_bol=\E[1K, clr_eol=\E[K, clr_eos=\E[J,
        column_address=\E[%i%p1%dG,
        cursor_address=\E[%i%p1%d;%p2%dH, cursor_down=^J,
        cursor_home=\E[H, cursor_invisible=\E[?25l,
        cursor_left=^H, cursor_normal=\E[?12l\E[?25h,
        cursor_right=\E[C, cursor_up=\E[A,
        cursor_visible=\E[?25h, delete_character=\E[P,
        delete_line=\E[M, ena_acs=\E)0,
        enter_alt_charset_mode=\E(0, enter_blink_mode=\E[5m,
        enter_bold_mode=\E[1m, enter_ca_mode=\E[?1049h,
        enter_insert_mode=\E[4h, enter_italics_mode=\E[3m,
        enter_reverse_mode=\E[7m, enter_secure_mode=\E[8m,
        enter_standout_mode=\E[7m,
        enter_underline_mode=\E[4m, erase_chars=\E[%p1%dX,
        exit_alt_charset_mode=\E(B,
        exit_attribute_mode=\E[0m, exit_ca_mode=\E[?1049l,
        exit_insert_mode=\E[4l, exit_italics_mode=\E[23m,
        exit_standout_mode=\E[27m,
        exit_underline_mode=\E[24m,
        flash_screen=\E[?5h$<80/>\E[?5l, from_status_line=^G,
        init_2string=\E[4l\E>\E[?1034l, insert_line=\E[L,
        key_a1=\E[1~, key_a3=\E[5~, key_b2=\EOu,
        key_backspace=^H, key_btab=\E[Z, key_c1=\E[4~,
        key_c3=\E[6~, key_clear=\E[3;5~, key_dc=\177~,
        key_dl=\E[3;2~, key_down=\EOB, key_eic=\E[2;2~,
        key_end=\E[4~, key_enter=\EOM, key_eol=\E[1;2F,
        key_eos=\E[1;5F, key_f1=\EOP, key_f10=\E[21~,
        key_f11=\E[23~, key_f12=\E[24~, key_f13=\E[1;2P,
        key_f14=\E[1;2Q, key_f15=\E[1;2R, key_f16=\E[1;2S,
        key_f17=\E[15;2~, key_f18=\E[17;2~, key_f19=\E[18;2~,
        key_f2=\EOQ, key_f20=\E[19;2~, key_f21=\E[20;2~,
        key_f22=\E[21;2~, key_f23=\E[23;2~, key_f24=\E[24;2~,
        key_f25=\E[1;5P, key_f26=\E[1;5Q, key_f27=\E[1;5R,
        key_f28=\E[1;5S, key_f29=\E[15;5~, key_f3=\EOR,
        key_f30=\E[17;5~, key_f31=\E[18;5~, key_f32=\E[19;5~,
        key_f33=\E[20;5~, key_f34=\E[21;5~, key_f35=\E[23;5~,
        key_f36=\E[24;5~, key_f37=\E[1;6P, key_f38=\E[1;6Q,
        key_f39=\E[1;6R, key_f4=\EOS, key_f40=\E[1;6S,
        key_f41=\E[15;6~, key_f42=\E[17;6~, key_f43=\E[18;6~,
        key_f44=\E[19;6~, key_f45=\E[20;6~, key_f46=\E[21;6~,
        key_f47=\E[23;6~, key_f48=\E[24;6~, key_f49=\E[1;3P,
        key_f5=\E[15~, key_f50=\E[1;3Q, key_f51=\E[1;3R,
        key_f52=\E[1;3S, key_f53=\E[15;3~, key_f54=\E[17;3~,
        key_f55=\E[18;3~, key_f56=\E[19;3~, key_f57=\E[20;3~,
        key_f58=\E[21;3~, key_f59=\E[23;3~, key_f6=\E[17~,
        key_f60=\E[24;3~, key_f61=\E[1;4P, key_f62=\E[1;4Q,
        key_f63=\E[1;4R, key_f7=\E[18~, key_f8=\E[19~,
        key_f9=\E[20~, key_home=\E[1~, key_ic=\E[2~,
        key_il=\E[2;5~, key_left=\EOD, key_mouse=\E[M,
        key_npage=\E[6~, key_ppage=\E[5~, key_right=\EOC,
        key_sdc=\E[3;2~, key_send=\E[1;2F, key_sf=\E[1;2B,
        key_shome=\E[1;2H, key_sic=\E[2;2~, key_sleft=\E[1;2D,
        key_snext=\E[6;2~, key_sprevious=\E[5;2~,
        key_sr=\E[1;2A, key_sright=\E[1;2C, key_up=\EOA,
        keypad_local=\E[?1l\E>, keypad_xmit=\E[?1h\E=,
        orig_pair=\E[39;49m, parm_dch=\E[%p1%dP,
        parm_delete_line=\E[%p1%dM,
        parm_down_cursor=\E[%p1%dB, parm_ich=\E[%p1%d@,
        parm_index=\E[%p1%dS, parm_insert_line=\E[%p1%dL,
        parm_left_cursor=\E[%p1%dD,
        parm_right_cursor=\E[%p1%dC,
        parm_up_cursor=\E[%p1%dA, print_screen=\E[i,
        prtr_off=\E[4i, prtr_on=\E[5i, reset_1string=\Ec,
        reset_2string=\E[4l\E>\E[?1034l, restore_cursor=\E8,
        row_address=\E[%i%p1%dd, save_cursor=\E7,
        scroll_forward=^J, scroll_reverse=\EM,
        set_a_background=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        set_a_foreground=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        set_attributes=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        set_background=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
        set_foreground=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
        set_tab=\EH, tab=^I, to_status_line=\E]0;,
```

**Comment by sittim** [comment]
## WOW...

![selection_034](https://cloud.githubusercontent.com/assets/8825037/21720300/49f7b930-d3f0-11e6-992e-0258d11a561e.png)


## once the $TERM is unset, it works fine

**Comment by leonerd** [comment]
Hmm. That's sortof expected. If `$TERM` is not set, I believe nvim will fall back on some basic tty name like "dumb" or "vt100". This reïnforces my suspicion that the problem is related to some values obtained from your terminfo.

**Comment by Vintodrimmer** [comment]
Good day,

Can it be fixed on the part of the neovim by any chance?

**Comment by oldgaro** [comment]
It still happening. But it is a St or bash faulty! not neovim! As I cant replicate it on Rxvt-Unicode

**Comment by justinmk** [comment]
It depends on `$TERM`, as explained above.

**Comment by oldgaro** [comment]
`screen`

**Comment by oldgaro** [comment]
#### Term 
St:
`st-256color`

#### infocmp -L
```

#	Reconstructed via infocmp from file: /usr/share/terminfo/s/st-256color
st-256color| simpleterm with 256 colors,
	auto_right_margin, back_color_erase,
	eat_newline_glitch, has_status_line, move_insert_mode,
	move_standout_mode, no_pad_char,
	columns#80, init_tabs#8, lines#24, max_colors#0x100,
	max_pairs#0x7fff, no_color_video#3,
	acs_chars=+C\054D-A.B0E``aaffgghFiGjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	back_tab=\E[Z, bell=^G, carriage_return=\r,
	change_scroll_region=\E[%i%p1%d;%p2%dr,
	clear_all_tabs=\E[3g, clear_screen=\E[H\E[2J,
	clr_bol=\E[1K, clr_eol=\E[K, clr_eos=\E[J,
	column_address=\E[%i%p1%dG,
	cursor_address=\E[%i%p1%d;%p2%dH, cursor_down=\n,
	cursor_home=\E[H, cursor_invisible=\E[?25l,
	cursor_left=^H, cursor_normal=\E[?12l\E[?25h,
	cursor_right=\E[C, cursor_up=\E[A,
	cursor_visible=\E[?25h, delete_character=\E[P,
	delete_line=\E[M, ena_acs=\E)0,
	enter_alt_charset_mode=\E(0, enter_blink_mode=\E[5m,
	enter_bold_mode=\E[1m, enter_ca_mode=\E[?1049h,
	enter_insert_mode=\E[4h, enter_italics_mode=\E[3m,
	enter_reverse_mode=\E[7m, enter_secure_mode=\E[8m,
	enter_standout_mode=\E[7m,
	enter_underline_mode=\E[4m, erase_chars=\E[%p1%dX,
	exit_alt_charset_mode=\E(B,
	exit_attribute_mode=\E[0m, exit_ca_mode=\E[?1049l,
	exit_insert_mode=\E[4l, exit_italics_mode=\E[23m,
	exit_standout_mode=\E[27m,
	exit_underline_mode=\E[24m,
	flash_screen=\E[?5h$<80/>\E[?5l, from_status_line=^G,
	init_2string=\E[4l\E>\E[?1034l, insert_line=\E[L,
	key_a1=\E[1~, key_a3=\E[5~, key_b2=\EOu,
	key_backspace=^H, key_btab=\E[Z, key_c1=\E[4~,
	key_c3=\E[6~, key_clear=\E[3;5~, key_dc=\177~,
	key_dl=\E[3;2~, key_down=\EOB, key_eic=\E[2;2~,
	key_end=\E[4~, key_enter=\EOM, key_eol=\E[1;2F,
	key_eos=\E[1;5F, key_f1=\EOP, key_f10=\E[21~,
	key_f11=\E[23~, key_f12=\E[24~, key_f13=\E[1;2P,
	key_f14=\E[1;2Q, key_f15=\E[1;2R, key_f16=\E[1;2S,
	key_f17=\E[15;2~, key_f18=\E[17;2~, key_f19=\E[18;2~,
	key_f2=\EOQ, key_f20=\E[19;2~, key_f21=\E[20;2~,
	key_f22=\E[21;2~, key_f23=\E[23;2~, key_f24=\E[24;2~,
	key_f25=\E[1;5P, key_f26=\E[1;5Q, key_f27=\E[1;5R,
	key_f28=\E[1;5S, key_f29=\E[15;5~, key_f3=\EOR,
	key_f30=\E[17;5~, key_f31=\E[18;5~, key_f32=\E[19;5~,
	key_f33=\E[20;5~, key_f34=\E[21;5~, key_f35=\E[23;5~,
	key_f36=\E[24;5~, key_f37=\E[1;6P, key_f38=\E[1;6Q,
	key_f39=\E[1;6R, key_f4=\EOS, key_f40=\E[1;6S,
	key_f41=\E[15;6~, key_f42=\E[17;6~, key_f43=\E[18;6~,
	key_f44=\E[19;6~, key_f45=\E[20;6~, key_f46=\E[21;6~,
	key_f47=\E[23;6~, key_f48=\E[24;6~, key_f49=\E[1;3P,
	key_f5=\E[15~, key_f50=\E[1;3Q, key_f51=\E[1;3R,
	key_f52=\E[1;3S, key_f53=\E[15;3~, key_f54=\E[17;3~,
	key_f55=\E[18;3~, key_f56=\E[19;3~, key_f57=\E[20;3~,
	key_f58=\E[21;3~, key_f59=\E[23;3~, key_f6=\E[17~,
	key_f60=\E[24;3~, key_f61=\E[1;4P, key_f62=\E[1;4Q,
	key_f63=\E[1;4R, key_f7=\E[18~, key_f8=\E[19~,
	key_f9=\E[20~, key_home=\E[1~, key_ic=\E[2~,
	key_il=\E[2;5~, key_left=\EOD, key_mouse=\E[M,
	key_npage=\E[6~, key_ppage=\E[5~, key_right=\EOC,
	key_sdc=\E[3;2~, key_send=\E[1;2F, key_sf=\E[1;2B,
	key_shome=\E[1;2H, key_sic=\E[2;2~, key_sleft=\E[1;2D,
	key_snext=\E[6;2~, key_sprevious=\E[5;2~,
	key_sr=\E[1;2A, key_sright=\E[1;2C, key_up=\EOA,
	keypad_local=\E[?1l\E>, keypad_xmit=\E[?1h\E=,
	orig_pair=\E[39;49m, parm_dch=\E[%p1%dP,
	parm_delete_line=\E[%p1%dM,
	parm_down_cursor=\E[%p1%dB, parm_ich=\E[%p1%d@,
	parm_index=\E[%p1%dS, parm_insert_line=\E[%p1%dL,
	parm_left_cursor=\E[%p1%dD,
	parm_right_cursor=\E[%p1%dC,
	parm_up_cursor=\E[%p1%dA, print_screen=\E[i,
	prtr_off=\E[4i, prtr_on=\E[5i, reset_1string=\Ec,
	reset_2string=\E[4l\E>\E[?1034l, restore_cursor=\E8,
	row_address=\E[%i%p1%dd, save_cursor=\E7,
	scroll_forward=\n, scroll_reverse=\EM,
	set_a_background=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	set_a_foreground=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	set_attributes=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	set_background=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	set_foreground=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	set_tab=\EH, tab=^I, to_status_line=\E]0;,

```

**Comment by oldgaro** [comment]
I tried St default package of Arch....still same issue!

**Comment by oldgaro** [comment]
I tried harder:

St default package of Arch Linux:  `ABORT: lookup_next within a TYPE_KEY node` 
Neovim from Aur (neovim-git): `ABORT: lookup_next within a TYPE_KEY node `
Nvim Appimage nightly: `ABORT: lookup_next within a TYPE_KEY node`

Although I can open nvim in: `St+Tmux, Rxvt-Unicode, Termite and Xterm. `

PS: I am still learning C, so I cant help further!  haha

https://github.com/neovim/libtermkey/blob/master/driver-ti.c

**Comment by oldgaro** [comment]
It is working again with St. 

I wiped my SSD and reinstalled Arch Linux and St again...and its ok now! haha

thanks! anyway

**Comment by elerch** [comment]
I had this issue as well, but based on the comment from @oldgaro I took a look at the commits on st since I originally compiled. I ended up cherry-picking https://git.suckless.org/st/commit/?id=b331da550b290d54592b7ba11242c92f5a303a48 into my st source. I then ran "tic -sx st.info" to get updated terminfo information and this fixed the issue.

This appears to be a libtermkey issue triggered by st's terminfo configuration prior to commit b331da5 in st.

**Comment by mvaenskae** [comment]
Cheers,

I also just encountered this bug while trying to update my st installation to current master with some patches.
neovim: v0.2.0 (gentoo-ebuild)
st commit: b1338e91ed632adbcd08388de37e46cf25326e01

The patch I believe to cause issues on my end is the following: https://st.suckless.org/patches/delkey/
The version I applied is this one: https://st.suckless.org/patches/delkey/st-delkey-20160727-308bfbf.diff

Running with the patch I cannot get nvim to start (same error as described above) and have some trouble regarding terminal input for sudo and other interactive dialogues. Without the patch everything works as usual and no issues occur. So anyone using the patch, I advise you to revert it and not use it anymore (I cannot find a reason as to why it should be required. On my end everything as expected).

I have little understanding as to why this happens but I believe this to be a multi-component issue in the end.

**Comment by oldgaro** [comment]
@mvaenskae Might be it indeed, cause I did patch St with delkey too! haha

**Comment by justinmk** [comment]
This should be fixed by the latest version of libtermkey (0.22). Ensure that Neovim was built with that version before reporting this as not-fixed. Nvim 0.4.x should have the version on most systems.

**Comment by slotThe** [comment]
Hello! Still getting this issue.

- `nvim --version`: 
``` 
NVIM v0.4.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.4.0/build/config -I/builddir/neovim-0.4.0/src -I/usr/include -I/builddir/neovim-0.4.0/build/src/nvim/auto -I/builddir/neovim-0.4.0/build/include
Compiled by slot@********

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: Void Linux/musl build
- Terminal name/version: st git build (newest commit is `f1546cf9c1f9fc52d26dbbcf73210901e83c7ecf`)
- `$TERM`: st-256color

Version of libtermkey used (output of `xbps-query libtermkey`):
```
architecture: x86_64-musl
automatic-install: yes
build-date: 2019-03-14 23:18 CDT
filename-sha256: f9fc16807326211710e109a8a5314d3d61897fc32300dc66160ad82405d8fc26
filename-size: 20KB
homepage: http://www.leonerd.org.uk/code/libtermkey
install-date: 2019-04-27 13:15 CEST
installed_size: 60KB
license: MIT
maintainer: Steve Prybylski <sa.prybylx@gmail.com>
metafile-sha256: fdb58ca82992601239fe7d9b882d7ec0a2bfad9b5d11ade291862d61fe86b7f6
pkgver: libtermkey-0.22_1
repository: https://alpha.de.repo.voidlinux.org/current/musl
shlib-provides:
        libtermkey.so.1
shlib-requires:
        libunibilium.so.4
        libc.so
short_desc: Library for processing keyboard entry from terminal-based programs
source-revisions: libtermkey:b95a49b243
state: installed
```

**Comment by KillTheMule** [comment]
I know nothing of Void linux, but could you check nvim is really using this lib? The output of `ld` should give you this info.

**Comment by slotThe** [comment]
For `ldd $(which nvim)` I get the following outut:
```
        /lib/ld-musl-x86_64.so.1 (0x7f6eb7cd5000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7f6eb7cd5000)
        libintl.so.8 => /lib/libintl.so.8 (0x7f6eb776f000)
        libuv.so.1 => /lib/libuv.so.1 (0x7f6eb7740000)
        libmsgpackc.[slot@pbox ~]$ ldd $(which nvim)
        /lib/ld-musl-x86_64.so.1 (0x7f6eb7cd5000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7f6eb7cd5000)
        libintl.so.8 => /lib/libintl.so.8 (0x7f6eb776f000)
        libuv.so.1 => /lib/libuv.so.1 (0x7f6eb7740000)
        libmsgpackc.so.2 => /lib/libmsgpackc.so.2 (0x7f6eb7539000)
        libvterm.so.0 => /lib/libvterm.so.0 (0x7f6eb7528000)
        libtermkey.so.1 => /lib/libtermkey.so.1 (0x7f6eb751b000)
        libunibilium.so.4 => /lib/libunibilium.so.4 (0x7f6eb7308000)
        libluajit-5.1.so.2 => /lib/libluajit-5.1.so.2 (0x7f6eb728c000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f6eb7273000)
so.2 => /lib/libmsgpackc.so.2 (0x7f6eb7539000)
        libvterm.so.0 => /lib/libvterm.so.0 (0x7f6eb7528000)
        libtermkey.so.1 => /lib/libtermkey.so.1 (0x7f6eb751b000)
        libunibilium.so.4 => /lib/libunibilium.so.4 (0x7f6eb7308000)
        libluajit-5.1.so.2 => /lib/libluajit-5.1.so.2 (0x7f6eb728c000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f6eb7273000)
```

**Comment by KillTheMule** [comment]
Ok, smarter people than me need to look at this :) I'd only like to ask you to make sure that `which nvim` really points to the nvim you're using, just to cut out that possibility.

**Comment by slotThe** [comment]
Ah yes, I should have probably made that more clear. It points to `/usr/bin/nvim`, which is indeed what I'm using. I edited the above post with the more explicit command.

**Comment by leonerd** [comment]
Possibly your terminfo file claims something silly; like that one key string is a prefix of another. That would cause this issue.

What $TERM and can you paste the output of `infocmp -L` on it please?

**Comment by slotThe** [comment]
`$TERM` is `st-256color`

`infoccmp -L` output is
```
#	Reconstructed via infocmp from file: /home/slot/.terminfo/s/st-256color
st-256color| simpleterm with 256 colors,
	auto_right_margin, back_color_erase, can_change,
	eat_newline_glitch, has_status_line, move_insert_mode,
	move_standout_mode, no_pad_char,
	columns#80, init_tabs#8, lines#24, max_colors#0x100,
	max_pairs#0x7fff,
	acs_chars=+C\054D-A.B0E``aaffgghFiGjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	back_tab=\E[Z, bell=^G, carriage_return=\r,
	change_scroll_region=\E[%i%p1%d;%p2%dr,
	clear_all_tabs=\E[3g, clear_screen=\E[H\E[2J,
	clr_bol=\E[1K, clr_eol=\E[K, clr_eos=\E[J,
	column_address=\E[%i%p1%dG,
	cursor_address=\E[%i%p1%d;%p2%dH, cursor_down=\n,
	cursor_home=\E[H, cursor_invisible=\E[?25l,
	cursor_left=^H, cursor_normal=\E[?12l\E[?25h,
	cursor_right=\E[C, cursor_up=\E[A,
	cursor_visible=\E[?25h, delete_character=\E[P,
	delete_line=\E[M, ena_acs=\E)0,
	enter_alt_charset_mode=\E(0, enter_blink_mode=\E[5m,
	enter_bold_mode=\E[1m, enter_ca_mode=\E[?1049h,
	enter_dim_mode=\E[2m, enter_insert_mode=\E[4h,
	enter_italics_mode=\E[3m, enter_reverse_mode=\E[7m,
	enter_secure_mode=\E[8m, enter_standout_mode=\E[7m,
	enter_underline_mode=\E[4m, erase_chars=\E[%p1%dX,
	exit_alt_charset_mode=\E(B,
	exit_attribute_mode=\E[0m, exit_ca_mode=\E[?1049l,
	exit_insert_mode=\E[4l, exit_italics_mode=\E[23m,
	exit_standout_mode=\E[27m,
	exit_underline_mode=\E[24m,
	flash_screen=\E[?5h$<80/>\E[?5l, from_status_line=^G,
	init_2string=\E[4l\E>\E[?1034l,
	initialize_color=\E]4;%p1%d;rgb\072%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\,
	insert_line=\E[L, key_a1=\E[1~, key_a3=\E[5~,
	key_b2=\EOu, key_backspace=^H, key_btab=\E[Z,
	key_c1=\E[4~, key_c3=\E[6~, key_clear=\E[3;5~,
	key_dc=\177~, key_dl=\E[3;2~, key_down=\EOB,
	key_eic=\E[2;2~, key_end=\E[4~, key_enter=\EOM,
	key_eol=\E[1;2F, key_eos=\E[1;5F, key_f1=\EOP,
	key_f10=\E[21~, key_f11=\E[23~, key_f12=\E[24~,
	key_f13=\E[1;2P, key_f14=\E[1;2Q, key_f15=\E[1;2R,
	key_f16=\E[1;2S, key_f17=\E[15;2~, key_f18=\E[17;2~,
	key_f19=\E[18;2~, key_f2=\EOQ, key_f20=\E[19;2~,
	key_f21=\E[20;2~, key_f22=\E[21;2~, key_f23=\E[23;2~,
	key_f24=\E[24;2~, key_f25=\E[1;5P, key_f26=\E[1;5Q,
	key_f27=\E[1;5R, key_f28=\E[1;5S, key_f29=\E[15;5~,
	key_f3=\EOR, key_f30=\E[17;5~, key_f31=\E[18;5~,
	key_f32=\E[19;5~, key_f33=\E[20;5~, key_f34=\E[21;5~,
	key_f35=\E[23;5~, key_f36=\E[24;5~, key_f37=\E[1;6P,
	key_f38=\E[1;6Q, key_f39=\E[1;6R, key_f4=\EOS,
	key_f40=\E[1;6S, key_f41=\E[15;6~, key_f42=\E[17;6~,
	key_f43=\E[18;6~, key_f44=\E[19;6~, key_f45=\E[20;6~,
	key_f46=\E[21;6~, key_f47=\E[23;6~, key_f48=\E[24;6~,
	key_f49=\E[1;3P, key_f5=\E[15~, key_f50=\E[1;3Q,
	key_f51=\E[1;3R, key_f52=\E[1;3S, key_f53=\E[15;3~,
	key_f54=\E[17;3~, key_f55=\E[18;3~, key_f56=\E[19;3~,
	key_f57=\E[20;3~, key_f58=\E[21;3~, key_f59=\E[23;3~,
	key_f6=\E[17~, key_f60=\E[24;3~, key_f61=\E[1;4P,
	key_f62=\E[1;4Q, key_f63=\E[1;4R, key_f7=\E[18~,
	key_f8=\E[19~, key_f9=\E[20~, key_home=\E[1~,
	key_ic=\E[2~, key_il=\E[2;5~, key_left=\EOD,
	key_mouse=\E[M, key_npage=\E[6~, key_ppage=\E[5~,
	key_right=\EOC, key_sdc=\E[3;2~, key_send=\E[1;2F,
	key_sf=\E[1;2B, key_shome=\E[1;2H, key_sic=\E[2;2~,
	key_sleft=\E[1;2D, key_snext=\E[6;2~,
	key_sprevious=\E[5;2~, key_sr=\E[1;2A,
	key_sright=\E[1;2C, key_up=\EOA,
	keypad_local=\E[?1l\E>, keypad_xmit=\E[?1h\E=,
	orig_colors=\E]104^G, orig_pair=\E[39;49m,
	parm_dch=\E[%p1%dP, parm_delete_line=\E[%p1%dM,
	parm_down_cursor=\E[%p1%dB, parm_ich=\E[%p1%d@,
	parm_index=\E[%p1%dS, parm_insert_line=\E[%p1%dL,
	parm_left_cursor=\E[%p1%dD,
	parm_right_cursor=\E[%p1%dC,
	parm_up_cursor=\E[%p1%dA, print_screen=\E[i,
	prtr_off=\E[4i, prtr_on=\E[5i, reset_1string=\Ec,
	reset_2string=\E[4l\E>\E[?1034l, restore_cursor=\E8,
	row_address=\E[%i%p1%dd, save_cursor=\E7,
	scroll_forward=\n, scroll_reverse=\EM,
	set_a_background=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	set_a_foreground=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	set_attributes=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	set_background=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	set_foreground=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	set_tab=\EH, tab=^I, to_status_line=\E]0;,
```
