### ISSUE TITLE
Drag selection broken in Neovim running in Konsole (works in Vim).

### ISSUE THREAD

**Issue by lourenko** [neovim/neovim#6907]
- `nvim --version`:NVIM v0.2.1-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-rVtC9d/neovim-0.2.0ubuntu1+git201706151255+3476+26~ubuntu16.04.1/build/config -I/build/neovim-rVtC9d/neovim-0.2.0ubuntu1+git201706151255+3476+26~ubuntu16.04.1/src -I/build/neovim-rVtC9d/neovim-0.2.0ubuntu1+git201706151255+3476+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-rVtC9d/neovim-0.2.0ubuntu1+git201706151255+3476+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-rVtC9d/neovim-0.2.0ubuntu1+git201706151255+3476+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-rVtC9d/neovim-0.2.0ubuntu1+git201706151255+3476+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-rVtC9d/neovim-0.2.0ubuntu1+git201706151255+3476+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-rVtC9d/neovim-0.2.0ubuntu1+git201706151255+3476+26~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-rVtC9d/neovim-0.2.0ubuntu1+git201706151255+3476+26~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-rVtC9d/neovim-0.2.0ubuntu1+git201706151255+3476+26~ubuntu16.04.1/build/include
Compilado por root@lgw01-20

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/usr/share/nvim

- Vim (version: ) behaves differently? Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
- Operating system/version: Ubuntu 16.04.2 LTS Xenial
- Terminal name/version: Konsole: 16.04.3 (from a KDE desktop)
- `$TERM`: xterm-256color

### Actual behaviour

Start dragging with left mouse key pressed to select word by word. In NeoVim, as the selection starts, the whole word is selected, instead of character by character, as like as in visual selection. This  feature only occurs when I use the Konsole terminal. In other terminals, like gnome-terminal and xterm, its work as expected.

### Expected behaviour

Select some characters of a word using the left mouse key, like in Vim (in Konsole terminal).

### Steps to reproduce using `nvim -u NORC`

```
set mouse=a
```
Write some word like `mississipi is a river` and then, using the mouse, try to select *only* the sequence  `ississ` by dragging the mouse left key.

**Comment by justinmk** [comment]
Thanks for reporting, please try https://github.com/neovim/neovim/pull/6801 . And check existing issues.

**Comment by tinchoz49** [comment]
hi @justinmk, how are you? 

Sorry to bother you in this duplicated issue but i'm having this problem too. Is this issue was fixed with the PR #6801 ? 

I'm using `NVIM v0.2.1-1122-g54b79f19d`

thanks!

**Comment by lourenko** [comment]
Not until now. Its possible to reopen the issue PR #6801
<https://github.com/neovim/neovim/pull/6801>?

Thank you too,

Marcos Lourenço

**Comment by lourenko** [comment]
> hi @justinmk, how are you?
> 
> Sorry to bother you in this duplicated issue but i'm having this problem too. Is this issue was fixed with the PR #6801 ?
> 
> I'm using `NVIM v0.2.1-1122-g54b79f19d`
> 
> thanks!

This problems persists until today. Then I'm still using Vim.
