### ISSUE TITLE
mouse wheel problem in terminal nvim

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#6989]
- `nvim --version`: master
- Vim (version: ) behaves differently? yes
- Operating system/version: arch i686
- Terminal name/version: termite
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u NORC`

```vim
function! Test() abort
    let g:wsd = []
    let i = 0
    while i < 5
        let i += 1
        let char = getchar()
        call add(g:wsd, char)
    endwhile
    echo g:wsd
endfunction
```

```
nvim -u NORC
:so test.vim
:call Test()
pull down mouse wheel
```

### Actual behaviour

in nvim when pull down mouse wheel, I see:

```
['<80><fd>K', '<80><fc> <80><fd>K', '<80><fc>@<80><fd>K', '<80><fc>`<80><fd>K', '<80><fd>K']
```

in vim when pull down mouse wheel I see:

```
['<80><fd>K', '<80><fd>K', '<80><fd>K', '<80><fd>K', '<80><fd>K']
```

### Expected behaviour

I think in vim and neovim, mouse wheel should do same thing, in neovim when pull down mouse wheel, it should not send different charactors.

**Comment by justinmk** [comment]
@wsdjeg Was this fixed by 0.2.1?

**Comment by wsdjeg** [comment]
no, and I am using the latest verison.

still get `['<80><fd>K', '<80><fc> <80><fd>K', '<80><fc>@<80><fd>K', '<80><fc>`<80><fd>K', '<80><fd>K']`

**Comment by wsdjeg** [comment]
this is a simple plugin patch for people who want to use mouse wheel in neovim(TUI).

for me, I want to use `<ScrollWheelUp>` and `<ScrollWheelDown>` to switch to next item or previous item, but with this issue, we can not handle all the key sended from mouse sheel, so I add something to fix it in my plugin.

```vim
let s:MPT._function_key = {
      \ "\<Tab>" : function('s:next_item'),
      \ "\<ScrollWheelDown>" : function('s:next_item'),
      \ "\<S-tab>" : function('s:previous_item'),
      \ "\<ScrollWheelUp>" : function('s:previous_item'),
      \ "\<Return>" : function('s:open_item'),
      \ "\<LeftMouse>" : function('s:move_cursor'),
      \ "\<2-LeftMouse>" : function('s:double_click'),
      \ }

if has('nvim')
  call extend(s:MPT._function_key, 
        \ {
        \ "\x80\xfdJ" : function('s:previous_item'),
        \ "\x80\xfc \x80\xfdJ" : function('s:previous_item'),
        \ "\x80\xfc@\x80\xfdJ" : function('s:previous_item'),
        \ "\x80\xfc`\x80\xfdJ" : function('s:previous_item'),
        \ "\x80\xfdK" : function('s:next_item'),
        \ "\x80\xfc \x80\xfdK" : function('s:next_item'),
        \ "\x80\xfc@\x80\xfdK" : function('s:next_item'),
        \ "\x80\xfc`\x80\xfdK" : function('s:next_item'),
        \ }
        \ )
endif
```

**Comment by justinmk** [comment]
Related? #6211

**Comment by wsdjeg** [comment]
@zeertzjq @bfredl Thanks :)
