### ISSUE TITLE
Weird characters in terminal after 0.2.1 

### ISSUE THREAD

**Issue by htfy96** [neovim/neovim#7002]
## `nvim --version`: 
```
NVIM v0.2.1-511-g105d680ae
Build type: RelWithDebInfo
Compilation: /usr/lib/ccache/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -g -fvar-tracking-assignments -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/build/include
Compiled by lz@lzPC

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
## Vim (version: ) behaves differently?
Vim 8.0.628 with `vim -u NONE` behaves properly.

## Operating system/version:
Arch Linux x86-64
## Terminal name/version:
Guake Terminal 0.8.10
Cannot reproduce on gnome-terminals
## `$TERM`:
xterm-256color

## Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
// press i
// input some characters
// Observe that weird characters appears
```

### Actual behaviour

![screenshot from 2017-07-11 11-59-48](https://user-images.githubusercontent.com/8121231/28050591-30324096-6631-11e7-88fa-e584984e27ca.png)
![screenshot from 2017-07-11 12-00-03](https://user-images.githubusercontent.com/8121231/28050707-e80e3fe4-6631-11e7-87da-d06b93498a5b.png)

### Expected behaviour
No weird characters.

## Addition
Ran `valgrind --track-origins=yes --leak-check=full nvim -u NONE 2>/tmp/record.txt`. Here is the log:
[record.txt](https://github.com/neovim/neovim/files/1137699/record.txt). Not sure whether it is related to #4796 since the same error is reported on gnome-terminal which works well.

**Comment by Shougo** [comment]
You can test it. 
https://github.com/neovim/neovim/pull/6997

**Comment by kunalg** [comment]
Same here. I'm on a nightly build on ubuntu 16.04 LTS (using [neovim-ppa/unstable](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable)).
```
kunal@hydrogen:~$ nvim -v
NVIM v0.2.1-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-45NS1U/neovim-0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1/build/config -I/build/neovim-45NS1U/neovim-0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1/src -I/build/neovim-45NS1U/neovim-0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-45NS1U/neovim-0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-45NS1U/neovim-0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-45NS1U/neovim-0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-45NS1U/neovim-0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-45NS1U/neovim-0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-45NS1U/neovim-0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-45NS1U/neovim-0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1/build/include
Compiled by root@lgw01-23

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

System details:
```
kunal@hydrogen:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

Typically use Konsole (KDE). Also tried in a tty - the issue remains.

**Comment by Shougo** [comment]
Have you tested https://github.com/neovim/neovim/pull/6997?

**Comment by DarkDefender** [comment]
If anyone still has problem with this after you have tired  #6997 , let me know in that pull request.

**Comment by kunalg** [comment]
#6997 CI builds seem to have failed.
Anyway, will try to build it locally later.

**Comment by FabioAntunes** [comment]
@Shougo The builds have failed, it's safe to compile it anyway?

**Comment by DarkDefender** [comment]
@FabioAntunes I might be based, but it works fine on my system. I would really like if you could test it out.

I don't know why the builds fail. I can only see that travis complains about lint stuff. But the other two services I have a hard time to find what is going wrong.

**Comment by FabioAntunes** [comment]
@DarkDefender tried out your pull request, unfortunately still having issues:
```NVIM v0.2.1-534-g78869f239```
![screenshot from 2017-07-11 11 58 05](https://user-images.githubusercontent.com/2544673/28065591-2d816c1e-6631-11e7-9720-5194f9ba9b3b.png)

* Elementary OS (Ubuntu 14.04)
* Pantheon Terminal

**Comment by DarkDefender** [comment]
@FabioAntunes I guess this does not chage cursor shape if you run it outside of neovim?
`printf "\x1b[4 q"`

I'm also guessing `TERM` is set to xterm?
What is `VTE_VERSION` set to?

It sadly seems like Pantheon Terminal uses a old version of libvte. The problem seems to be that VTE versions this old do not support cursor shape changes with terminal codes. However by saying that they are xterm, terminal programs that uses terminfo or just checks TERM will think they do.

**Comment by FabioAntunes** [comment]
@DarkDefender sorry for the late reply
* TERM: `xterm`
* VTE_VERSION: 3409

![screenshot from 2017-07-11 15 35 18](https://user-images.githubusercontent.com/2544673/28073791-bf748f6c-664e-11e7-8ec7-0d61b13a0d1e.png)

**Comment by DarkDefender** [comment]
@FabioAntunes I've pushed an update that should fix it. Can you try it out?

**Comment by FabioAntunes** [comment]
@DarkDefender still having issues.. Is there something I can do to help you out?

**Comment by DarkDefender** [comment]
@FabioAntunes Ah, my bad. I did not think through my previous fix. It didn't really fix anything. Can you try again now? :P

**Comment by FabioAntunes** [comment]
@DarkDefender  it's working now, so far no strange characters

**Comment by FabioAntunes** [comment]
I will be using this build during the day I will let you know if I find something odd.

**Comment by tecywiz121** [comment]
For anyone using ppa:neovim-ppa/unstable, you can work around it with `:set guicursor=`

**Comment by michaelmior** [comment]
@DarkDefender I'm seeing the same issue as in [this comment](https://github.com/neovim/neovim/issues/7002#issuecomment-314411297), but unfortunately #6997 doesn't solve it for me.

**Comment by DarkDefender** [comment]
@michaelmior terminal and `TERM` ?

**Comment by DarkDefender** [comment]
nvm, saw your previous bug report

**Comment by DarkDefender** [comment]
@michaelmior what is `VTE_VERSION` set to?

**Comment by michaelmior** [comment]
@DarkDefender It's not set.

**Comment by DarkDefender** [comment]
So `echo $VTE_VERSION` returns nothing? Mate terminal is based on libvte so I would think that it would still be there.

If it is not, then I can sadly only suggest manually setting `:set guicursor=` in your init.vim or upgrading your Mate terminal version. 1.18 seems to be the latest one and I suspect that it should have a new enought version of libvte that this will not be a problem.

**Comment by DarkDefender** [comment]
Note that VTE_VERSION might not be there if you are using ssh

**Comment by michaelmior** [comment]
@DarkDefender Correct, I get nothing (and not using SSH). I have been considering upgrading to a newer version of MATE, although I may also just try a different terminal emulator to see if that helps.

**Comment by michaelmior** [comment]
As expected, `:set guicursor=` fixes the problem. This was previously solved with `NVIM_TUI_ENABLE_CURSOR_SHAPE` which is I see is now ignored. Unfortunately setting `guicursor` also  messes up the colors.

**Comment by DarkDefender** [comment]
Messes up the colors how?

**Comment by michaelmior** [comment]
I'll try to remember to post a screenshot in the morning when I'm back at my PC but the colours of everything in the UI is different and not matching my defined colour scheme.

**Comment by michaelmior** [comment]
@DarkDefender It seems that when I tried this morning, I'm not having the same issue so this solution seems to work. Changing the cursor shape never worked anyway. Thanks!

**Comment by michaelmior** [comment]
I can't seem to get the "bad" behaviour consistently, but here are before and after screenshots.

Before `set guicursor=`:
![guicursor](https://user-images.githubusercontent.com/82501/28170518-a80ef824-67b3-11e7-9331-e250c732b346.png)

After:
![noguicursor](https://user-images.githubusercontent.com/82501/28170510-9fb5dcf6-67b3-11e7-9b71-0d14bed56c86.png)

**Comment by DarkDefender** [comment]
Does this happen outside of tmux also?

**Comment by michaelmior** [comment]
No, I can't seem to reproduce this outside of tmux. Outside of tmux `TERM` is `xterm-256color` (and `screen-256color` inside tmux).

**Comment by DarkDefender** [comment]
Do you have true color switched on with `termguicolors`?

**Comment by michaelmior** [comment]
Nope, that's turned off.

**Comment by DarkDefender** [comment]
Does it still happen if you build neovim from this commit:
https://github.com/neovim/neovim/commit/69f0847ccc79acabb1cad5b1b54c906973946d81

I would also like if you could join the neovim IRC channel (freenode #neovim) so we can figure this out quickly.

**Comment by michaelmior** [comment]
It doesn't seem to, although I'm not convinced I know the steps to reproduce accurately. I'm on #neovim now.

**Comment by egmontkob** [comment]
Just for the record: the `$VTE_VERSION` variable was introduced in 3405 (well, vte-0.34.5 I mean). Whoever does not have this set in `mate-terminal` probably uses a gtk2-based version thereof.

**Comment by egmontkob** [comment]
... Oh, and vte's handling of unrecognized escape sequences [sucks](https://bugzilla.gnome.org/show_bug.cgi?id=403130).

**Comment by htfy96** [comment]
Guake depends on buggy `vte` which cannot handle cursor control sequence well even with the version in PR. 

Finally I switched to Tilda which depends on vte3.

**Comment by michaelmior** [comment]
@DarkDefender FYI, I haven't seen the colour issue again that I previously mentioned. However, I'm still seeing the unrecognized escape sequences being displayed even with `guicursor=`.

**Comment by DarkDefender** [comment]
@michaelmior Do you see any while inside neovim?

**Comment by michaelmior** [comment]
Yes. If I switch to a different tmux window and then come back.

**Comment by DarkDefender** [comment]
Does that happen if you are switching tmux windows regardless? Tmux also can try to change cursor shape.

If you do not get this when outside of tmux, then I don't think we can fix this from our side (but I could be wrong).

**Comment by michaelmior** [comment]
Unfortunately, I can't nail down under what circumstances this happens. I will note that if I create a new tmux window within a session that has this problem, switching to that window does not immediately produce this issue.

**Comment by DarkDefender** [comment]
I'm just taking a wild guess here. If it only triggers in tmux, then it might be because tmux tries to "restore" the cursor shape when switching between tmux windows. This is a tmux feature so that you can have different cursor shapes in different windows. You can also do the same with cursor colors.

This was introduced so that if you changed shape/color of the cursor it would be limited to that specific tmux window.

**Comment by michaelmior** [comment]
I have the following in `~/.tmux.conf` which suggested to me previously

```
set -g terminal-overrides "xterm*:XT:smcup@:rmcup@"                             
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
```

To be honest, I'm not entirely sure of the purpose of this but I assume it may be related.

**Comment by DarkDefender** [comment]
Ah, does it happen if you remove the "Ss and Se" line entirely?
Or if you do:
```
set -ga terminal-overrides ',*:Ss@:Se@'
```
?

The Ss and Se stuff is to a variable that says that your terminal supports changing cursor shapes using the specific codes that they are set to.

IIRC the `@` should unset them

**Comment by michaelmior** [comment]
Setting it and reloading my tmux config in an existing session didn't change anything, but I'll keep tabs on this and see if the behaviour changes. Thanks for the help unrelated to neovim :)

**Comment by thuandt** [comment]
@michaelmior did you solved this issue?

I use byobu with tmux backend and it happened since last month, I update nvim everyday but seem problem isn't fixed yet.

**Comment by michaelmior** [comment]
@thuandt Nope, no consistent solution yet for me.

**Comment by riddochc** [comment]
I'm having this issue in konsole 17.0.4.3, but not xterm 308.  My $TERM is xterm-256color.

Running ttyrec, the only place (besides when I exit nvim) that a 'q' shows up in the log is when  the following escape sequence is written:

\e [ 2 <space> q

I could be wrong about this, but i think the space causes the terminal to decide that the command has finished, and the following 'q' is treated as a character to display instead of part of the escape sequence.

I haven't bisected this, but I know the issue was introduced sometime since commit 26124b48.

**Comment by riddochc** [comment]
I just tried bisecting this issue, I was wrong in thinking the issue started at commit 26124b4, I had to go back further.  Git bisect reported this:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
1f3b5e1a826fbff8ce2fa84e0e50d082d65a08bd
6910bfee0fb9470b0b30e5a46efeebfe760e6a2c
We cannot bisect more!

I had to skip 1f3b5e1a because it segfaulted on startup, but given the nature of that change, I think we can conclude the issue was introduced in 6910bfee0.  Checking my versions again, it looks like I've been using neovim with unibilium-v1.2.0-7-g0dae863, which I installed last december, but there's only been 5 commits on unibilium since then, none of which touch code, so we can rule out the possibility of version differences there affecting this.

I'm pasting in my bisect log:

git bisect start
# bad: [27356de2697ca542ded05ea6c2017a3ca738084f] Merge pull request #7104 from jamessan/run-oldtests-under-headless
git bisect bad 27356de2697ca542ded05ea6c2017a3ca738084f
# good: [f0dafa89c2b7602cfedf0bd3409858e4c212b0a2] provider/clipboard.vim: Handle missing g:clipboard keys
git bisect good f0dafa89c2b7602cfedf0bd3409858e4c212b0a2
# bad: [105d680aea9f449c118520597a822e834a00c0ac] Merge #6816 'TUI improvements'
git bisect bad 105d680aea9f449c118520597a822e834a00c0ac
# bad: [cdfaecb25f6a9a94f29a38d9f2d24a579b3dff5f] tui: Eliminate more extraneous control sequences.
git bisect bad cdfaecb25f6a9a94f29a38d9f2d24a579b3dff5f
# skip: [5377de33ac4adea54c9c9980c7a6bc8cc70c0c7a] tui: Add st to the always 256-colour capable list. Also comment and augment some terminal colour tests.
git bisect skip 5377de33ac4adea54c9c9980c7a6bc8cc70c0c7a
# bad: [5265ac500064eecba3317ad8152cab14e9950db7] tui: Change terminal family recognition to avoid '+' entries. The terminfo commentary states that these are not standalone entries suitable for end-use.
git bisect bad 5265ac500064eecba3317ad8152cab14e9950db7
# good: [74472f7b2bf354dbffcaca3738dacba5dfaefd6d] tui: Fix conflict with predefined "linux" macro.
git bisect good 74472f7b2bf354dbffcaca3738dacba5dfaefd6d
# skip: [1f3b5e1a826fbff8ce2fa84e0e50d082d65a08bd] tui: Correct error in terminfo extension processing. Using the wrong unibilium query function just happened to work with the various terminfo records used in local testing.
git bisect skip 1f3b5e1a826fbff8ce2fa84e0e50d082d65a08bd
# good: [16300d02c7fbe95396697fc6c09012e2c2b47b69] tui: Improvements to RGB colour support. The details are in the on-line help under :help true-color .
git bisect good 16300d02c7fbe95396697fc6c09012e2c2b47b69
# bad: [6910bfee0fb9470b0b30e5a46efeebfe760e6a2c] tui: Correct error in terminfo extension processing. Using the right unibilium query function then revealed a latent NULL pointer problem.
git bisect bad 6910bfee0fb9470b0b30e5a46efeebfe760e6a2c
# good: [8768b7f4a045093001c55d12a85419bebe5869dc] tui: Remove now-unused flag variable. Follows on from fcf0d13f48bffbd41749069ce383d01153dd960c.
git bisect good 8768b7f4a045093001c55d12a85419bebe5869dc
# only skipped commits left to test
# possible first bad commit: [6910bfee0fb9470b0b30e5a46efeebfe760e6a2c] tui: Correct error in terminfo extension processing. Using the right unibilium query function then revealed a latent NULL pointer problem.
# possible first bad commit: [1f3b5e1a826fbff8ce2fa84e0e50d082d65a08bd] tui: Correct error in terminfo extension processing. Using the wrong unibilium query function just happened to work with the various terminfo records used in local testing.

**Comment by riddochc** [comment]
I should have tried this sooner... the :set guicursor= workaround works for me. Not ideal, I suppose, but I haven't really expected the cursor to be changing much, either.  I can try looking into this further and actually read some code instead of just poking at git, or test patches if someone else gets around to it before I do.

**Comment by wikimatze** [comment]
@riddochc thanks for the trick with `set guicursors=` that fixed the issue for me in normal terminal mode. When using tmux, I don't need this setting, but anyways, it is working now.

**Comment by frdeso** [comment]
I am having this issue on `nvim v0.2.2` on Terminator but not on Gnome-Terminal. `set guicursors=` fixes it.

**Comment by egmontkob** [comment]
@frdeso Probably you're using an old Terminator (version 1.0 or older) and hence an ancient VTE. You should upgrade to Terminator 1.91 or so.

**Comment by frdeso** [comment]
@egmontkob You are right. The [Ubuntu Xenial LTS package](https://packages.ubuntu.com/xenial/terminator) is on version 0.98.

**Comment by carmelo12341** [comment]
I think this issue is related.
Some charaters appear out of nowhere, most of them are "q"s
![selection_253](https://user-images.githubusercontent.com/9203764/34748933-faf6a994-f596-11e7-82b8-4a16426d0292.png)
Using `nvim v0.2.2` and Arch Linux
`set guicursor=` doesn't seem to work.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes
