### ISSUE TITLE
system([]) sometimes stops running commands until PATH changes

### ISSUE THREAD

**Issue by ZyX-II** [neovim/neovim#7377]
- `nvim --version`:  NVIM v0.2.1-871-g6c9183ae8 (latest chocolatey package), v0.2.1-955-g0a48388b3 (nightly release from releases page, win64 version)
- Operating system/version: windows 7 SP1, 64-bit
- Terminal name/version: nvim-qt

Can‘t say exactly what is the sequence of action, but after some time of Neovim running with full config it appears that starting from some point `system(['win32yank', '-o'])` and `system('win32yank -o')` start returning different results: specifically first returns an empty string (`systemlist()` does the same thing which AFAIK means that command not run, confirmed by v:shell_error set to -1).

`system(['echo', 'abc'])` still works though and while checking what may be that I found that

1. $PATH weirdly contains double semicolon followed by path to the “installation directory” where win32yank is located among other things. (“Installation directory” is mere an unpacked directory from archive.)
2. If I run `let $PATH=substitute($PATH, ';;', ';', 'g')` the problem is fixed.

No idea who is tainting the $PATH though, but pretty sure this is not something from my config: `vimg PATH $MYVIMRC/../**/*.vim` has only found vim-addon-manager actually doing anything with $PATH in a function which is clearly not called.

**Comment by ZyX-II** [comment]
(PS: this is the same person as @ZyX-I, I just do not like bringing my passwords to work and needed to post an issue. Do not add me as a contributor or whatever though.)

**Comment by ZyX-II** [comment]
Not so easy, `substitute()` does not actually work, so it should be something else going on which made `system([])` temporary working and then made it stop working again. I have an idea that “does not actually works” means “works only if that changed something”: i.e. what is needed is a *change*, not getting rid of an empty item from `$PATH`.

And what makes the matters worse, when such situation appears *clipboard provider does not error out*, instead it yields the last value pasted successfully.

**Comment by ZyX-I** [comment]
One of the latest observations is that appending a semicolon to `$PATH` which was previously subject to `substitute()` I mentioned earlier done in order to temporary fix the issue indeed fixes the issue once again after it reappears. So it looks like change in `$PATH` is necessary, hope this helps.

**Comment by justinmk** [comment]
> $PATH weirdly contains double semicolon followed by path to the “installation directory”

`os_setenv_append_path()` appends the installation directory on startup, but isn't called thereafter.

@ZyX-I Was this with neovim-qt or was it reproducible with nvim.exe? This has been reported in various forms before (e.g. https://github.com/neovim/neovim/issues/7000 ) but until now no one mentioned the double separator.

> appending a semicolon to $PATH which was previously subject to substitute() I mentioned earlier done in order to temporary fix the issue indeed fixes the issue once again after it reappears. So it looks like change in $PATH is necessary

Do you mean _any_ change will fix it? Or the specific change: "append semicolon" (which is different than the `subsitute()`)?

**Comment by ZyX-I** [comment]
I only checked changes “make double semicolon(s) single” and “append a semicolon”, both are fixing. Though I am not experiencing the problem for quite some time now.

**Comment by 0vercl0k** [comment]
I'm not sure this will help, but on my set-up I've found that my PATH variable is already ending with ';' (prior to starting neovim). When `os_setenv_append_path` appends the neovim directory it does it by concatenating the current PATH with ';dir' which is leaving my PATH with 'foo;;dir'. Maybe a better way is just to prepend the installation directory to the path..

I am working around this issue by making sure the PATH before starting neovim isn't terminated by a semicolon. It's been working for now but I need to test it a bit more; as usually I encounter this behavior at least once a day it shouldn't be too hard to see if it does it or not.

Cheers

**Comment by justinmk** [comment]
Can anyone reproduce this using the MSVC builds? To try the MSVC build, download "Neovim.zip" from one of these links:

- [MSVC win32](https://ci.appveyor.com/project/neovim/neovim/branch/master/job/kgr6oc8u9epd9noy/artifacts)
- [MSVC win64](https://ci.appveyor.com/project/neovim/neovim/branch/master/job/y8r5ug4h6m6u688d/artifacts)

**Comment by 0vercl0k** [comment]
I tried one of the win64 build out on Sunday, but unfortunately it kept
crashing for me (at least that's what nvim-qt was telling me). I'll give it
another shot tomorrow though.

Cheers

Le dim. 22 juil. 2018 à 10:53, Justin M. Keyes <notifications@github.com> a
écrit :

**Comment by justinmk** [comment]
@FelipeLema MSVC binaries are used for the release-page.

**Comment by janlazo** [comment]
Is this fixed now?

**Comment by justinmk** [comment]
Seemed to still happen for me a few months ago, I need to try with latest.

**Comment by justinmk** [comment]
@0vercl0k hoping you can confirm if https://github.com/neovim/neovim/commit/59712f6dbecfd9a7ccd021115170d1c9313b0969 fixes this issue.

**Comment by 0vercl0k** [comment]
Sorry Justin, I have moved away from Neovim so won't be able to try out the
fix.

Cheers

Le mar. 8 sept. 2020 à 20:48, Justin M. Keyes <notifications@github.com> a
écrit :
