### ISSUE TITLE
In NeoVim on WSL, when moving the screen, background color will not be reflected.

### ISSUE THREAD

**Issue by miyagaw61** [neovim/neovim#7634]
In NeoVim on WSL, when moving the screen with <C-e>, <C-y>, g, GG, and so on, the ctermbg of the highlight will not be reflected.

- `nvim --version`: v0.2.3-5-g7d24a95
- Vim (version: 8.0) behaves differently? yes
- Operating system/version: Ubuntu on WIndows 64bit (WSL)
- Terminal name/version: sorry, I don't know.
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
:set t_ut=
:highlight Normal ctermbg=21
<C-e>
<C-e>
<C-e>
```

### Actual behaviour

![Imgur](https://i.imgur.com/sPZDafr.png)

### Expected behaviour

![Imgur](https://i.imgur.com/pszYAAD.png)

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/7624 should fix this

**Comment by miyagaw61** [comment]
I should disable BCE?
I did `:set t_ut=` already.
Am I still not able to disable BCE?

**Comment by justinmk** [comment]
`set t_ut` is irreleveant in Nvim. Nvim does not support micro-managing terminfo. If you really want to do that, modify your actual terminfo.

But it doesn't matter anyways, because BCE is totally disabled by #7624 for everything except "true xterm" (i.e. when `$XTERM_VERSION` env var is defined, the terminal is assumed to be a "real" xterm).

So, did you try latest HEAD?

**Comment by miyagaw61** [comment]
yes.
I tried the following command.
```
git clone https://github.com/neovim/neovim.git $repos_path/neovim
cd $REPOS/neovim
yes | make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$bin_path/neovim"
yes | make install
```
Of course, `git diff ..origin/master` outputs anything.

**Comment by justinmk** [comment]
Need to be clear. Are you saying the problem still exists? And what is the exact `:version` ?

**Comment by miyagaw61** [comment]
Yes.
My NeoVim is HEAD but this problem is happening.
BCE is not disabled yet...?

`:version` outputs:
```
NVIM v0.2.3-5-g7d24a95
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/miyagaw61/repos/neovim/build/config -I/home/miyagaw61/repos/neovim/src -I/home/miyagaw61/repos/neovim/.deps/usr/include -I/home/miyagaw61/repos/neovim/.deps/usr/include -I/home/miyagaw61/repos/neovim/.deps/usr/include -I/home/miyagaw61/repos/neovim/.deps/usr/include -I/home/miyagaw61/repos/neovim/.deps/usr/include -I/home/miyagaw61/repos/neovim/.deps/usr/include -I/usr/include -I/home/miyagaw61/repos/neovim/build/src/nvim/auto -I/home/miyagaw61/repos/neovim/build/include
Compiled by root@mgpc

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/miyagaw61/bin/neovim/share/nvim"

Run :checkhealth for more info
```

`nvim -u NORC` -> `:checkhealth` outputs:
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized build-type. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $COLORTERM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - OK: pyenv found: "/mnt/c/Users/miyagaw61/home/.pyenv/libexec/pyenv"
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
    /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
    python2.6 not found in search path or not executable.
    /home/miyagaw61/.pyenv/shims/python is Python 3.6 and cannot provide Python 2.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /home/miyagaw61/.pyenv/shims/python is Python 3.6 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - OK: pyenv found: "/mnt/c/Users/miyagaw61/home/.pyenv/libexec/pyenv"
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /home/miyagaw61/.pyenv/versions/3.6.3/bin/python3
  - INFO: Python3 version: 3.6.3
  - INFO: python3-neovim version: 0.2.0
  - OK: Latest python3-neovim is installed: 0.2.0

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
  - WARNING: Missing "neovim" gem.
    - ADVICE:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Node provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.
```

**Comment by miyagaw61** [comment]
(I'm sorry, I pulled.)
