### ISSUE TITLE
Sticky characters in :terminal horizontal splits

### ISSUE THREAD

**Issue by bhrutledge** [neovim/neovim#7703]
I've been seeing sticky characters in a few situations, and I'm not sure they're all related, but this is the one I could reproduce. It doesn't seem to a problem when the terminal takes up the whole window, or is in a vertical split. `git bisect` says dbc25f5 is the first bad commit.

- `nvim --version`: 0.2.2
- Operating system/version: macOS 10.12.6
- Terminal name/version: iTerm2 3.15, Terminal.app 2.7.3, Hyper 1.4.8 
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:botright split | terminal
a
yarn add webpack
```

### Actual behaviour

```
├─ window-size@0.1.0                                                                       ]
├─ wordwrap@0.0.2       p                                                                  ]
├─ wrap-ansi@2.1.0
├─ wrappy@1.0.2
├─ xtend@4.0.1
├─ y18n@3.2.1
├─ yallist@2.1.2
├─ yargs-parser@7.0.0
└─ yargs@8.0.2
✨─ Done in 6.03s7   0

brian@bhr-macbook-air:~/Code/nvim-terminal-chars
$  D    i  6        0

brian@bhr-macbook-air:~/Code/nvim-terminal-chars
$  D    i  6        0

brian@bhr-macbook-air:~/Code/nvim-terminal-chars
$
```

### Expected behaviour

```
├─ window-size@0.1.0
├─ wordwrap@0.0.2
├─ wrap-ansi@2.1.0
├─ wrappy@1.0.2
├─ xtend@4.0.1
├─ y18n@3.2.1
├─ yallist@2.1.2
├─ yargs-parser@7.0.0
└─ yargs@8.0.2
✨─  Done in 5.30s.

brian@bhr-macbook-air:~/Code/nvim-terminal-chars
$

brian@bhr-macbook-air:~/Code/nvim-terminal-chars
$

brian@bhr-macbook-air:~/Code/nvim-terminal-chars
$
```

**Comment by justinmk** [comment]
Thanks for bisecting! This should have been fixed by https://github.com/neovim/neovim/pull/7676. Maybe you can try the development version, binaries are available at https://github.com/neovim/neovim/releases

**Comment by bhrutledge** [comment]
@justinmk The issue still exists in today's pre-release, as well as on a freshly pulled and compiled `master`. Can this issue be reopened?

**Comment by justinmk** [comment]
@bhrutledge could you see if this also happens with https://github.com/qvacua/vimr/releases  (no install required, just unzip the `.tar.bz2` file)? That will tell us if it's a TUI bug or a more general display bug.

Could be related to https://github.com/neovim/neovim/issues/4976

**Comment by bhrutledge** [comment]
It does not happen in VimR.

**Comment by dkarter** [comment]
I can confirm this issue in iTerm on macOS. It is also happening sometimes randomly and on code windows which can be a concern - it made me delete real code multiple times.

Here are some example videos demonstrating the issue:
https://www.dropbox.com/s/41wu9t0maw5yxyl/neovim%20bug.mp4?dl=0
https://www.dropbox.com/s/4uko7itsy91mpqf/neovim%20render%20bug.mp4?dl=0
https://www.dropbox.com/s/qklo2pasucjq3cn/neovim%20render%20bug%202.mp4?dl=0
https://www.dropbox.com/s/q2rmwb3ew0robve/neovim%20bug%203.mp4?dl=0

I can also confirm it is not happening in Vimr.

Thank you!

**Comment by justinmk** [comment]
@dkarter Please mention the exact version of Nvim that you are using.

**Comment by dkarter** [comment]
@justinmk Sorry I forgot to mention that. I am using the stable version of neovim v0.2.2.  I usually stick to stable versions since I am relying on NeoVim for my day to day work, but makes sense to check HEAD for bug reports. 

What are your plans for releasing v0.2.3? I imagine a lot of good work has gone into it including a lot of Vim upstream patches.

**Comment by justinmk** [comment]
See the milestones page .

**Comment by dkarter** [comment]
This is still happening in v0.2.3-dev on iTerm2 Build 3.1.5 (macOS) @justinmk 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/551858/38518187-ebbbbaf8-3c01-11e8-9dc7-57e5b483bd67.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/551858/38518201-f70ff310-3c01-11e8-9a64-ee159fe23d18.png">

**Comment by justinmk** [comment]
duplicate of https://github.com/neovim/neovim/issues/4976 , see https://github.com/neovim/neovim/issues/4976#issuecomment-230025307
