### ISSUE TITLE
Tab bar not redrawn after tall command output

### ISSUE THREAD

**Issue by frangio** [neovim/neovim#8557]
- NVIM v0.3.0-1287-gd2c460638
- Vim (version: 8.1) behaves correctly

### Steps to reproduce using `nvim -u NORC`

Open a terminal window that is only about 15 rows tall, so that the output of some command (we'll use `:version`) is taller than that.

```
nvim -u NORC
:tabe
:version
q
```

### Actual behaviour
Part of the command output is left over in the tab bar.

### Expected behaviour
The tab bar should be redrawn and shown again.

**Comment by bfredl** [comment]
Does this also happen in 0.3 final?

**Comment by justinmk** [comment]
Should be fixed. Upgrade to latest.

**Comment by frangio** [comment]
Oh, sorry. I thought I was running the release.

I can reproduce it in the 0.3.0 release as well as in the latest commit, though. Can we reopen this?

**Comment by frangio** [comment]
@justinmk I can still reproduce this on the latest build. Not on v0.2.3-1-gd6f9d1df0 (which oddly is the `appimage` version I downloaded from the v0.2.2 release).

**Comment by justinmk** [comment]
Should be fixed in HEAD.
