### ISSUE TITLE
neovim screen tearing when using youcompleteme in wsl(ubuntu)

### ISSUE THREAD

**Issue by noaRricky** [neovim/neovim#8752]
- `nvim --version`:NVIM v0.2.2 Build type: RelWithDebInfo LuaJIT 2.0.4
- Vim (version: ) behaves differently?vim(version 7.4) Works as expected;
- Operating system/version: windows sub linux ubuntu
- Terminal name/version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

- add to the init.vim file youcompleteme repo:

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'valloric/youcompleteme', { 'do': './install.py' }
call plug#end()
```

- PlugInstall;
- use nvim open a new python file
-  add code: import numpy as np
- type np.arr
- select array in pop up window and add brackets

### Actual behaviour

![error](https://user-images.githubusercontent.com/16248350/42807332-19bae5ee-89e3-11e8-8d6c-9f0b3dec00ef.png)

### Expected behaviour

![right](https://user-images.githubusercontent.com/16248350/42807391-424ae2d4-89e3-11e8-8ab9-c8adcadf17a8.png)

Actually, neovim pop up intellisence windows is much faster than vim, after fixing the problem I believe neovim must be a  really powerful tool

**Comment by KillTheMule** [comment]
First step you should upgrade to neovim 0.3. It hast been released for some weeks and contains a host of improvements.

**Comment by justinmk** [comment]
As @KillTheMule said, upgrade to 0.3. Also, we've had similar reports that were resolved by later version of https://github.com/mintty/wsltty

> Terminal name/version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

That's the shell, not the terminal. Need to know which terminal you're using.

**Comment by noaRricky** [comment]
Thanks. I have tried nvim 0.3.1 but still have the same problem

**Comment by justinmk** [comment]
But what about the other things.

**Comment by noaRricky** [comment]
I find wsl-terminal and solve the problem. Anyway thank you for your advice
