### ISSUE TITLE
teardown: race between init and exit_event

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8813]
Sometimes the asan CI job fails like this (e.g. [here](https://github.com/neovim/neovim/pull/7813#issuecomment-380949586) and [here](https://github.com/neovim/neovim/pull/8088#issuecomment-376312511)):

```
==================== File /home/travis/build/neovim/neovim/build/log/ubsan.16820 ====================
= =================================================================
= ==16820==ERROR: AddressSanitizer: SEGV on unknown address 0x000001baab50 (pc 0x00000044f3a1 bp 0x000000000001 sp 0x7fff7ddb6a60 T0)
= ==16820==The signal is caused by a WRITE memory access.
=     #0 0x44f3a0 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t> /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:90:10
=     #1 0x44f3a0 in AtomicallySetQuarantineFlagIfAllocated /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:520
=     #2 0x44f3a0 in __asan::Allocator::Deallocate(void*, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:597
=     #3 0x4ef316 in __interceptor_free /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:50:3
=     #4 0xfbfae4 in xfree /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:134:3
=     #5 0x120e948 in free_string_option /home/travis/build/neovim/neovim/build/../src/nvim/option.c:2207:5
=     #6 0x120de3d in free_all_options /home/travis/build/neovim/neovim/build/../src/nvim/option.c:923:9
=     #7 0xfc2441 in free_all_mem /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:622:3
=     #8 0x12bbe6c in mch_exit /home/travis/build/neovim/neovim/build/../src/nvim/os_unix.c:153:3
=     #9 0x1092cc3 in exit_event /home/travis/build/neovim/neovim/build/../src/nvim/msgpack_rpc/channel.c:542:5
=     #10 0xa6b2d3 in multiqueue_process_events /home/travis/build/neovim/neovim/build/../src/nvim/event/multiqueue.c:150:7
=     #11 0xa64e2f in loop_poll_events /home/travis/build/neovim/neovim/build/../src/nvim/event/loop.c:65:3
=     #12 0x12a4ec0 in os_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/os/input.c:162:5
=     #13 0x1035f07 in line_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/misc1.c:2692:5
=     #14 0x143ac50 in nfa_regmatch /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6203:5
=     #15 0x141b4d9 in nfa_regtry /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6272:16
=     #16 0x1419203 in nfa_regexec_both /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6440:12
=     #17 0x13c734d in nfa_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6593:10
=     #18 0x1379f20 in vim_regexec_both /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7250:16
=     #19 0x137ac07 in vim_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7302:10
=     #20 0x910f2b in f_split /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:15673:17
=     #21 0x829124 in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6368:11
=     #22 0x83d018 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6114:11
=     #23 0x8c57a1 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4218:15
=     #24 0x8c1d6b in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3915:7
=     #25 0x8bfa7f in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3766:7
=     #26 0x8bb29f in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3503:7
=     #27 0x8ba73c in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3421:7
=     #28 0x8b9bdc in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3352:7
=     #29 0x8212f1 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3279:7
=     #30 0x82071b in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3239:9
=     #31 0x82d088 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1485:9
=     #32 0xb69fc3 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2228:5
=     #33 0xb4c569 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:592:20
=     #34 0x85cbc5 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:21442:3
=     #35 0x828a4b in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6353:11
=     #36 0x83d018 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6114:11
=     #37 0x835fd4 in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2727:9
=     #38 0xb69fc3 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2228:5
=     #39 0xb4c569 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:592:20
=     #40 0xd2d506 in apply_autocmds_group /home/travis/build/neovim/neovim/build/../src/nvim/fileio.c:6933:5
=     #41 0xcf8ff6 in apply_autocmds /home/travis/build/neovim/neovim/build/../src/nvim/fileio.c:6576:10
=     #42 0x1168c78 in normal_check_text_changed /home/travis/build/neovim/neovim/build/../src/nvim/normal.c:1219:5
=     #43 0x11667d5 in normal_check /home/travis/build/neovim/neovim/build/../src/nvim/normal.c:1325:5
=     #44 0x17774c1 in state_enter /home/travis/build/neovim/neovim/build/../src/nvim/state.c:28:35
=     #45 0x10c0bf4 in normal_enter /home/travis/build/neovim/neovim/build/../src/nvim/normal.c:467:3
=     #46 0xea98a2 in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:566:3
=     #47 0x7fbb0a667f44 in __libc_start_main /build/eglibc-ripdx6/eglibc-2.19/csu/libc-start.c:287
=     #48 0x44e39b in _start (/home/travis/build/neovim/neovim/build/bin/nvim+0x44e39b)
= 
= AddressSanitizer can not provide additional info.
= SUMMARY: AddressSanitizer: SEGV /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:90:10 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>
= ==16820==ABORTING
=====================================================================================================
test/helpers.lua:149: assertion failed!
```

Possible cause:

-  Options init isn't complete, so `free_all_options` is free'ing something before it was alloc'd.
- stdio RPC channel was closed
    - was this because the client died from a invalid message?
-  `exit_event` is scheduled on `main_loop.fast_events`. 
    - is this necessary, or could we put it on `main_loop.events` instead? Then `os_breakcheck .. loop_poll_events`

**Comment by justinmk** [comment]
One of the `tui FocusGained/FocusLost ...` tests sometimes fails with "deadly signal". Usually there's no backtrace but recently there was this one:

```
Program terminated with signal SIGABRT, Aborted.
#0  0xf7f1dfe9 in __kernel_vsyscall ()
[Current thread is 1 (Thread 0xf77ffb40 (LWP 18226))]

Thread 2 (Thread 0xf7caf740 (LWP 18225)):
#0  0xf7f1dfe9 in __kernel_vsyscall ()
No symbol table info available.
#1  0xf7d60588 in _exit () from /lib32/libc.so.6
No symbol table info available.
#2  0xf7cdf72a in ?? () from /lib32/libc.so.6
No symbol table info available.
#3  0xf7cdf7cf in exit () from /lib32/libc.so.6
No symbol table info available.
#4  0x081b8519 in preserve_exit () at ../src/nvim/misc1.c:2652
        really_exiting = true
#5  0x081fae8d in deadly_signal (signum=1) at ../src/nvim/os/signal.c:137
No locals.
#6  0x081faef3 in on_signal (handle=0x846b4a0 <shup>, signum=1, data=0x0) at ../src/nvim/os/signal.c:162
        __PRETTY_FUNCTION__ = "on_signal"
        __func__ = "on_signal"
#7  0x08113382 in signal_event (argv=0xff7ffdb4) at ../src/nvim/event/signal.c:47
        watcher = 0x846b4a0 <shup>
#8  0x0811108e in multiqueue_process_events (this=0xf7816400) at ../src/nvim/event/multiqueue.c:150
        event = {handler = 0x8113358 <signal_event>, argv = {0x846b4a0 <shup>, 0x400, 0x0, 0x0, 0xff7fcac4, 0xc9fa74dd, 0x91, 0xff7fcb34, 0xa, 0x0}}
        __PRETTY_FUNCTION__ = "multiqueue_process_events"
#9  0x08110820 in loop_poll_events (loop=0x8470e60 <main_loop>, ms=10) at ../src/nvim/event/loop.c:66
        mode = UV_RUN_ONCE
        timeout_expired = false
#10 0x082a6d14 in ui_bridge_stop (b=0xf793f000) at ../src/nvim/ui_bridge.c:120
        bridge = 0xf793f000
        stopped = false
#11 0x082a4a5a in ui_builtin_stop () at ../src/nvim/ui.c:139
        ui = 0xf793f000
        i = 0
#12 0x081fbcdf in mch_exit (r=1) at ../src/nvim/os_unix.c:142
No locals.
#13 0x0818ee19 in getout (exitval=1) at ../src/nvim/main.c:703
        tp = 0x0
        next_tp = 0x0
#14 0x081b85df in preserve_exit () at ../src/nvim/misc1.c:2675
        really_exiting = true
#15 0x081f7fc3 in read_error_exit () at ../src/nvim/os/input.c:452
No locals.
#16 0x081f75f0 in os_inchar (buf=0x0, maxlen=0, ms=-1, tb_change_cnt=0) at ../src/nvim/os/input.c:142
        result = kInputEof
#17 0x0827ed69 in state_enter (s=0xff7fffdc) at ../src/nvim/state.c:55
        check_result = 1
        key = 58
        execute_result = 1
#18 0x081c4391 in normal_enter (cmdwin=false, noexmode=false) at ../src/nvim/normal.c:467
        state = {state = {check = 0x81c62ad <normal_check>, execute = 0x81c56e6 <normal_execute>}, conceal_old_cursor_line = 0, conceal_new_cursor_line = 0, command_finished = false, ctrl_w = false, need_flushbuf = false, conceal_update_lines = false, set_prevcount = false, previous_got_int = false, cmdwin = false, noexmode = false, toplevel = true, oa = {op_type = 0, regname = 0, motion_type = kMTCharWise, motion_force = 0, use_reg_one = false, inclusive = false, end_adjusted = false, start = {lnum = 0, col = 0, coladd = 0}, end = {lnum = 0, col = 0, coladd = 0}, cursor_start = {lnum = 0, col = 0, coladd = 0}, line_count = 0, empty = false, is_VIsual = false, start_vcol = 0, end_vcol = 0, prev_opcount = 0, prev_count0 = 0}, ca = {oap = 0xff7ffff8, prechar = 0, cmdchar = 0, nchar = 0, ncharC1 = 0, ncharC2 = 0, extra_char = 0, opcount = 0, count0 = 0, count1 = 0, arg = 0, retval = 0, searchbuf = 0x0}, mapped_len = 0, old_mapped_len = 0, idx = 60, c = 0, old_col = 0, old_pos = {lnum = 1, col = 0, coladd = 0}}
#19 0x0818ea35 in main (argc=7, argv=0xff800274) at ../src/nvim/main.c:598
        fname = 0x0
        params = {argc = 7, argv = 0xff800274, use_vimrc = 0xff800afa "NONE", n_commands = 0, commands = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, cmds_tofree = "\000\000\000\000\000\000\000\000\000", n_pre_commands = 1, pre_commands = {0xff800b0d "set shortmess+=I background=light noswapfile noautoindent laststatus=1 undodir=. directory=. viewdir=. backupdir=. belloff= noshowcmd noruler nomore", 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, edit_type = 0, tagname = 0x0, use_ef = 0x0, input_isatty = true, output_isatty = true, err_isatty = true, no_swap_file = 0, use_debug_break_level = -1, window_count = 1, window_layout = 0, diff_mode = 0, listen_addr = 0x0}
        cwd = 0x0
        __PRETTY_FUNCTION__ = "main"
        reading_tty = true
        reading_excmds = false
        early_ui = false

Thread 1 (Thread 0xf77ffb40 (LWP 18226)):
#0  0xf7f1dfe9 in __kernel_vsyscall ()
No symbol table info available.
#1  0xf7cdcd09 in raise () from /lib32/libc.so.6
No symbol table info available.
#2  0xf7cde207 in abort () from /lib32/libc.so.6
No symbol table info available.
#3  0x082dee91 in uv__signal_block_and_lock (saved_sigmask=saved_sigmask@entry=0xf77fedc0) at /home/travis/nvim-deps/build/src/libuv/src/unix/signal.c:144
        new_mask = {__val = {2147483647, 4294967294, 4294967295 <repeats 30 times>}}
#4  0x082df245 in uv__signal_stop (handle=handle@entry=0xf6c20cbc) at /home/travis/nvim-deps/build/src/libuv/src/unix/signal.c:548
        saved_sigmask = {__val = {0, 0, 4159973656, 137334933, 0, 4152356568, 0, 2, 4158221198, 138747904, 4157380405, 137256820, 15, 2, 0, 4152356352, 0, 0, 0, 2280519680, 138747904, 4139911396, 4152356784, 137200113, 4152356784, 0, 8199, 137241004, 138747904, 137200182, 138747904, 137241377}}
        first_handle = <optimized out>
        rem_oneshot = <optimized out>
        first_oneshot = <optimized out>
        ret = <optimized out>
#5  0x082e0275 in uv__signal_stop (handle=0xf6c20cbc) at /home/travis/nvim-deps/build/src/libuv/src/unix/signal.c:545
No locals.
#6  uv_signal_stop (handle=0xf6c20cbc) at /home/travis/nvim-deps/build/src/libuv/src/unix/signal.c:531
        __PRETTY_FUNCTION__ = "uv_signal_stop"
#7  0x0811332c in signal_watcher_stop (watcher=0xf6c20cbc) at ../src/nvim/event/signal.c:34
No locals.
#8  0x0829dab7 in tui_main (bridge=0xf793f000, ui=0xf7850280) at ../src/nvim/tui/tui.c:403
        tui_loop = {uv = {data = 0xf77fefb0, active_handles = 2, handle_queue = {0xf77ff114, 0xf6c2083c}, active_reqs = {unused = {0x0, 0x0}, count = 0}, stop_flag = 0, flags = 0, backend_fd = 15, pending_queue = {0xf77fefd4, 0xf77fefd4}, watcher_queue = {0xf77fefdc, 0xf77fefdc}, watchers = 0xf6c0c000, nwatchers = 30, nfds = 2, wq = {0xf77feff0, 0xf77feff0}, wq_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __kind = 0, __nusers = 0, {__elision_data = {__espins = 0, __elision = 0}, __list = {__next = 0x0}}}, __size = '\000' <repeats 23 times>, __align = 0}, wq_async = {data = 0x0, loop = 0xf77fefb0, type = UV_ASYNC, close_cb = 0x0, handle_queue = {0xf77ff2a0, 0xf77ff114}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 20, async_cb = 0x82e98c0 <uv__work_done>, queue = {0xf77ff2c4, 0xf77ff094}, pending = 0}, cloexec_lock = {__data = {__lock = 0, __nr_readers = 0, __readers_wakeup = 0, __writer_wakeup = 0, __nr_readers_queued = 0, __nr_writers_queued = 0, __flags = 0 '\000', __shared = 0 '\000', __rwelision = 0 '\000', __pad2 = 0 '\000', __writer = 0}, __size = '\000' <repeats 31 times>, __align = 0}, closing_handles = 0xf6c208a0, process_handles = {0xf77ff074, 0xf77ff074}, prepare_handles = {0xf77ff07c, 0xf77ff07c}, check_handles = {0xf77ff084, 0xf77ff084}, idle_handles = {0xf77ff08c, 0xf77ff08c}, async_handles = {0xf77ff044, 0xf77ff2c4}, async_unused = 0x0, async_io_watcher = {cb = 0x82d6820 <uv__async_io>, pending_queue = {0xf77ff0a4, 0xf77ff0a4}, watcher_queue = {0xf77ff0ac, 0xf77ff0ac}, pevents = 1, events = 1, fd = 18}, async_wfd = -1, timer_heap = {min = 0x0, nelts = 0}, timer_counter = 13, time = 624639, signal_pipefd = {16, 17}, signal_io_watcher = {cb = 0x82df8b0 <uv__signal_event>, pending_queue = {0xf77ff0e8, 0xf77ff0e8}, watcher_queue = {0xf77ff0f0, 0xf77ff0f0}, pevents = 1, events = 1, fd = 16}, child_watcher = {data = 0x0, loop = 0xf77fefb0, type = UV_SIGNAL, close_cb = 0x0, handle_queue = {0xf77ff020, 0xf77fefb8}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 16, signal_cb = 0x0, signum = 0, tree_entry = {rbe_left = 0x0, rbe_right = 0x0, rbe_parent = 0x0, rbe_color = 0}, caught_signals = 0, dispatched_signals = 0}, emfile_fd = 19, inotify_read_watcher = {cb = 0x0, pending_queue = {0x0, 0x0}, watcher_queue = {0x0, 0x0}, pevents = 0, events = 0, fd = 0}, inotify_watchers = 0x0, inotify_fd = -1}, events = 0xf6c0f000, thread_events = 0xf6c0f040, fast_events = 0xf6c0f020, children = 0xf6c0d000, children_watcher = {data = 0xf7f42000, loop = 0xf77fefb0, type = UV_SIGNAL, close_cb = 0xf7cb4f12, handle_queue = {0xf77ff1f0, 0xf77ff2a0}, u = {fd = -137653816, reserved = {0xf7cb91c8, 0x542140c, 0xf7f3ba94, 0xf77ff260}}, next_closing = 0x0, flags = 8, signal_cb = 0xf7f3ba94, signum = 0, tree_entry = {rbe_left = 0xf7f399d3, rbe_right = 0xf7e82638, rbe_parent = 0x0, rbe_color = 0}, caught_signals = 0, dispatched_signals = 0}, children_kill_timer = {data = 0xf7f27fc9, loop = 0xf77fefb0, type = UV_TIMER, close_cb = 0xf77ff268, handle_queue = {0xf77ff248, 0xf77ff1a0}, u = {fd = -135389264, reserved = {0xf7ee1fb0, 0xf77ff268, 0xf7f42a74, 0x7}}, next_closing = 0x0, flags = 8, timer_cb = 0x0, heap_node = {0x1, 0xf7f19450, 0x5}, timeout = 4294967296, repeat = 0, start_id = 0}, poll_timer = {data = 0xf6c0e008, loop = 0xf77fefb0, type = UV_TIMER, close_cb = 0xf7f19450, handle_queue = {0xf6c20c6c, 0xf77ff1f0}, u = {fd = 0, reserved = {0x0, 0xf77ff2f4, 0xf77ff270, 0xf7ee3698}}, next_closing = 0x0, flags = 8, timer_cb = 0x8110cdb <timer_cb>, heap_node = {0x0, 0x0, 0x0}, timeout = 624659, repeat = 20, start_id = 12}, async = {data = 0x0, loop = 0xf77fefb0, type = UV_ASYNC, close_cb = 0x0, handle_queue = {0xf77ff1a0, 0xf77ff020}, u = {fd = 5, reserved = {0x5, 0xf7f19450, 0xf7efb034, 0xf7f2d8a2}}, next_closing = 0x0, flags = 12, async_cb = 0x8110c13 <async_cb>, queue = {0xf77ff094, 0xf77ff044}, pending = 0}, mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __kind = 0, __nusers = 0, {__elision_data = {__espins = 0, __elision = 0}, __list = {__next = 0x0}}}, __size = '\000' <repeats 23 times>, __align = 0}, recursive = 0}
        data = 0xf6c10780
#9  0x082a6c37 in ui_thread_run (data=0xf793f000) at ../src/nvim/ui_bridge.c:102
        bridge = 0xf793f000
#10 0xf7ee726a in start_thread (arg=0xf77ffb40) at pthread_create.c:333
        __res = <optimized out>
        pd = 0xf77ffb40
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {-135286784, 0, 4001536, -142609432, 1758915627, 1272243242}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#11 0xf7d9641e in clone () from /lib32/libc.so.6
No symbol table info available.


Tests covered by this check: 13
test/helpers.lua:292: crash detected (see above)

stack traceback:
	test/helpers.lua:292: in function 'check_cores'
	test/functional/helpers.lua:759: in function <test/functional/helpers.lua:754>
```

**Comment by blueyed** [comment]
Is this the same issue?  (https://travis-ci.org/neovim/neovim/jobs/546346300, https://api.travis-ci.org/v3/job/546346300/log.txt)
```
[32m[2m[ RUN      ][0m[0m :Man man.lua: highlight_line() clears backspaces from text and adds highlights: [2m20.11 ms[0m [1m[32mOK[0m[0m
==================== File /home/travis/build/neovim/neovim/build/log/ubsan.16304 ====================
= =================================================================
= ==16304==ERROR: AddressSanitizer: SEGV on unknown address 0x000001ea8d10 (pc 0x000000457551 bp 0x7fff07b1cc30 sp 0x7fff07b1cbc0 T0)
= ==16304==The signal is caused by a WRITE memory access.
=     #0 0x457550 in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) (/home/travis/build/neovim/neovim/build/bin/nvim+0x457550)
=     #1 0x50aa0c in __interceptor_cfree.localalias.0 (/home/travis/build/neovim/neovim/build/bin/nvim+0x50aa0c)
=     #2 0x112d234 in xfree /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:118:3
=     #3 0x13ba658 in free_string_option /home/travis/build/neovim/neovim/build/../src/nvim/option.c:2299:5
=     #4 0x13b9d75 in free_all_options /home/travis/build/neovim/neovim/build/../src/nvim/option.c:967:9
=     #5 0x112f557 in free_all_mem /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:649:3
=     #6 0x146c12c in mch_exit /home/travis/build/neovim/neovim/build/../src/nvim/os_unix.c:102:3
=     #7 0x1217ba3 in exit_event /home/travis/build/neovim/neovim/build/../src/nvim/msgpack_rpc/channel.c:557:5
=     #8 0xb8371c in multiqueue_process_events /home/travis/build/neovim/neovim/build/../src/nvim/event/multiqueue.c:150:7
=     #9 0xb7c1fa in loop_poll_events /home/travis/build/neovim/neovim/build/../src/nvim/event/loop.c:66:3
=     #10 0x1453e03 in os_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/os/input.c:167:5
=     #11 0x11acc47 in line_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/misc1.c:2738:5
=     #12 0x15e702f in nfa_regmatch /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6252:5
=     #13 0x15c5098 in nfa_regtry /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6326:16
=     #14 0x15c344c in nfa_regexec_both /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6496:12
=     #15 0x157c4e3 in nfa_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6642:10
=     #16 0x153221e in vim_regexec_string /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7241:16
=     #17 0x15330e7 in vim_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7293:10
=     #18 0xa63a0b in find_some_match /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:12696:15
=     #19 0x9d2027 in f_matchstr /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:12974:3
=     #20 0x907827 in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6425:11
=     #21 0x91caf3 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6167:11
=     #22 0x9ac591 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4270:15
=     #23 0x9a8b33 in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3967:7
=     #24 0x9a62a7 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3815:7
=     #25 0x9a15af in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3551:7
=     #26 0x9a0a8c in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3469:7
=     #27 0x99ff5c in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3400:7
=     #28 0x8ffc42 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3327:7
=     #29 0x9003c0 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3366:9
=     #30 0x8ff05a in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3287:9
=     #31 0x90bedf in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1508:9
=     #32 0xc8e0ee in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2248:5
=     #33 0xc6c390 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #34 0x93d890 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22424:3
=     #35 0x90714b in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6410:11
=     #36 0x91caf3 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6167:11
=     #37 0x9ac591 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4270:15
=     #38 0x9a8b33 in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3967:7
=     #39 0x9a62a7 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3815:7
=     #40 0x9a15af in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3551:7
=     #41 0x9a0a8c in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3469:7
=     #42 0x99ff5c in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3400:7
=     #43 0x8ffc42 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3327:7
=     #44 0x8ff05a in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3287:9
=     #45 0x90fea4 in eval_for_line /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2539:7
=     #46 0xd3bda2 in ex_while /home/travis/build/neovim/neovim/build/../src/nvim/ex_eval.c:967:14
=     #47 0xc8e0ee in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2248:5
=     #48 0xc6c390 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #49 0x93d890 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22424:3
=     #50 0x90714b in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6410:11
=     #51 0x91caf3 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6167:11
=     #52 0x9ac591 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4270:15
=     #53 0x9a8b33 in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3967:7
=     #54 0x9a62a7 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3815:7
=     #55 0x9a15af in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3551:7
=     #56 0x9a0a8c in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3469:7
=     #57 0x99ff5c in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3400:7
=     #58 0x8ffc42 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3327:7
=     #59 0x8ff05a in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3287:9
=     #60 0x90bedf in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1508:9
=     #61 0xc8e0ee in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2248:5
=     #62 0xc6c390 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #63 0x93d890 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22424:3
=     #64 0x90714b in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6410:11
=     #65 0x91caf3 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6167:11
=     #66 0x91567e in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2764:9
=     #67 0xc8e0ee in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2248:5
=     #68 0xc6c390 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #69 0xc519f0 in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3228:3
=     #70 0xc4c24e in source_callback /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2368:9
=     #71 0xc4bb04 in do_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2446:15
=     #72 0xc4bf0b in do_in_path_and_pp /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2490:12
=     #73 0xc4c221 in source_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2538:10
=     #74 0x100296e in load_plugins /home/travis/build/neovim/neovim/build/../src/nvim/main.c:1358:5
=     #75 0xff46d7 in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:389:3
=     #76 0x7fd3f1ed382f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
=     #77 0x452568 in _start (/home/travis/build/neovim/neovim/build/bin/nvim+0x452568)
= 
= AddressSanitizer can not provide additional info.
= SUMMARY: AddressSanitizer: SEGV (/home/travis/build/neovim/neovim/build/bin/nvim+0x457550) in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType)
= ==16304==ABORTING
=====================================================================================================
test/helpers.lua:152: assertion failed!

stack traceback:
	test/helpers.lua:152: in function 'check_logs'
	test/functional/helpers.lua:840: in function <test/functional/helpers.lua:836>
```

**Comment by justinmk** [comment]
@blueyed yes

**Comment by blueyed** [comment]
For reference: I've seen this only/mostly with/after the ":Man man.lua: highlight_line() clears backspaces from text and adds highlights" test.

**Comment by justinmk** [comment]
Happening frequently now. Stacktrace is somewhat different: during startup, involving `load_plugins .. f_matchstr` instead of `apply_autocmds  .. f_split`.

https://github.com/neovim/neovim/pull/10683#issuecomment-517941712

> Is it really the same failure? Here we are asking nvim to quit even before VimEnter. I suspect this is caused by effectively `clear() ` twice in a row without using the instance in between.
> 
> Maybe we can get rid of that.

```
[----------] Running tests from test/functional/plugin/man_spec.lua
[ RUN      ] :Man man.lua: highlight_line() clears backspaces from text and adds highlights: 18.14 ms OK
==================== File /home/travis/build/neovim/neovim/build/log/ubsan.16389 ====================
= =================================================================
= ==16389==ERROR: AddressSanitizer: SEGV on unknown address 0x000001d548d0 (pc 0x000000455084 bp 0x000000000000 sp 0x7ffe628bb830 T0)
= ==16389==The signal is caused by a WRITE memory access.
=     #0 0x455083 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t> /tmp/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81:10
=     #1 0x455083 in AtomicallySetQuarantineFlagIfAllocated /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:554
=     #2 0x455083 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:631
=     #3 0x4fb97b in __interceptor_free /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:129:3
=     #4 0x1066974 in xfree /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:119:3
=     #5 0x12c54b8 in free_string_option /home/travis/build/neovim/neovim/build/../src/nvim/option.c:2306:5
=     #6 0x12c49dd in free_all_options /home/travis/build/neovim/neovim/build/../src/nvim/option.c:969:9
=     #7 0x1069609 in free_all_mem /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:650:3
=     #8 0x1378f95 in mch_exit /home/travis/build/neovim/neovim/build/../src/nvim/os_unix.c:102:3
=     #9 0x114608d in exit_event /home/travis/build/neovim/neovim/build/../src/nvim/msgpack_rpc/channel.c:557:5
=     #10 0xb02c8e in multiqueue_process_events /home/travis/build/neovim/neovim/build/../src/nvim/event/multiqueue.c:150:7
=     #11 0xafc087 in loop_poll_events /home/travis/build/neovim/neovim/build/../src/nvim/event/loop.c:66:3
=     #12 0x1360f73 in os_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/os/input.c:167:5
=     #13 0x10e5f49 in line_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/misc1.c:2747:5
=     #14 0x14ffb14 in nfa_regmatch /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6316:5
=     #15 0x14e01bb in nfa_regtry /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6390:16
=     #16 0x14ddef2 in nfa_regexec_both /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6560:12
=     #17 0x148bf28 in nfa_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6706:10
=     #18 0x143f5a7 in vim_regexec_string /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7250:16
=     #19 0x1440287 in vim_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7302:10
=     #20 0xa05c13 in find_some_match /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:12952:15
=     #21 0x96fb85 in f_matchstr /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:13230:3
=     #22 0x8a5160 in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6536:11
=     #23 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
=     #24 0x948a68 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
=     #25 0x94509a in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
=     #26 0x942b65 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
=     #27 0x93e35b in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
=     #28 0x93d7f3 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
=     #29 0x93cca3 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
=     #30 0x89e648 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
=     #31 0x89ee16 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3489:9
=     #32 0x89da72 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
=     #33 0x8a93c0 in ex_let_const /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1590:9
=     #34 0x8a9886 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1531:3
=     #35 0xbfd379 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
=     #36 0xbdf488 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #37 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
=     #38 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
=     #39 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
=     #40 0x948a68 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
=     #41 0x94509a in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
=     #42 0x942b65 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
=     #43 0x93e35b in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
=     #44 0x93d7f3 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
=     #45 0x93cca3 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
=     #46 0x89e648 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
=     #47 0x89da72 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
=     #48 0x8aa093 in eval_for_line /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2662:7
=     #49 0xca28f5 in ex_while /home/travis/build/neovim/neovim/build/../src/nvim/ex_eval.c:967:14
=     #50 0xbfd379 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
=     #51 0xbdf488 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #52 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
=     #53 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
=     #54 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
=     #55 0x948a68 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
=     #56 0x94509a in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
=     #57 0x942b65 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
=     #58 0x93e35b in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
=     #59 0x93d7f3 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
=     #60 0x93cca3 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
=     #61 0x89e648 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
=     #62 0x89da72 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
=     #63 0x8a93c0 in ex_let_const /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1590:9
=     #64 0x8a9886 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1531:3
=     #65 0xbfd379 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
=     #66 0xbdf488 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #67 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
=     #68 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
=     #69 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
=     #70 0x8b0c5e in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2887:9
=     #71 0xbfd379 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
=     #72 0xbdf488 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #73 0xbc59a8 in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3230:3
=     #74 0xbc05ae in source_callback /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2365:9
=     #75 0xbbfe05 in do_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2443:15
=     #76 0xbc026b in do_in_path_and_pp /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2487:12
=     #77 0xbc0581 in source_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2535:10
=     #78 0xf46b7e in load_plugins /home/travis/build/neovim/neovim/build/../src/nvim/main.c:1354:5
=     #79 0xf38926 in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:384:3
=     #80 0x7f680566482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
=     #81 0x453db8 in _start (/home/travis/build/neovim/neovim/build/bin/nvim+0x453db8)
= 
= AddressSanitizer can not provide additional info.
= SUMMARY: AddressSanitizer: SEGV /tmp/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81:10 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>
= ==16389==ABORTING
=====================================================================================================
test/helpers.lua:156: assertion failed!

stack traceback:
	test/helpers.lua:156: in function 'check_logs'
	test/functional/helpers.lua:864: in function <test/functional/helpers.lua:860>
```

**Comment by blueyed** [comment]
Fixed in d4a0b6c4e?  Or only the later/newer one?

**Comment by justinmk** [comment]
The core problem still is not fixed, though we know how to avoid it thanks to @bfredl.

**Comment by justinmk** [comment]
Fixed in d4a0b6c4e1d78f19bf5879b113c5252d5a4f2e5c  for `man_spec.lua`. 

Another test is sometimes triggering this issue:

```
[32m[2m[ RUN      ][0m[0m plugin/shada.vim event SourceCmd works: [2m55.50 ms[0m [1m[32mOK[0m[0m
==================== File /home/travis/build/neovim/neovim/build/log/ubsan.18013 ====================
= =================================================================
= ==18013==ERROR: AddressSanitizer: SEGV on unknown address 0x000001d5d310 (pc 0x0000004551d4 bp 0x000000000000 sp 0x7ffe3d8377b0 T0)
= ==18013==The signal is caused by a WRITE memory access.
=     #0 0x4551d3 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t> /tmp/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81:10
=     #1 0x4551d3 in AtomicallySetQuarantineFlagIfAllocated /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:554
=     #2 0x4551d3 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:631
=     #3 0x4fbacb in __interceptor_free /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:129:3
=     #4 0x106e7d4 in xfree /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:119:3
=     #5 0x12cd6b8 in free_string_option /home/travis/build/neovim/neovim/build/../src/nvim/option.c:2306:5
=     #6 0x12ccbdd in free_all_options /home/travis/build/neovim/neovim/build/../src/nvim/option.c:969:9
=     #7 0x1071469 in free_all_mem /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:650:3
=     #8 0x1381195 in mch_exit /home/travis/build/neovim/neovim/build/../src/nvim/os_unix.c:102:3
=     #9 0x114e28d in exit_event /home/travis/build/neovim/neovim/build/../src/nvim/msgpack_rpc/channel.c:557:5
=     #10 0xb08cbe in multiqueue_process_events /home/travis/build/neovim/neovim/build/../src/nvim/event/multiqueue.c:150:7
=     #11 0xb020b7 in loop_poll_events /home/travis/build/neovim/neovim/build/../src/nvim/event/loop.c:66:3
=     #12 0x1369173 in os_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/os/input.c:167:5
=     #13 0x10ee149 in line_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/misc1.c:2750:5
=     #14 0x1507d14 in nfa_regmatch /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6316:5
=     #15 0x14e83bb in nfa_regtry /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6390:16
=     #16 0x14e60f2 in nfa_regexec_both /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6560:12
=     #17 0x1494128 in nfa_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6706:10
=     #18 0x14477a7 in vim_regexec_string /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7250:16
=     #19 0x1448487 in vim_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7302:10
=     #20 0xa0bc43 in find_some_match /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:12985:15
=     #21 0x975875 in f_matchstr /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:13263:3
=     #22 0x8aa3c0 in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6536:11
=     #23 0x8bcfc7 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
=     #24 0x94dcc8 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
=     #25 0x94a2fa in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
=     #26 0x947dc5 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
=     #27 0x9435bb in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
=     #28 0x942a53 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
=     #29 0x941f03 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
=     #30 0x8a38a8 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
=     #31 0x8a4076 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3489:9
=     #32 0x8a2cd2 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
=     #33 0x8ae620 in ex_let_const /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1590:9
=     #34 0x8aeae6 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1531:3
=     #35 0xc033a9 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
=     #36 0xbe54b8 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #37 0x8dd2b6 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22822:3
=     #38 0x8a9ccd in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
=     #39 0x8bcfc7 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
=     #40 0x94dcc8 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
=     #41 0x94a2fa in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
=     #42 0x947dc5 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
=     #43 0x9435bb in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
=     #44 0x942a53 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
=     #45 0x941f03 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
=     #46 0x8a38a8 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
=     #47 0x8a2cd2 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
=     #48 0x8af2f3 in eval_for_line /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2662:7
=     #49 0xca8925 in ex_while /home/travis/build/neovim/neovim/build/../src/nvim/ex_eval.c:967:14
=     #50 0xc033a9 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
=     #51 0xbe54b8 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #52 0x8dd2b6 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22822:3
=     #53 0x8a9ccd in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
=     #54 0x8bcfc7 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
=     #55 0x94dcc8 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
=     #56 0x94a2fa in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
=     #57 0x947dc5 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
=     #58 0x9435bb in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
=     #59 0x942a53 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
=     #60 0x941f03 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
=     #61 0x8a38a8 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
=     #62 0x8a2cd2 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
=     #63 0x8ae620 in ex_let_const /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1590:9
=     #64 0x8aeae6 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1531:3
=     #65 0xc033a9 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
=     #66 0xbe54b8 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #67 0x8dd2b6 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22822:3
=     #68 0x8a9ccd in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
=     #69 0x8bcfc7 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
=     #70 0x8b5ebe in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2887:9
=     #71 0xc033a9 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
=     #72 0xbe54b8 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #73 0xbcb9d8 in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3230:3
=     #74 0xbc65de in source_callback /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2365:9
=     #75 0xbc5e35 in do_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2443:15
=     #76 0xbc629b in do_in_path_and_pp /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2487:12
=     #77 0xbc65b1 in source_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2535:10
=     #78 0xf4d35e in load_plugins /home/travis/build/neovim/neovim/build/../src/nvim/main.c:1354:5
=     #79 0xf3f106 in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:384:3
=     #80 0x7f6a609d182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
=     #81 0x453f08 in _start (/home/travis/build/neovim/neovim/build/bin/nvim+0x453f08)
= 
= AddressSanitizer can not provide additional info.
= SUMMARY: AddressSanitizer: SEGV /tmp/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81:10 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>
= ==18013==ABORTING
=====================================================================================================
test/helpers.lua:156: assertion failed!

stack traceback:
	test/helpers.lua:156: in function 'check_logs'
	test/functional/helpers.lua:864: in function <test/functional/helpers.lua:860>
```

**Comment by justinmk** [comment]
Haven't seen this in a long time, and there have been many lifecycle adjustments.
