### ISSUE TITLE
MANPAGER text not processed

### ISSUE THREAD

**Issue by mustaqimM** [neovim/neovim#9120]
- `nvim --version`: `v0.3.1`
- Vim (version: ) behaves differently?
- Operating system/version: `void linux 4.18.13_1`
- Terminal name/version: `kitty 0.12.3`
- `$TERM`: `xterm-kitty`

### Steps to reproduce using `nvim -u NORC`

```
set -gx MANPAGER  nvim -c "set ft=man"
man ranger
```

### Actual behaviour
Man pages have `^H` between words when invoking `man ranger`. `$MANPAGER` is set as `nvim -c "set ft=man" -`. This doesn't occur if I use it like this: `man ranger | nvim -c "set ft=man" -`
See here:
https://i.imgur.com/GTaY8Yg.png

I should note that void uses `mdocml` and not `man-db`

```bash
RANGER(1)                        ranger manual                       RANGER(1)



N^HNA^HAM^HME^HE
       ranger - visual file manager

S^HSY^HYN^HNO^HOP^HPS^HSI^HIS^HS
       r^Hra^Han^Hng^Hge^Her^Hr [-^H--^H-v^Hve^Her^Hrs^Hsi^Hio^Hon^Hn] [-^H--^H-h^Hhe^Hel^Hlp^Hp] [-^H--^H-d^Hde^Heb^Hbu^Hug^Hg] [-^H--^H-c^Hcl^Hle^Hea^Han^Hn] [-^H--^
H-c^Hca^Hac^Hch^Hhe^Hed^Hdi^Hir^Hr=_^Hd_^Hi_^Hr_^He_^Hc_^Ht_^Ho_^Hr_^Hy]
       [-^H--^H-c^Hco^Hon^Hnf^Hfd^Hdi^Hir^Hr=_^Hd_^Hi_^Hr_^He_^Hc_^Ht_^Ho_^Hr_^Hy] [-^H--^H-d^Hda^Hat^Hta^Had^Hdi^Hir^Hr=_^Hd_^Hi_^Hr_^He_^Hc_^Ht_^Ho_^Hr_^Hy] [-^H--^H
-c^Hco^Hop^Hpy^Hy-^H-c^Hco^Hon^Hnf^Hfi^Hig^Hg=_^Hw_^Hh_^Hi_^Hc_^Hh]
       [-^H--^H-c^Hch^Hho^Hoo^Hos^Hse^Hef^Hfi^Hil^Hle^He=_^Ht_^Ha_^Hr_^Hg_^He_^Ht] [-^H--^H-c^Hch^Hho^Hoo^Hos^Hse^Hef^Hfi^Hil^Hle^Hes^Hs=_^Ht_^Ha_^Hr_^Hg_^He_^Ht] [-^H
--^H-c^Hch^Hho^Hoo^Hos^Hse^Hed^Hdi^Hir^Hr=_^Ht_^Ha_^Hr_^Hg_^He_^Ht]
       [-^H--^H-s^Hse^Hel^Hle^Hec^Hct^Htf^Hfi^Hil^Hle^He=_^Hf_^Hi_^Hl_^He_^Hp_^Ha_^Ht_^Hh] [-^H--^H-s^Hsh^Hho^How^Hw-^H-o^Hon^Hnl^Hly^Hy-^H-d^Hdi^Hir^Hrs^Hs] [-^H--^H-
l^Hli^His^Hst^Ht-^H-u^Hun^Hnu^Hus^Hse^Hed^Hd-^H-k^Hke^Hey^Hys^Hs]
       [-^H--^H-l^Hli^His^Hst^Ht-^H-t^Hta^Hag^Hgg^Hge^Hed^Hd-^H-f^Hfi^Hil^Hle^Hes^Hs=_^Ht_^Ha_^Hg] [-^H--^H-p^Hpr^Hro^Hof^Hfi^Hil^Hle^He] [-^H--^H-c^Hcm^Hmd^Hd=_^Hc_^H
o_^Hm_^Hm_^Ha_^Hn_^Hd] [_^Hp_^Ha_^Ht_^Hh _^H._^H._^H.]

D^HDE^HES^HSC^HCR^HRI^HIP^HPT^HTI^HIO^HON^HN
       ranger is a console file manager with VI key bindings.

R^HRE^HES^HSO^HOU^HUR^HRC^HCE^HES^HS
       _^HT_^Hh_^Hi_^Hs _^Hm_^Ha_^Hn_^Hu_^Ha_^Hl contains instructions on how to use and configure ranger.

       _^HI_^Hn_^Hs_^Hi_^Hd_^He _^Hr_^Ha_^Hn_^Hg_^He_^Hr, you can press _^H? for a list of key bindings, commands or
       settings.

       The _^HR_^HE_^HA_^HD_^HM_^HE contains install instructions.

       The file _^HH_^HA_^HC_^HK_^HI_^HN_^HG_^H._^Hm_^Hd contains guidelines for code modification.

       The directory _^Hd_^Ho_^Hc_^H/_^Hc_^Ho_^Hn_^Hf_^Hi_^Hg_^Hs contains configuration files.  They are
/tmp/man.XXXXbHKecE                                                                                                                                  1,1            Top
```

**Comment by justinmk** [comment]
Does it happen with  `:Man ranger`  ?

**Comment by mustaqimM** [comment]
No it doesn't

**Comment by justinmk** [comment]
Sounds like an initialization issue. This might have been fixed on HEAD/0.3.2.

**Comment by justinmk** [comment]
Does it happen if you set MANPAGER to start nvim without user config?

    export MANPAGER='nvim -u NORC -c "set ft=man"'

**Comment by mustaqimM** [comment]
Ya, it still occurs. It's like the terminal on the right of the pic I linked

**Comment by justinmk** [comment]
This might have been fixed in the development version (0.3.2). If not, I can't reproduce it, so we need your help (send a patch).

> I should note that void uses mdocml and not man-db

That shouldn't matter since `:Man` works for you.

**Comment by mustaqimM** [comment]
On `0.3.2` it still occurs.

**Comment by justinmk** [comment]
@tweekmonster Nice analysis! We can almost eliminate the whitespace like this (note that `-` arg is not required to consume stdin in Nvim 0.3.1+):

    export MANPAGER="nvim +'set ft=man'"

We could work around this issue by making `:Man!` (with bang) do `:set ft=man`. Then users don't need a separate shell script:

    export MANPAGER="nvim +Man!"

**Comment by justinmk** [comment]
@mustaqimM can you try https://github.com/neovim/neovim/pull/9139

**Comment by tweekmonster** [comment]
> Nice analysis!

Thanks!

> note that - arg is not required to consume stdin in Nvim 0.3.1+

I noticed, but without it, it changes the behavior of nvim: The man page content is still in buffer 2, but the blank `ft=man"` file is displayed when nvim loads.

> We could work around this issue by making :Man! (with bang) do :set ft=man.

That would be a decent workaround in this scenario.  Though, I think it'd be cleaner if it can be done without the bang or arguments.  I'll elaborate in #9139
