### ISSUE TITLE
GitHub release of nvim does not run on macOS 10.14

### ISSUE THREAD

**Issue by jordan-arenstein** [neovim/neovim#9134]
- `nvim --version`: 0.3.0, 0.3.1, 0.3.2 **only from GitHub Releases, but installs from homebrew work fine**
- Operating system/version: macOS 10.14
- Terminal name/version: iTerm2, Terminal
- `$TERM` :xterm-256color

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
```

Attempting to run a nvim binary produces `Segmentation fault: 11`

The binaries downloaded from github do not run on my computer running macOS 10.14. Corresponding versions installed from homebrew run as expected.

**Comment by jdhao** [comment]
I have also met this issue. So I installed neovim through HomeBrew, though the version is 0.3.1.

**Comment by justinmk** [comment]
Latest [prerelease](https://github.com/neovim/neovim/releases/tag/nightly) was built on macOS 10.13. 

Hopefully it works on 10.14 .

**Comment by jordan-arenstein** [comment]
Still crashing for me.

**Comment by jordan-arenstein** [comment]
Stacktrace from Console:
```
Process:               nvim [55381]
Path:                  /Users/USER/Downloads/*/nvim
Identifier:            nvim
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [55274]
Responsible:           nvim [55381]
User ID:               501

Date/Time:             2018-11-27 23:26:11.122 +0200
OS Version:            Mac OS X 10.14.1 (18B75)
Report Version:        12
Bridge OS Version:     3.0 (14Y667)
Anonymous UUID:        917C986D-D23A-7854-5C88-275CC7369834

Sleep/Wake UUID:       17B86922-B752-45FD-8E7C-72600C710038

Time Awake Since Boot: 150000 seconds
Time Since Wake:       120 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000b8bd968
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [55381]

VM Regions Near 0xb8bd968:
    shared memory          000000000b8b8000-000000000b8bc000 [   16K] r--/rw- SM=SHM  
--> 
    Dispatch continuations 000000000ba00000-000000000ca00000 [ 16.0M] rw-/rwx SM=PRV  

Application Specific Information:
dyld2 mode

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   CoreFoundation                	0x000000010be563f5 -[CFPrefsSource copyOSLogDescription] + 149
1   CoreFoundation                	0x000000010bd141a8 -[CFPrefsPlistSource handleReply:toRequestNewDataMessage:onConnection:retryCount:error:] + 1528
2   CoreFoundation                	0x000000010bd13b83 __93-[CFPrefsSearchListSource handleReply:toRequestNewDataMessage:onConnection:retryCount:error:]_block_invoke + 147
3   libxpc.dylib                  	0x00007fff67dea605 xpc_array_apply + 57
4   CoreFoundation                	0x000000010bd13abc -[CFPrefsSearchListSource handleReply:toRequestNewDataMessage:onConnection:retryCount:error:] + 300
5   CoreFoundation                	0x000000010be98aec __80-[CFPrefsSearchListSource alreadylocked_generationCountFromListOfSources:count:]_block_invoke_3.139 + 76
6   CoreFoundation                	0x000000010bec12b4 -[_CFXPreferences withConnectionForRole:performBlock:] + 36
7   CoreFoundation                	0x000000010be98a95 __80-[CFPrefsSearchListSource alreadylocked_generationCountFromListOfSources:count:]_block_invoke_2.138 + 117
8   libsystem_trace.dylib         	0x00007fff67dc94ef _os_activity_initiate_impl + 53
9   CoreFoundation                	0x000000010be989f2 __80-[CFPrefsSearchListSource alreadylocked_generationCountFromListOfSources:count:]_block_invoke.136 + 114
10  CoreFoundation                	0x000000010be98337 CFPREFERENCES_IS_WAITING_FOR_USER_CFPREFSD + 39
11  CoreFoundation                	0x000000010be9858c -[CFPrefsSearchListSource alreadylocked_generationCountFromListOfSources:count:] + 348
12  CoreFoundation                	0x000000010bd121a6 -[CFPrefsSearchListSource alreadylocked_copyDictionary] + 326
13  CoreFoundation                	0x000000010bd1a21f -[CFPrefsSource copyDictionary] + 47
14  CoreFoundation                	0x000000010bec03dc __54-[_CFXPreferences copyDictionaryForApp:withContainer:]_block_invoke + 28
15  CoreFoundation                	0x000000010be99d39 __108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 297
16  CoreFoundation                	0x000000010be99ba5 -[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 341
17  CoreFoundation                	0x000000010bec0356 -[_CFXPreferences copyDictionaryForApp:withContainer:] + 118
18  CoreFoundation                	0x000000010bd1a169 __CFXPreferencesCopyCurrentApplicationState + 281
19  CoreFoundation                	0x000000010bd199d8 _CFLocaleCopyCurrentGuts + 264
20  nvim                          	0x000000010baafca8 lang_init + 56
21  nvim                          	0x000000010ba92f2f set_init_1 + 7023
22  nvim                          	0x000000010ba25a82 main + 1522
23  libdyld.dylib                 	0x00007fff67bb908d start + 1

Thread 1:: Dispatch queue: com.apple.root.user-interactive-qos.overcommit
0   dyld                          	0x0000000118f4c081 ImageLoaderMachO::libPath(unsigned int) const + 39
1   dyld                          	0x0000000118f4bc1b ImageLoaderMachO::findExportedSymbol(char const*, bool, char const*, ImageLoader const**) const + 123
2   dyld                          	0x0000000118f463c0 ImageLoader::findExportedSymbolAddress(ImageLoader::LinkContext const&, char const*, ImageLoader const*, int, bool, ImageLoader const**, unsigned long*) const + 50
3   dyld                          	0x0000000118f52556 ImageLoaderMachOCompressed::resolveTwolevel(ImageLoader::LinkContext const&, char const*, ImageLoader const*, ImageLoader const*, unsigned int, bool, bool, ImageLoader const**) + 86
4   dyld                          	0x0000000118f527c7 ImageLoaderMachOCompressed::resolve(ImageLoader::LinkContext const&, char const*, unsigned char, long, ImageLoader const**, ImageLoaderMachOCompressed::LastLookup*, bool) + 263
5   dyld                          	0x0000000118f54c48 ImageLoaderMachOCompressed::doBindFastLazySymbol(unsigned int, ImageLoader::LinkContext const&, void (*)(), void (*)()) + 248
6   dyld                          	0x0000000118f38bc6 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 89
7   libdyld.dylib                 	0x00007fff67ba4e1e dyld_stub_binder + 282
8   ???                           	0x000000010c179008 0 + 4497838088
9   CoreFoundation                	0x000000010bd13b83 __93-[CFPrefsSearchListSource handleReply:toRequestNewDataMessage:onConnection:retryCount:error:]_block_invoke + 147
10  libxpc.dylib                  	0x00007fff67dea605 xpc_array_apply + 57
11  CoreFoundation                	0x000000010bd13abc -[CFPrefsSearchListSource handleReply:toRequestNewDataMessage:onConnection:retryCount:error:] + 300
12  CoreFoundation                	0x000000010be987da __80-[CFPrefsSearchListSource alreadylocked_generationCountFromListOfSources:count:]_block_invoke_3 + 58
13  libxpc.dylib                  	0x00007fff67dee9b1 _xpc_connection_reply_callout + 36
14  libxpc.dylib                  	0x00007fff67dee938 _xpc_connection_call_reply_async + 82
15  libdispatch.dylib             	0x00007fff67b6ae39 _dispatch_client_callout3 + 8
16  libdispatch.dylib             	0x00007fff67b813b0 _dispatch_mach_msg_async_reply_invoke + 322
17  libdispatch.dylib             	0x00007fff67b79a7c _dispatch_kevent_worker_thread + 1390
18  libsystem_pthread.dylib       	0x00007fff67daa646 _pthread_wqthread + 419
19  libsystem_pthread.dylib       	0x00007fff67daa435 start_wqthread + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000028  rbx: 0x00007f93c3609920  rcx: 0x00000000000a8002  rdx: 0x00007fff67dc5e14
  rdi: 0x00007f93c3609920  rsi: 0x00007fff38bd94a2  rbp: 0x00007ffee43b6c90  rsp: 0x00007ffee43b6c40
   r8: 0x0000000000000043   r9: 0x0000000000000290  r10: 0x000000010c2b7e50  r11: 0x00007f93c3403320
  r12: 0x000000010c0adb63  r13: 0x000000000b8bd968  r14: 0x0000000000000000  r15: 0x000000010c0adb67
  rip: 0x000000010be563f5  rfl: 0x0000000000010202  cr2: 0x000000000b8bd968
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x10b848000 -        0x10bc08fff +nvim (0) <2A36EC59-6793-3752-A751-6DBC47A9133E> /Users/USER/Downloads/*/nvim
       0x10bcd8000 -        0x10c178fe7 +CoreFoundation (1451) <7AFE9C8F-A562-3AFC-8402-117AA02F57E9> /Users/USER/Downloads/*/CoreFoundation
       0x10c42e000 -        0x10c436ff7 +libintl.8.dylib (0) <2BE4B1C7-92C9-39E9-B4A7-F880907047DB> /Users/USER/Downloads/*/libintl.8.dylib
       0x10c43f000 -        0x10c530ff7 +libiconv.2.dylib (51) <0772997F-4109-38A1-91ED-0F3F16AE99E5> /Users/USER/Downloads/*/libiconv.2.dylib
       0x10c545000 -        0x10c548ffb +libutil.dylib (51.20.1) <216D18E5-0BAF-3EAF-A38E-F6AC37CBABD9> /Users/USER/Downloads/*/libutil.dylib
       0x118f34000 -        0x118fb26a7  dyld (635.2) <1780094A-8FE2-3EAA-B4A3-C4CF14BC5196> /usr/lib/dyld
    0x7fff64c7c000 -     0x7fff64c7dff7  libDiagnosticMessagesClient.dylib (107) <C542CB3C-AA44-3D7F-B88C-79CC31B481AB> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff6502e000 -     0x7fff6502fffb  libSystem.B.dylib (1252.200.5) <D5AFCC78-2AC2-37EB-B0EF-BB00FD38ED00> /usr/lib/libSystem.B.dylib
    0x7fff65288000 -     0x7fff652dfff7  libc++.1.dylib (400.9.4) <D4AB366F-48A9-3C7D-91BD-41198F69DD57> /usr/lib/libc++.1.dylib
    0x7fff652e0000 -     0x7fff652f5fff  libc++abi.dylib (400.17) <BA948A32-9024-3E55-98D4-18E31F6AED25> /usr/lib/libc++abi.dylib
    0x7fff65f43000 -     0x7fff661a6ffb  libicucore.A.dylib (62108.0.1) <969815D4-A345-31BB-82B7-0C3B58CA7E90> /usr/lib/libicucore.A.dylib
    0x7fff66ad4000 -     0x7fff6725afe7  libobjc.A.dylib (750.1) <9CE27EC3-3A12-35D1-8F2F-3550B9668259> /usr/lib/libobjc.A.dylib
    0x7fff679b7000 -     0x7fff679c9ffb  libz.1.dylib (70.200.4) <99A3D725-8388-38B4-B66C-5E9006E6F072> /usr/lib/libz.1.dylib
    0x7fff67a3a000 -     0x7fff67a3eff3  libcache.dylib (81) <FE21A7E9-DBEB-33AC-836B-785AD036ACF4> /usr/lib/system/libcache.dylib
    0x7fff67a3f000 -     0x7fff67a49ff3  libcommonCrypto.dylib (60118.220.1) <1099E427-6E81-3059-87AF-6F5FD81CA998> /usr/lib/system/libcommonCrypto.dylib
    0x7fff67a4a000 -     0x7fff67a51fff  libcompiler_rt.dylib (63.4) <A4D9CF37-D076-3CE9-95F1-DA89DA1601B6> /usr/lib/system/libcompiler_rt.dylib
    0x7fff67a52000 -     0x7fff67a5bff3  libcopyfile.dylib (146.200.3) <4BCDADBF-79F5-3829-B47D-64DA0D44BCBF> /usr/lib/system/libcopyfile.dylib
    0x7fff67a5c000 -     0x7fff67ae0fdf  libcorecrypto.dylib (602.220.6) <E1046E01-A2FD-35B4-B018-ACC372F3880E> /usr/lib/system/libcorecrypto.dylib
    0x7fff67b67000 -     0x7fff67ba1ff7  libdispatch.dylib (1008.220.2) <D8B56783-152A-34A8-94E9-8E6BAE049384> /usr/lib/system/libdispatch.dylib
    0x7fff67ba2000 -     0x7fff67bd1fff  libdyld.dylib (635.2) <1B79A5CE-125F-301F-A441-C1869573AED0> /usr/lib/system/libdyld.dylib
    0x7fff67bd2000 -     0x7fff67bd2ffb  libkeymgr.dylib (30) <A73AA788-C35C-3284-BFCA-95B1BBDF0CF3> /usr/lib/system/libkeymgr.dylib
    0x7fff67be0000 -     0x7fff67be0ff7  liblaunch.dylib (1336.220.5) <95EB6EAF-2DC5-344F-BADB-CA4E35E4E503> /usr/lib/system/liblaunch.dylib
    0x7fff67be1000 -     0x7fff67be6fff  libmacho.dylib (921) <ECC4E97C-575E-3A08-8191-BF02D7D4E637> /usr/lib/system/libmacho.dylib
    0x7fff67be7000 -     0x7fff67be9ffb  libquarantine.dylib (86.220.1) <6AE5AEEC-A9FD-3CF8-92DD-12B5AFBE12DE> /usr/lib/system/libquarantine.dylib
    0x7fff67bea000 -     0x7fff67bebff3  libremovefile.dylib (45.200.2) <D74A307B-3DC7-3992-B16C-DACB8207BE13> /usr/lib/system/libremovefile.dylib
    0x7fff67bec000 -     0x7fff67c03ff3  libsystem_asl.dylib (356.200.4) <EC9D8AD4-E5CB-3765-804A-9E1E9DC045D2> /usr/lib/system/libsystem_asl.dylib
    0x7fff67c04000 -     0x7fff67c04fff  libsystem_blocks.dylib (73) <26419398-C30C-30F1-B656-A92AFA9560F6> /usr/lib/system/libsystem_blocks.dylib
    0x7fff67c05000 -     0x7fff67c8dfff  libsystem_c.dylib (1272.200.26) <3DEEE96E-6DF6-35AD-8654-D69AC26B907B> /usr/lib/system/libsystem_c.dylib
    0x7fff67c8e000 -     0x7fff67c91ff7  libsystem_configuration.dylib (963.200.27) <02CC3996-B34E-333C-8806-AE2699D34424> /usr/lib/system/libsystem_configuration.dylib
    0x7fff67c92000 -     0x7fff67c95ff7  libsystem_coreservices.dylib (66) <254B6849-2C8F-302C-8616-B8324A11AB30> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff67c96000 -     0x7fff67c9cffb  libsystem_darwin.dylib (1272.200.26) <974E9EF7-DE72-34B7-B056-0A81C10DF8EB> /usr/lib/system/libsystem_darwin.dylib
    0x7fff67c9d000 -     0x7fff67ca3ff7  libsystem_dnssd.dylib (878.200.35) <FFC665AA-B257-35AD-BD8B-32FD42C2EEC1> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff67ca4000 -     0x7fff67cf0ff3  libsystem_info.dylib (517.200.9) <0707C387-D7DE-372E-8FF1-3DE5C91932D6> /usr/lib/system/libsystem_info.dylib
    0x7fff67cf1000 -     0x7fff67d18ff7  libsystem_kernel.dylib (4903.221.2) <0E882078-7330-3B49-AA5D-3CDB5645A4E5> /usr/lib/system/libsystem_kernel.dylib
    0x7fff67d19000 -     0x7fff67d64ff7  libsystem_m.dylib (3158.200.7) <43D1796B-954F-37D6-B1AC-9D80DF0655A2> /usr/lib/system/libsystem_m.dylib
    0x7fff67d65000 -     0x7fff67d89ff7  libsystem_malloc.dylib (166.220.1) <3B196122-4E0D-3E3F-AA3E-5115B976DE26> /usr/lib/system/libsystem_malloc.dylib
    0x7fff67d8a000 -     0x7fff67d95ff3  libsystem_networkextension.dylib (767.220.1) <C54EB8F6-F305-3452-8DB1-F7DA6859AF8C> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff67d96000 -     0x7fff67d9dfff  libsystem_notify.dylib (172.200.21) <BCCB222F-DC64-3954-A836-DCCE6659CA5A> /usr/lib/system/libsystem_notify.dylib
    0x7fff67d9e000 -     0x7fff67da7fef  libsystem_platform.dylib (177.200.16) <B75B04AD-69FE-3ADE-84D2-C17972FC8F49> /usr/lib/system/libsystem_platform.dylib
    0x7fff67da8000 -     0x7fff67db2fff  libsystem_pthread.dylib (330.220.2) <4958273C-4273-3501-8137-E44249E10D9C> /usr/lib/system/libsystem_pthread.dylib
    0x7fff67db3000 -     0x7fff67db6ff7  libsystem_sandbox.dylib (851.220.9) <4D6433A8-C703-3ED9-82EB-B9E481A0FD2F> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff67db7000 -     0x7fff67db9ff3  libsystem_secinit.dylib (30.220.1) <6C681113-8C48-3256-BEF6-0C3723DEB926> /usr/lib/system/libsystem_secinit.dylib
    0x7fff67dba000 -     0x7fff67dc1ff7  libsystem_symptoms.dylib (820.227.2) <3147D594-F41F-35FD-BF0B-6B8B66A407DE> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff67dc2000 -     0x7fff67dd7ff7  libsystem_trace.dylib (906.220.1) <D5045DC5-A165-3238-A470-1796F12BF84F> /usr/lib/system/libsystem_trace.dylib
    0x7fff67dd9000 -     0x7fff67ddeffb  libunwind.dylib (35.4) <41222EF6-2233-3CF4-947A-15D48CB8C030> /usr/lib/system/libunwind.dylib
    0x7fff67ddf000 -     0x7fff67e0ffff  libxpc.dylib (1336.220.5) <B2137772-E202-3656-A089-F6DD517007D5> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 11529232
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=240.9M resident=0K(0%) swapped_out_or_unallocated=240.9M(100%)
Writable regions: Total=54.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=54.1M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        2 
Dispatch continuations            16.0M        2 
Kernel Alloc Once                    8K        2 
MALLOC                            29.1M        9 
MALLOC guard page                   16K        5 
STACK GUARD                       56.0M        3 
Stack                             8712K        3 
__DATA                            4028K       49 
__LINKEDIT                       217.3M        8 
__TEXT                            23.6M       47 
__UNICODE                          560K        2 
mapped file                         24K        2 
shared memory                       44K        6 
===========                     =======  ======= 
TOTAL       
```

Output of `otool -L ./bin/nvim`

```
./bin/nvim:
	@executable_path/../libs/CoreFoundation (compatibility version 150.0.0, current version 1451.0.0)
	@executable_path/../libs/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	@executable_path/../libs/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	@executable_path/../libs/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by justinmk** [comment]
This should have been fixed in #8804. Are you sure you're using the nightly (0.3.2 prerelease) ?

**Comment by jordan-arenstein** [comment]
This is using the nightly (top download on releases page).

`nvim --version` also causes a segmentation fault.

**Comment by mhinz** [comment]
What's the output of `locale`?

**Comment by yangliping** [comment]
I have the same issue

```
$ locale
LANG=
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

$ ./nvim --version
Segmentation fault: 11

$ unset LC_ALL LC_CTYPE

$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

$ ./nvim --version
Segmentation fault: 11

$ export LC_ALL="zh_CN.UTF-8"

$ locale
LANG=
LC_COLLATE="zh_CN.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_ALL="zh_CN.UTF-8"

$ ./nvim --version
NVIM v0.3.2-940-gbd32d8cf9
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode-9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by justinmk** [comment]
Please try these steps:

- Toggle or switch your locale in macOS system preferences (rather than `$LANG`). Choose any locale other than the one you normally use.
    - Then try to run the `nvim` that crashes, if you didn't already delete it.
- Try the [latest nightly](https://github.com/neovim/neovim/releases/tag/nightly), it was built with a newer version of Xcode.

---

### Further info

- https://objective-see.com/blog/blog_0x34.html
    - Behavior of `CFLocaleCopyCurrent` is cached and may change after user selects a different locale in macOS system preferences.
- https://savannah.gnu.org/bugs/?43404
  - Not sure what to make this, but it sounds like `libintl` may conflict with our use of `setlocale` and/or `CFLocaleCopyCurrent` ? 
  - We could try building without `libintl` in bot-ci.

**Comment by git-brandon** [comment]
I also was having the same issue until I changed my locale settings and rebooted. That seemed to fix the problem.

**Comment by mhinz** [comment]
Thanks for the reports. By now we're pretty sure what the problem is.

https://github.com/neovim/neovim/blob/master/src/nvim/os/lang.c currently assumes that functions like `CFLocaleCopyCurrent()` always return valid values, but in certain situations (which are not specified by Apple) they don't.

So, adding more NULL checks to that file is easy. The harder part is figuring out what value to fall back in these cases.

**Comment by dm1try** [comment]
FYI, the issue is reproducible only for prebuilt binaries on my machine.
It is somehow related to dynamically loaded `CoreFoundation`
see
```
nvim-osx64  export LANG=""
nvim-osx64  bin/nvim
dyld: loaded: /Users/dmitrydedov/Downloads/nvim-osx64/bin/nvim
dyld: loaded: /Users/dmitrydedov/Downloads/nvim-osx64/bin/../libs/CoreFoundation
dyld: loaded: /Users/dmitrydedov/Downloads/nvim-osx64/bin/../libs/libintl.8.dylib
dyld: loaded: /Users/dmitrydedov/Downloads/nvim-osx64/bin/../libs/libiconv.2.dylib
dyld: loaded: /usr/lib/libSystem.B.dylib
dyld: loaded: /Users/dmitrydedov/Downloads/nvim-osx64/bin/../libs/libutil.dylib
dyld: loaded: /usr/lib/libDiagnosticMessagesClient.dylib
dyld: loaded: /usr/lib/libicucore.A.dylib
dyld: loaded: /usr/lib/libobjc.A.dylib
dyld: loaded: /usr/lib/libz.1.dylib
dyld: loaded: /usr/lib/system/libcache.dylib
dyld: loaded: /usr/lib/system/libcommonCrypto.dylib
dyld: loaded: /usr/lib/system/libcompiler_rt.dylib
dyld: loaded: /usr/lib/system/libcopyfile.dylib
dyld: loaded: /usr/lib/system/libcorecrypto.dylib
dyld: loaded: /usr/lib/system/libdispatch.dylib
dyld: loaded: /usr/lib/system/libdyld.dylib
dyld: loaded: /usr/lib/system/libkeymgr.dylib
dyld: loaded: /usr/lib/system/liblaunch.dylib
dyld: loaded: /usr/lib/system/libmacho.dylib
dyld: loaded: /usr/lib/system/libquarantine.dylib
dyld: loaded: /usr/lib/system/libremovefile.dylib
dyld: loaded: /usr/lib/system/libsystem_asl.dylib
dyld: loaded: /usr/lib/system/libsystem_blocks.dylib
dyld: loaded: /usr/lib/system/libsystem_c.dylib
dyld: loaded: /usr/lib/system/libsystem_configuration.dylib
dyld: loaded: /usr/lib/system/libsystem_coreservices.dylib
dyld: loaded: /usr/lib/system/libsystem_darwin.dylib
dyld: loaded: /usr/lib/system/libsystem_dnssd.dylib
dyld: loaded: /usr/lib/system/libsystem_info.dylib
dyld: loaded: /usr/lib/system/libsystem_m.dylib
dyld: loaded: /usr/lib/system/libsystem_malloc.dylib
dyld: loaded: /usr/lib/system/libsystem_networkextension.dylib
dyld: loaded: /usr/lib/system/libsystem_notify.dylib
dyld: loaded: /usr/lib/system/libsystem_sandbox.dylib
dyld: loaded: /usr/lib/system/libsystem_secinit.dylib
dyld: loaded: /usr/lib/system/libsystem_kernel.dylib
dyld: loaded: /usr/lib/system/libsystem_platform.dylib
dyld: loaded: /usr/lib/system/libsystem_pthread.dylib
dyld: loaded: /usr/lib/system/libsystem_symptoms.dylib
dyld: loaded: /usr/lib/system/libsystem_trace.dylib
dyld: loaded: /usr/lib/system/libunwind.dylib
dyld: loaded: /usr/lib/system/libxpc.dylib
dyld: loaded: /usr/lib/libc++abi.dylib
dyld: loaded: /usr/lib/libc++.1.dylib
dyld: unloaded: /usr/lib/libiconv.2.dylib
dyld: unloaded: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
[1]    67759 segmentation fault  bin/nvim
```
but
```
nvim-osx64  DYLD_LIBRARY_PATH=/System/Library/Frameworks/CoreFoundation.framework/Versions/A/ bin/nvim
dyld: loaded: /Users/dmitrydedov/Downloads/nvim-osx64/bin/nvim
dyld: loaded: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
dyld: loaded: /Users/dmitrydedov/Downloads/nvim-osx64/bin/../libs/libintl.8.dylib
dyld: loaded: /Users/dmitrydedov/Downloads/nvim-osx64/bin/../libs/libiconv.2.dylib
dyld: loaded: /usr/lib/libSystem.B.dylib
dyld: loaded: /Users/dmitrydedov/Downloads/nvim-osx64/bin/../libs/libutil.dylib
dyld: loaded: /usr/lib/libobjc.A.dylib
dyld: loaded: /usr/lib/libDiagnosticMessagesClient.dylib
dyld: loaded: /usr/lib/libicucore.A.dylib
dyld: loaded: /usr/lib/libz.1.dylib
dyld: loaded: /usr/lib/libc++abi.dylib
dyld: loaded: /usr/lib/libc++.1.dylib
dyld: loaded: /usr/lib/system/libcache.dylib
dyld: loaded: /usr/lib/system/libcommonCrypto.dylib
dyld: loaded: /usr/lib/system/libcompiler_rt.dylib
dyld: loaded: /usr/lib/system/libcopyfile.dylib
dyld: loaded: /usr/lib/system/libcorecrypto.dylib
dyld: loaded: /usr/lib/system/libdispatch.dylib
dyld: loaded: /usr/lib/system/libdyld.dylib
dyld: loaded: /usr/lib/system/libkeymgr.dylib
dyld: loaded: /usr/lib/system/liblaunch.dylib
dyld: loaded: /usr/lib/system/libmacho.dylib
dyld: loaded: /usr/lib/system/libquarantine.dylib
dyld: loaded: /usr/lib/system/libremovefile.dylib
dyld: loaded: /usr/lib/system/libsystem_asl.dylib
dyld: loaded: /usr/lib/system/libsystem_blocks.dylib
dyld: loaded: /usr/lib/system/libsystem_c.dylib
dyld: loaded: /usr/lib/system/libsystem_configuration.dylib
dyld: loaded: /usr/lib/system/libsystem_coreservices.dylib
dyld: loaded: /usr/lib/system/libsystem_darwin.dylib
dyld: loaded: /usr/lib/system/libsystem_dnssd.dylib
dyld: loaded: /usr/lib/system/libsystem_info.dylib
dyld: loaded: /usr/lib/system/libsystem_m.dylib
dyld: loaded: /usr/lib/system/libsystem_malloc.dylib
dyld: loaded: /usr/lib/system/libsystem_networkextension.dylib
dyld: loaded: /usr/lib/system/libsystem_notify.dylib
dyld: loaded: /usr/lib/system/libsystem_sandbox.dylib
dyld: loaded: /usr/lib/system/libsystem_secinit.dylib
dyld: loaded: /usr/lib/system/libsystem_kernel.dylib
dyld: loaded: /usr/lib/system/libsystem_platform.dylib
dyld: loaded: /usr/lib/system/libsystem_pthread.dylib
dyld: loaded: /usr/lib/system/libsystem_symptoms.dylib
dyld: loaded: /usr/lib/system/libsystem_trace.dylib
dyld: loaded: /usr/lib/system/libunwind.dylib
dyld: loaded: /usr/lib/system/libxpc.dylib
dyld: unloaded: /usr/lib/libiconv.2.dylib
```

**Comment by dm1try** [comment]
> CFLocaleCopyCurrent() always return valid values, but in certain situations (which are not specified by Apple) they don't.

according to the report above and my testing, the error looks like something related to CoreFoundation internals. so simple check for `NULL` unlikely helps.

```
nvim-osx64  lldb bin/nvim
(lldb) target create "bin/nvim"
Current executable set to 'bin/nvim' (x86_64).
(lldb) run
Process 67833 launched: '/Users/dmitrydedov/Downloads/nvim-osx64/bin/nvim' (x86_64)
Process 67833 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8e3108)
    frame #0: 0x000000000004aa63 CoreFoundation`generationCountFromListOfSources + 195
CoreFoundation`generationCountFromListOfSources:
```

**Comment by justinmk** [comment]
I think we should not package CoreFoundation, instead we assume that it is ABI-compatible. It should be skipped [here](https://github.com/neovim/bot-ci/blob/master/ci/package-macos.sh#L34).

**Comment by justinmk** [comment]
> I think we should not package CoreFoundation, instead we assume that it is ABI-compatible. 

Done, so CoreFoundation is not present in the latest nightly. Please try it:

https://github.com/neovim/neovim/releases/tag/nightly

**Comment by dm1try** [comment]
@justinmk works for me
before:
```
nvim-osx64  bin/nvim -v
NVIM v0.3.2-980-g857a7312d
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
nvim-osx64  LANG="" bin/nvim --headless -c 'echo $LANG|exit'
[1]    70554 segmentation fault  LANG="" bin/nvim --headless -c 'echo $LANG|exit'
```
after
```
nvim-osx64  bin/nvim -v
NVIM v0.3.2-996-g55c518588
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
nvim-osx64  LANG="" bin/nvim --headless -c 'echo $LANG|exit'
en_US% 
```
```
nvim-osx64  echo $LANG
en_US.UTF-8
```

**Comment by justinmk** [comment]
Thanks @dm1try . Fixed by https://github.com/neovim/bot-ci/commit/05384567778d00414e926dda23af2b05510d08bf

**Comment by zpz** [comment]
This problem is still with me. `brew install neovim` installs version 0.3.4. Mac version 10.13.x. Gets `seg 11` error.
