### ISSUE TITLE
undofile conflicts with wa on InsertLeave

### ISSUE THREAD

**Issue by swalladge** [neovim/neovim#9510]
- `nvim --version`: present in 0.3.3 and v0.4.0-150-g279043d62
- Vim (version: ) behaves differently? 8.1.0570 (similar behaviour)
- Operating system/version: Archlinux
- Terminal name/version: urxvt
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:e test.txt
:set undofile
:autocmd InsertLeave ?* wa
ofoo<esc>u
```

### Actual behaviour

Does not undo inserting `foo`. Pressing `u` again will perform the undo.

With vim 8.1.0570, pressing `u` multiple times will refuse to undo anything.

### Expected behaviour

Does undo inserting `foo`

**Comment by swalladge** [comment]
Update: via git bisect I have tracked the source of the problem to 3c41df269173b68aa5572df8c5b7cae408229b88 . I haven't had a chance to read through it, but the commit message is related:

> vim-patch:8.1.0256: using setline() in TextChangedI splits undo

**Comment by kutsan** [comment]
Is there any workaround to this? I've been having this problem quite a while and it's frustrating to use with auto save functionality.

**Comment by justinmk** [comment]
@kutsan what Nvim version exactly are you using? there was likely a followup to `vim-patch:8.1.0256` , either we need to merge that or perhaps this is fixed in Nvim master.

**Comment by kutsan** [comment]
@justinmk It's the latest release `v0.4.3`.

**Comment by kutsan** [comment]
@justinmk I just tested on `master` and problem still persists FYI.

**Comment by kutsan** [comment]
@justinmk It's fixed in https://github.com/vim/vim/commit/db93495d276642f63f80471fbcb900b9aa1e9e42. Could you please include it to neovim repository.

**Comment by swalladge** [comment]
@kutsan nice find! It's included in this PR, so hopefully will be merged soon: https://github.com/neovim/neovim/pull/12203 :tada:

**Comment by swalladge** [comment]
Can confirm this is now fixed on master since #12203 merged. :grin: 

CC @kutsan @justinmk

**Comment by kutsan** [comment]
Thank you to whoever involved to make this happen! 

cc. @janlazo
